// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cifar10_axis_wrapper_cifar10_axis_wrapper,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=13.990063,HLS_SYN_LAT=232259,HLS_SYN_TPT=78850,HLS_SYN_MEM=120,HLS_SYN_DSP=0,HLS_SYN_FF=23661,HLS_SYN_LUT=36418,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_axis_wrapper (
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        s_axis_TDATA,
        s_axis_TKEEP,
        s_axis_TSTRB,
        s_axis_TLAST,
        m_axis_TDATA,
        m_axis_TKEEP,
        m_axis_TSTRB,
        m_axis_TLAST,
        s_axis_TVALID,
        s_axis_TREADY,
        m_axis_TVALID,
        m_axis_TREADY
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] s_axis_TDATA;
input  [3:0] s_axis_TKEEP;
input  [3:0] s_axis_TSTRB;
input  [0:0] s_axis_TLAST;
output  [31:0] m_axis_TDATA;
output  [3:0] m_axis_TKEEP;
output  [3:0] m_axis_TSTRB;
output  [0:0] m_axis_TLAST;
input   s_axis_TVALID;
output   s_axis_TREADY;
output   m_axis_TVALID;
input   m_axis_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    axis_to_hls4ml_input_U0_ap_start;
wire    axis_to_hls4ml_input_U0_ap_done;
wire    axis_to_hls4ml_input_U0_ap_continue;
wire    axis_to_hls4ml_input_U0_ap_idle;
wire    axis_to_hls4ml_input_U0_ap_ready;
wire   [26:0] axis_to_hls4ml_input_U0_nn_in_din;
wire    axis_to_hls4ml_input_U0_nn_in_write;
wire   [31:0] axis_to_hls4ml_input_U0_nn_in_num_data_valid;
wire   [31:0] axis_to_hls4ml_input_U0_nn_in_fifo_cap;
wire    axis_to_hls4ml_input_U0_start_out;
wire    axis_to_hls4ml_input_U0_start_write;
wire    axis_to_hls4ml_input_U0_s_axis_TREADY;
wire    cifar10_hls_core_U0_ap_start;
wire    cifar10_hls_core_U0_start_out;
wire    cifar10_hls_core_U0_start_write;
wire    cifar10_hls_core_U0_nn_in_read;
wire   [119:0] cifar10_hls_core_U0_nn_out_din;
wire    cifar10_hls_core_U0_nn_out_write;
wire    cifar10_hls_core_U0_ap_done;
wire    cifar10_hls_core_U0_ap_ready;
wire    cifar10_hls_core_U0_ap_idle;
wire    cifar10_hls_core_U0_ap_continue;
wire    hls4ml_output_to_axis_U0_ap_start;
wire    hls4ml_output_to_axis_U0_ap_done;
wire    hls4ml_output_to_axis_U0_ap_continue;
wire    hls4ml_output_to_axis_U0_ap_idle;
wire    hls4ml_output_to_axis_U0_ap_ready;
wire    hls4ml_output_to_axis_U0_nn_out_read;
wire   [31:0] hls4ml_output_to_axis_U0_m_axis_TDATA;
wire    hls4ml_output_to_axis_U0_m_axis_TVALID;
wire   [3:0] hls4ml_output_to_axis_U0_m_axis_TKEEP;
wire   [3:0] hls4ml_output_to_axis_U0_m_axis_TSTRB;
wire   [0:0] hls4ml_output_to_axis_U0_m_axis_TLAST;
wire    nn_in_full_n;
wire   [26:0] nn_in_dout;
wire    nn_in_empty_n;
wire   [4:0] nn_in_num_data_valid;
wire   [4:0] nn_in_fifo_cap;
wire    nn_out_full_n;
wire   [119:0] nn_out_dout;
wire    nn_out_empty_n;
wire   [2:0] nn_out_num_data_valid;
wire   [2:0] nn_out_fifo_cap;
wire   [0:0] start_for_cifar10_hls_core_U0_din;
wire    start_for_cifar10_hls_core_U0_full_n;
wire   [0:0] start_for_cifar10_hls_core_U0_dout;
wire    start_for_cifar10_hls_core_U0_empty_n;
wire   [0:0] start_for_hls4ml_output_to_axis_U0_din;
wire    start_for_hls4ml_output_to_axis_U0_full_n;
wire   [0:0] start_for_hls4ml_output_to_axis_U0_dout;
wire    start_for_hls4ml_output_to_axis_U0_empty_n;

cifar10_axis_wrapper_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cifar10_axis_wrapper_axis_to_hls4ml_input axis_to_hls4ml_input_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_hls4ml_input_U0_ap_start),
    .start_full_n(start_for_cifar10_hls_core_U0_full_n),
    .ap_done(axis_to_hls4ml_input_U0_ap_done),
    .ap_continue(axis_to_hls4ml_input_U0_ap_continue),
    .ap_idle(axis_to_hls4ml_input_U0_ap_idle),
    .ap_ready(axis_to_hls4ml_input_U0_ap_ready),
    .s_axis_TVALID(s_axis_TVALID),
    .nn_in_din(axis_to_hls4ml_input_U0_nn_in_din),
    .nn_in_full_n(nn_in_full_n),
    .nn_in_write(axis_to_hls4ml_input_U0_nn_in_write),
    .nn_in_num_data_valid(axis_to_hls4ml_input_U0_nn_in_num_data_valid),
    .nn_in_fifo_cap(axis_to_hls4ml_input_U0_nn_in_fifo_cap),
    .start_out(axis_to_hls4ml_input_U0_start_out),
    .start_write(axis_to_hls4ml_input_U0_start_write),
    .s_axis_TDATA(s_axis_TDATA),
    .s_axis_TREADY(axis_to_hls4ml_input_U0_s_axis_TREADY),
    .s_axis_TKEEP(s_axis_TKEEP),
    .s_axis_TSTRB(s_axis_TSTRB),
    .s_axis_TLAST(s_axis_TLAST)
);

cifar10_axis_wrapper_cifar10_hls_core cifar10_hls_core_U0(
    .ap_start(cifar10_hls_core_U0_ap_start),
    .start_full_n(start_for_hls4ml_output_to_axis_U0_full_n),
    .start_out(cifar10_hls_core_U0_start_out),
    .start_write(cifar10_hls_core_U0_start_write),
    .nn_in_dout(nn_in_dout),
    .nn_in_empty_n(nn_in_empty_n),
    .nn_in_read(cifar10_hls_core_U0_nn_in_read),
    .nn_out_din(cifar10_hls_core_U0_nn_out_din),
    .nn_out_full_n(nn_out_full_n),
    .nn_out_write(cifar10_hls_core_U0_nn_out_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_done(cifar10_hls_core_U0_ap_done),
    .ap_ready(cifar10_hls_core_U0_ap_ready),
    .ap_idle(cifar10_hls_core_U0_ap_idle),
    .ap_continue(cifar10_hls_core_U0_ap_continue)
);

cifar10_axis_wrapper_hls4ml_output_to_axis hls4ml_output_to_axis_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(hls4ml_output_to_axis_U0_ap_start),
    .ap_done(hls4ml_output_to_axis_U0_ap_done),
    .ap_continue(hls4ml_output_to_axis_U0_ap_continue),
    .ap_idle(hls4ml_output_to_axis_U0_ap_idle),
    .ap_ready(hls4ml_output_to_axis_U0_ap_ready),
    .nn_out_dout(nn_out_dout),
    .nn_out_empty_n(nn_out_empty_n),
    .nn_out_read(hls4ml_output_to_axis_U0_nn_out_read),
    .nn_out_num_data_valid(nn_out_num_data_valid),
    .nn_out_fifo_cap(nn_out_fifo_cap),
    .m_axis_TDATA(hls4ml_output_to_axis_U0_m_axis_TDATA),
    .m_axis_TVALID(hls4ml_output_to_axis_U0_m_axis_TVALID),
    .m_axis_TREADY(m_axis_TREADY),
    .m_axis_TKEEP(hls4ml_output_to_axis_U0_m_axis_TKEEP),
    .m_axis_TSTRB(hls4ml_output_to_axis_U0_m_axis_TSTRB),
    .m_axis_TLAST(hls4ml_output_to_axis_U0_m_axis_TLAST)
);

cifar10_axis_wrapper_fifo_w27_d16_S nn_in_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_hls4ml_input_U0_nn_in_din),
    .if_full_n(nn_in_full_n),
    .if_write(axis_to_hls4ml_input_U0_nn_in_write),
    .if_dout(nn_in_dout),
    .if_empty_n(nn_in_empty_n),
    .if_read(cifar10_hls_core_U0_nn_in_read),
    .if_num_data_valid(nn_in_num_data_valid),
    .if_fifo_cap(nn_in_fifo_cap)
);

cifar10_axis_wrapper_fifo_w120_d2_S nn_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(cifar10_hls_core_U0_nn_out_din),
    .if_full_n(nn_out_full_n),
    .if_write(cifar10_hls_core_U0_nn_out_write),
    .if_dout(nn_out_dout),
    .if_empty_n(nn_out_empty_n),
    .if_read(hls4ml_output_to_axis_U0_nn_out_read),
    .if_num_data_valid(nn_out_num_data_valid),
    .if_fifo_cap(nn_out_fifo_cap)
);

cifar10_axis_wrapper_start_for_cifar10_hls_core_U0 start_for_cifar10_hls_core_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_cifar10_hls_core_U0_din),
    .if_full_n(start_for_cifar10_hls_core_U0_full_n),
    .if_write(axis_to_hls4ml_input_U0_start_write),
    .if_dout(start_for_cifar10_hls_core_U0_dout),
    .if_empty_n(start_for_cifar10_hls_core_U0_empty_n),
    .if_read(cifar10_hls_core_U0_ap_ready)
);

cifar10_axis_wrapper_start_for_hls4ml_output_to_axis_U0 start_for_hls4ml_output_to_axis_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hls4ml_output_to_axis_U0_din),
    .if_full_n(start_for_hls4ml_output_to_axis_U0_full_n),
    .if_write(cifar10_hls_core_U0_start_write),
    .if_dout(start_for_hls4ml_output_to_axis_U0_dout),
    .if_empty_n(start_for_hls4ml_output_to_axis_U0_empty_n),
    .if_read(hls4ml_output_to_axis_U0_ap_ready)
);

assign ap_done = hls4ml_output_to_axis_U0_ap_done;

assign ap_idle = (hls4ml_output_to_axis_U0_ap_idle & cifar10_hls_core_U0_ap_idle & axis_to_hls4ml_input_U0_ap_idle);

assign ap_ready = axis_to_hls4ml_input_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign axis_to_hls4ml_input_U0_ap_continue = 1'b1;

assign axis_to_hls4ml_input_U0_ap_start = ap_start;

assign axis_to_hls4ml_input_U0_nn_in_fifo_cap = nn_in_fifo_cap;

assign axis_to_hls4ml_input_U0_nn_in_num_data_valid = nn_in_num_data_valid;

assign cifar10_hls_core_U0_ap_continue = 1'b1;

assign cifar10_hls_core_U0_ap_start = start_for_cifar10_hls_core_U0_empty_n;

assign hls4ml_output_to_axis_U0_ap_continue = 1'b1;

assign hls4ml_output_to_axis_U0_ap_start = start_for_hls4ml_output_to_axis_U0_empty_n;

assign m_axis_TDATA = hls4ml_output_to_axis_U0_m_axis_TDATA;

assign m_axis_TKEEP = hls4ml_output_to_axis_U0_m_axis_TKEEP;

assign m_axis_TLAST = hls4ml_output_to_axis_U0_m_axis_TLAST;

assign m_axis_TSTRB = hls4ml_output_to_axis_U0_m_axis_TSTRB;

assign m_axis_TVALID = hls4ml_output_to_axis_U0_m_axis_TVALID;

assign s_axis_TREADY = axis_to_hls4ml_input_U0_s_axis_TREADY;

assign start_for_cifar10_hls_core_U0_din = 1'b1;

assign start_for_hls4ml_output_to_axis_U0_din = 1'b1;

endmodule //cifar10_axis_wrapper
