// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_axis_wrapper_relu_array_ap_fixed_14u_array_ap_fixed_10_4_0_3_0_14u_relu_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer5_out_dout,
        layer5_out_empty_n,
        layer5_out_read,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer6_out_din,
        layer6_out_full_n,
        layer6_out_write,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [139:0] layer5_out_dout;
input   layer5_out_empty_n;
output   layer5_out_read;
input  [8:0] layer5_out_num_data_valid;
input  [8:0] layer5_out_fifo_cap;
output  [139:0] layer6_out_din;
input   layer6_out_full_n;
output   layer6_out_write;
input  [31:0] layer6_out_num_data_valid;
input  [31:0] layer6_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer5_out_read;
reg layer6_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_619_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer5_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer6_out_blk_n;
wire   [8:0] select_ln51_fu_423_p3;
reg   [8:0] select_ln51_reg_712;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [8:0] select_ln51_62_fu_437_p3;
reg   [8:0] select_ln51_62_reg_717;
wire   [8:0] select_ln51_63_fu_451_p3;
reg   [8:0] select_ln51_63_reg_722;
wire   [8:0] select_ln51_64_fu_465_p3;
reg   [8:0] select_ln51_64_reg_727;
wire   [8:0] select_ln51_65_fu_479_p3;
reg   [8:0] select_ln51_65_reg_732;
wire   [8:0] select_ln51_66_fu_493_p3;
reg   [8:0] select_ln51_66_reg_737;
wire   [8:0] select_ln51_67_fu_507_p3;
reg   [8:0] select_ln51_67_reg_742;
wire   [8:0] select_ln51_68_fu_521_p3;
reg   [8:0] select_ln51_68_reg_747;
wire   [8:0] select_ln51_69_fu_535_p3;
reg   [8:0] select_ln51_69_reg_752;
wire   [8:0] select_ln51_70_fu_549_p3;
reg   [8:0] select_ln51_70_reg_757;
wire   [8:0] select_ln51_71_fu_563_p3;
reg   [8:0] select_ln51_71_reg_762;
wire   [8:0] select_ln51_72_fu_577_p3;
reg   [8:0] select_ln51_72_reg_767;
wire   [8:0] select_ln51_73_fu_591_p3;
reg   [8:0] select_ln51_73_reg_772;
wire   [8:0] select_ln51_74_fu_605_p3;
reg   [8:0] select_ln51_74_reg_777;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] i_fu_124;
wire   [7:0] i_9_fu_613_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_8;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [9:0] trunc_ln44_fu_149_p1;
wire   [0:0] icmp_ln51_fu_417_p2;
wire   [8:0] trunc_ln44_103_fu_153_p1;
wire   [9:0] trunc_ln44_62_fu_157_p4;
wire   [0:0] icmp_ln51_62_fu_431_p2;
wire   [8:0] trunc_ln44_s_fu_167_p4;
wire   [9:0] trunc_ln44_63_fu_177_p4;
wire   [0:0] icmp_ln51_63_fu_445_p2;
wire   [8:0] trunc_ln44_89_fu_187_p4;
wire   [9:0] trunc_ln44_64_fu_197_p4;
wire   [0:0] icmp_ln51_64_fu_459_p2;
wire   [8:0] trunc_ln44_90_fu_207_p4;
wire   [9:0] trunc_ln44_65_fu_217_p4;
wire   [0:0] icmp_ln51_65_fu_473_p2;
wire   [8:0] trunc_ln44_91_fu_227_p4;
wire   [9:0] trunc_ln44_66_fu_237_p4;
wire   [0:0] icmp_ln51_66_fu_487_p2;
wire   [8:0] trunc_ln44_92_fu_247_p4;
wire   [9:0] trunc_ln44_67_fu_257_p4;
wire   [0:0] icmp_ln51_67_fu_501_p2;
wire   [8:0] trunc_ln44_93_fu_267_p4;
wire   [9:0] trunc_ln44_68_fu_277_p4;
wire   [0:0] icmp_ln51_68_fu_515_p2;
wire   [8:0] trunc_ln44_94_fu_287_p4;
wire   [9:0] trunc_ln44_69_fu_297_p4;
wire   [0:0] icmp_ln51_69_fu_529_p2;
wire   [8:0] trunc_ln44_95_fu_307_p4;
wire   [9:0] trunc_ln44_70_fu_317_p4;
wire   [0:0] icmp_ln51_70_fu_543_p2;
wire   [8:0] trunc_ln44_96_fu_327_p4;
wire   [9:0] trunc_ln44_71_fu_337_p4;
wire   [0:0] icmp_ln51_71_fu_557_p2;
wire   [8:0] trunc_ln44_97_fu_347_p4;
wire   [9:0] trunc_ln44_72_fu_357_p4;
wire   [0:0] icmp_ln51_72_fu_571_p2;
wire   [8:0] trunc_ln44_98_fu_367_p4;
wire   [9:0] trunc_ln44_73_fu_377_p4;
wire   [0:0] icmp_ln51_73_fu_585_p2;
wire   [8:0] trunc_ln44_99_fu_387_p4;
wire   [9:0] trunc_ln44_74_fu_397_p4;
wire   [0:0] icmp_ln51_74_fu_599_p2;
wire   [8:0] trunc_ln4_fu_407_p4;
wire   [9:0] zext_ln51_70_fu_666_p1;
wire   [9:0] zext_ln51_69_fu_663_p1;
wire   [9:0] zext_ln51_68_fu_660_p1;
wire   [9:0] zext_ln51_67_fu_657_p1;
wire   [9:0] zext_ln51_66_fu_654_p1;
wire   [9:0] zext_ln51_65_fu_651_p1;
wire   [9:0] zext_ln51_64_fu_648_p1;
wire   [9:0] zext_ln51_63_fu_645_p1;
wire   [9:0] zext_ln51_62_fu_642_p1;
wire   [9:0] zext_ln51_61_fu_639_p1;
wire   [9:0] zext_ln51_60_fu_636_p1;
wire   [9:0] zext_ln51_59_fu_633_p1;
wire   [9:0] zext_ln51_fu_630_p1;
wire   [138:0] or_ln57_s_fu_669_p15;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_141;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_124 = 8'd0;
end

cifar10_axis_wrapper_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_141)) begin
        i_fu_124 <= i_9_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln51_62_reg_717 <= select_ln51_62_fu_437_p3;
        select_ln51_63_reg_722 <= select_ln51_63_fu_451_p3;
        select_ln51_64_reg_727 <= select_ln51_64_fu_465_p3;
        select_ln51_65_reg_732 <= select_ln51_65_fu_479_p3;
        select_ln51_66_reg_737 <= select_ln51_66_fu_493_p3;
        select_ln51_67_reg_742 <= select_ln51_67_fu_507_p3;
        select_ln51_68_reg_747 <= select_ln51_68_fu_521_p3;
        select_ln51_69_reg_752 <= select_ln51_69_fu_535_p3;
        select_ln51_70_reg_757 <= select_ln51_70_fu_549_p3;
        select_ln51_71_reg_762 <= select_ln51_71_fu_563_p3;
        select_ln51_72_reg_767 <= select_ln51_72_fu_577_p3;
        select_ln51_73_reg_772 <= select_ln51_73_fu_591_p3;
        select_ln51_74_reg_777 <= select_ln51_74_fu_605_p3;
        select_ln51_reg_712 <= select_ln51_fu_423_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_619_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_8 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_8 = i_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer5_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_141 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_9_fu_613_p2 = (ap_sig_allocacmp_i_8 + 8'd1);

assign icmp_ln41_fu_619_p2 = ((ap_sig_allocacmp_i_8 == 8'd168) ? 1'b1 : 1'b0);

assign icmp_ln51_62_fu_431_p2 = (($signed(trunc_ln44_62_fu_157_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_63_fu_445_p2 = (($signed(trunc_ln44_63_fu_177_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_64_fu_459_p2 = (($signed(trunc_ln44_64_fu_197_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_65_fu_473_p2 = (($signed(trunc_ln44_65_fu_217_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_66_fu_487_p2 = (($signed(trunc_ln44_66_fu_237_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_67_fu_501_p2 = (($signed(trunc_ln44_67_fu_257_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_68_fu_515_p2 = (($signed(trunc_ln44_68_fu_277_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_69_fu_529_p2 = (($signed(trunc_ln44_69_fu_297_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_70_fu_543_p2 = (($signed(trunc_ln44_70_fu_317_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_71_fu_557_p2 = (($signed(trunc_ln44_71_fu_337_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_72_fu_571_p2 = (($signed(trunc_ln44_72_fu_357_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_73_fu_585_p2 = (($signed(trunc_ln44_73_fu_377_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_74_fu_599_p2 = (($signed(trunc_ln44_74_fu_397_p4) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_417_p2 = (($signed(trunc_ln44_fu_149_p1) > $signed(10'd0)) ? 1'b1 : 1'b0);

assign layer6_out_din = or_ln57_s_fu_669_p15;

assign or_ln57_s_fu_669_p15 = {{{{{{{{{{{{{{select_ln51_74_reg_777}, {zext_ln51_70_fu_666_p1}}, {zext_ln51_69_fu_663_p1}}, {zext_ln51_68_fu_660_p1}}, {zext_ln51_67_fu_657_p1}}, {zext_ln51_66_fu_654_p1}}, {zext_ln51_65_fu_651_p1}}, {zext_ln51_64_fu_648_p1}}, {zext_ln51_63_fu_645_p1}}, {zext_ln51_62_fu_642_p1}}, {zext_ln51_61_fu_639_p1}}, {zext_ln51_60_fu_636_p1}}, {zext_ln51_59_fu_633_p1}}, {zext_ln51_fu_630_p1}};

assign select_ln51_62_fu_437_p3 = ((icmp_ln51_62_fu_431_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_167_p4 : 9'd0);

assign select_ln51_63_fu_451_p3 = ((icmp_ln51_63_fu_445_p2[0:0] == 1'b1) ? trunc_ln44_89_fu_187_p4 : 9'd0);

assign select_ln51_64_fu_465_p3 = ((icmp_ln51_64_fu_459_p2[0:0] == 1'b1) ? trunc_ln44_90_fu_207_p4 : 9'd0);

assign select_ln51_65_fu_479_p3 = ((icmp_ln51_65_fu_473_p2[0:0] == 1'b1) ? trunc_ln44_91_fu_227_p4 : 9'd0);

assign select_ln51_66_fu_493_p3 = ((icmp_ln51_66_fu_487_p2[0:0] == 1'b1) ? trunc_ln44_92_fu_247_p4 : 9'd0);

assign select_ln51_67_fu_507_p3 = ((icmp_ln51_67_fu_501_p2[0:0] == 1'b1) ? trunc_ln44_93_fu_267_p4 : 9'd0);

assign select_ln51_68_fu_521_p3 = ((icmp_ln51_68_fu_515_p2[0:0] == 1'b1) ? trunc_ln44_94_fu_287_p4 : 9'd0);

assign select_ln51_69_fu_535_p3 = ((icmp_ln51_69_fu_529_p2[0:0] == 1'b1) ? trunc_ln44_95_fu_307_p4 : 9'd0);

assign select_ln51_70_fu_549_p3 = ((icmp_ln51_70_fu_543_p2[0:0] == 1'b1) ? trunc_ln44_96_fu_327_p4 : 9'd0);

assign select_ln51_71_fu_563_p3 = ((icmp_ln51_71_fu_557_p2[0:0] == 1'b1) ? trunc_ln44_97_fu_347_p4 : 9'd0);

assign select_ln51_72_fu_577_p3 = ((icmp_ln51_72_fu_571_p2[0:0] == 1'b1) ? trunc_ln44_98_fu_367_p4 : 9'd0);

assign select_ln51_73_fu_591_p3 = ((icmp_ln51_73_fu_585_p2[0:0] == 1'b1) ? trunc_ln44_99_fu_387_p4 : 9'd0);

assign select_ln51_74_fu_605_p3 = ((icmp_ln51_74_fu_599_p2[0:0] == 1'b1) ? trunc_ln4_fu_407_p4 : 9'd0);

assign select_ln51_fu_423_p3 = ((icmp_ln51_fu_417_p2[0:0] == 1'b1) ? trunc_ln44_103_fu_153_p1 : 9'd0);

assign start_out = real_start;

assign trunc_ln44_103_fu_153_p1 = layer5_out_dout[8:0];

assign trunc_ln44_62_fu_157_p4 = {{layer5_out_dout[19:10]}};

assign trunc_ln44_63_fu_177_p4 = {{layer5_out_dout[29:20]}};

assign trunc_ln44_64_fu_197_p4 = {{layer5_out_dout[39:30]}};

assign trunc_ln44_65_fu_217_p4 = {{layer5_out_dout[49:40]}};

assign trunc_ln44_66_fu_237_p4 = {{layer5_out_dout[59:50]}};

assign trunc_ln44_67_fu_257_p4 = {{layer5_out_dout[69:60]}};

assign trunc_ln44_68_fu_277_p4 = {{layer5_out_dout[79:70]}};

assign trunc_ln44_69_fu_297_p4 = {{layer5_out_dout[89:80]}};

assign trunc_ln44_70_fu_317_p4 = {{layer5_out_dout[99:90]}};

assign trunc_ln44_71_fu_337_p4 = {{layer5_out_dout[109:100]}};

assign trunc_ln44_72_fu_357_p4 = {{layer5_out_dout[119:110]}};

assign trunc_ln44_73_fu_377_p4 = {{layer5_out_dout[129:120]}};

assign trunc_ln44_74_fu_397_p4 = {{layer5_out_dout[139:130]}};

assign trunc_ln44_89_fu_187_p4 = {{layer5_out_dout[28:20]}};

assign trunc_ln44_90_fu_207_p4 = {{layer5_out_dout[38:30]}};

assign trunc_ln44_91_fu_227_p4 = {{layer5_out_dout[48:40]}};

assign trunc_ln44_92_fu_247_p4 = {{layer5_out_dout[58:50]}};

assign trunc_ln44_93_fu_267_p4 = {{layer5_out_dout[68:60]}};

assign trunc_ln44_94_fu_287_p4 = {{layer5_out_dout[78:70]}};

assign trunc_ln44_95_fu_307_p4 = {{layer5_out_dout[88:80]}};

assign trunc_ln44_96_fu_327_p4 = {{layer5_out_dout[98:90]}};

assign trunc_ln44_97_fu_347_p4 = {{layer5_out_dout[108:100]}};

assign trunc_ln44_98_fu_367_p4 = {{layer5_out_dout[118:110]}};

assign trunc_ln44_99_fu_387_p4 = {{layer5_out_dout[128:120]}};

assign trunc_ln44_fu_149_p1 = layer5_out_dout[9:0];

assign trunc_ln44_s_fu_167_p4 = {{layer5_out_dout[18:10]}};

assign trunc_ln4_fu_407_p4 = {{layer5_out_dout[138:130]}};

assign zext_ln51_59_fu_633_p1 = select_ln51_62_reg_717;

assign zext_ln51_60_fu_636_p1 = select_ln51_63_reg_722;

assign zext_ln51_61_fu_639_p1 = select_ln51_64_reg_727;

assign zext_ln51_62_fu_642_p1 = select_ln51_65_reg_732;

assign zext_ln51_63_fu_645_p1 = select_ln51_66_reg_737;

assign zext_ln51_64_fu_648_p1 = select_ln51_67_reg_742;

assign zext_ln51_65_fu_651_p1 = select_ln51_68_reg_747;

assign zext_ln51_66_fu_654_p1 = select_ln51_69_reg_752;

assign zext_ln51_67_fu_657_p1 = select_ln51_70_reg_757;

assign zext_ln51_68_fu_660_p1 = select_ln51_71_reg_762;

assign zext_ln51_69_fu_663_p1 = select_ln51_72_reg_767;

assign zext_ln51_70_fu_666_p1 = select_ln51_73_reg_772;

assign zext_ln51_fu_630_p1 = select_ln51_reg_712;

endmodule //cifar10_axis_wrapper_relu_array_ap_fixed_14u_array_ap_fixed_10_4_0_3_0_14u_relu_config6_s
