// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_axis_wrapper_relu_array_ap_fixed_32u_array_ap_fixed_11_5_0_3_0_32u_relu_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_din,
        layer9_out_full_n,
        layer9_out_write,
        layer9_out_num_data_valid,
        layer9_out_fifo_cap,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [351:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [4:0] layer8_out_num_data_valid;
input  [4:0] layer8_out_fifo_cap;
output  [351:0] layer9_out_din;
input   layer9_out_full_n;
output   layer9_out_write;
input  [31:0] layer9_out_num_data_valid;
input  [31:0] layer9_out_fifo_cap;
output   start_out;
output   start_write;

reg ap_idle;
reg layer8_out_read;
reg layer9_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_1339_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer8_out_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    layer9_out_blk_n;
wire   [9:0] select_ln51_fu_891_p3;
reg   [9:0] select_ln51_reg_1522;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [9:0] select_ln51_8_fu_905_p3;
reg   [9:0] select_ln51_8_reg_1527;
wire   [9:0] select_ln51_9_fu_919_p3;
reg   [9:0] select_ln51_9_reg_1532;
wire   [9:0] select_ln51_10_fu_933_p3;
reg   [9:0] select_ln51_10_reg_1537;
wire   [9:0] select_ln51_11_fu_947_p3;
reg   [9:0] select_ln51_11_reg_1542;
wire   [9:0] select_ln51_12_fu_961_p3;
reg   [9:0] select_ln51_12_reg_1547;
wire   [9:0] select_ln51_13_fu_975_p3;
reg   [9:0] select_ln51_13_reg_1552;
wire   [9:0] select_ln51_14_fu_989_p3;
reg   [9:0] select_ln51_14_reg_1557;
wire   [9:0] select_ln51_15_fu_1003_p3;
reg   [9:0] select_ln51_15_reg_1562;
wire   [9:0] select_ln51_16_fu_1017_p3;
reg   [9:0] select_ln51_16_reg_1567;
wire   [9:0] select_ln51_17_fu_1031_p3;
reg   [9:0] select_ln51_17_reg_1572;
wire   [9:0] select_ln51_18_fu_1045_p3;
reg   [9:0] select_ln51_18_reg_1577;
wire   [9:0] select_ln51_19_fu_1059_p3;
reg   [9:0] select_ln51_19_reg_1582;
wire   [9:0] select_ln51_20_fu_1073_p3;
reg   [9:0] select_ln51_20_reg_1587;
wire   [9:0] select_ln51_21_fu_1087_p3;
reg   [9:0] select_ln51_21_reg_1592;
wire   [9:0] select_ln51_22_fu_1101_p3;
reg   [9:0] select_ln51_22_reg_1597;
wire   [9:0] select_ln51_23_fu_1115_p3;
reg   [9:0] select_ln51_23_reg_1602;
wire   [9:0] select_ln51_24_fu_1129_p3;
reg   [9:0] select_ln51_24_reg_1607;
wire   [9:0] select_ln51_25_fu_1143_p3;
reg   [9:0] select_ln51_25_reg_1612;
wire   [9:0] select_ln51_26_fu_1157_p3;
reg   [9:0] select_ln51_26_reg_1617;
wire   [9:0] select_ln51_27_fu_1171_p3;
reg   [9:0] select_ln51_27_reg_1622;
wire   [9:0] select_ln51_28_fu_1185_p3;
reg   [9:0] select_ln51_28_reg_1627;
wire   [9:0] select_ln51_29_fu_1199_p3;
reg   [9:0] select_ln51_29_reg_1632;
wire   [9:0] select_ln51_30_fu_1213_p3;
reg   [9:0] select_ln51_30_reg_1637;
wire   [9:0] select_ln51_31_fu_1227_p3;
reg   [9:0] select_ln51_31_reg_1642;
wire   [9:0] select_ln51_32_fu_1241_p3;
reg   [9:0] select_ln51_32_reg_1647;
wire   [9:0] select_ln51_33_fu_1255_p3;
reg   [9:0] select_ln51_33_reg_1652;
wire   [9:0] select_ln51_34_fu_1269_p3;
reg   [9:0] select_ln51_34_reg_1657;
wire   [9:0] select_ln51_35_fu_1283_p3;
reg   [9:0] select_ln51_35_reg_1662;
wire   [9:0] select_ln51_36_fu_1297_p3;
reg   [9:0] select_ln51_36_reg_1667;
wire   [9:0] select_ln51_37_fu_1311_p3;
reg   [9:0] select_ln51_37_reg_1672;
wire   [9:0] select_ln51_38_fu_1325_p3;
reg   [9:0] select_ln51_38_reg_1677;
reg    ap_block_pp0_stage0_11001;
reg   [3:0] i_fu_232;
wire   [3:0] i_5_fu_1333_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_4;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [10:0] trunc_ln44_fu_257_p1;
wire   [0:0] icmp_ln51_fu_885_p2;
wire   [9:0] trunc_ln44_69_fu_261_p1;
wire   [10:0] trunc_ln44_8_fu_265_p4;
wire   [0:0] icmp_ln51_8_fu_899_p2;
wire   [9:0] trunc_ln44_s_fu_275_p4;
wire   [10:0] trunc_ln44_9_fu_285_p4;
wire   [0:0] icmp_ln51_9_fu_913_p2;
wire   [9:0] trunc_ln44_39_fu_295_p4;
wire   [10:0] trunc_ln44_10_fu_305_p4;
wire   [0:0] icmp_ln51_10_fu_927_p2;
wire   [9:0] trunc_ln44_40_fu_315_p4;
wire   [10:0] trunc_ln44_11_fu_325_p4;
wire   [0:0] icmp_ln51_11_fu_941_p2;
wire   [9:0] trunc_ln44_41_fu_335_p4;
wire   [10:0] trunc_ln44_12_fu_345_p4;
wire   [0:0] icmp_ln51_12_fu_955_p2;
wire   [9:0] trunc_ln44_42_fu_355_p4;
wire   [10:0] trunc_ln44_13_fu_365_p4;
wire   [0:0] icmp_ln51_13_fu_969_p2;
wire   [9:0] trunc_ln44_43_fu_375_p4;
wire   [10:0] trunc_ln44_14_fu_385_p4;
wire   [0:0] icmp_ln51_14_fu_983_p2;
wire   [9:0] trunc_ln44_44_fu_395_p4;
wire   [10:0] trunc_ln44_15_fu_405_p4;
wire   [0:0] icmp_ln51_15_fu_997_p2;
wire   [9:0] trunc_ln44_45_fu_415_p4;
wire   [10:0] trunc_ln44_16_fu_425_p4;
wire   [0:0] icmp_ln51_16_fu_1011_p2;
wire   [9:0] trunc_ln44_46_fu_435_p4;
wire   [10:0] trunc_ln44_17_fu_445_p4;
wire   [0:0] icmp_ln51_17_fu_1025_p2;
wire   [9:0] trunc_ln44_47_fu_455_p4;
wire   [10:0] trunc_ln44_18_fu_465_p4;
wire   [0:0] icmp_ln51_18_fu_1039_p2;
wire   [9:0] trunc_ln44_48_fu_475_p4;
wire   [10:0] trunc_ln44_19_fu_485_p4;
wire   [0:0] icmp_ln51_19_fu_1053_p2;
wire   [9:0] trunc_ln44_49_fu_495_p4;
wire   [10:0] trunc_ln44_20_fu_505_p4;
wire   [0:0] icmp_ln51_20_fu_1067_p2;
wire   [9:0] trunc_ln44_50_fu_515_p4;
wire   [10:0] trunc_ln44_21_fu_525_p4;
wire   [0:0] icmp_ln51_21_fu_1081_p2;
wire   [9:0] trunc_ln44_51_fu_535_p4;
wire   [10:0] trunc_ln44_22_fu_545_p4;
wire   [0:0] icmp_ln51_22_fu_1095_p2;
wire   [9:0] trunc_ln44_52_fu_555_p4;
wire   [10:0] trunc_ln44_23_fu_565_p4;
wire   [0:0] icmp_ln51_23_fu_1109_p2;
wire   [9:0] trunc_ln44_53_fu_575_p4;
wire   [10:0] trunc_ln44_24_fu_585_p4;
wire   [0:0] icmp_ln51_24_fu_1123_p2;
wire   [9:0] trunc_ln44_54_fu_595_p4;
wire   [10:0] trunc_ln44_25_fu_605_p4;
wire   [0:0] icmp_ln51_25_fu_1137_p2;
wire   [9:0] trunc_ln44_55_fu_615_p4;
wire   [10:0] trunc_ln44_26_fu_625_p4;
wire   [0:0] icmp_ln51_26_fu_1151_p2;
wire   [9:0] trunc_ln44_56_fu_635_p4;
wire   [10:0] trunc_ln44_27_fu_645_p4;
wire   [0:0] icmp_ln51_27_fu_1165_p2;
wire   [9:0] trunc_ln44_57_fu_655_p4;
wire   [10:0] trunc_ln44_28_fu_665_p4;
wire   [0:0] icmp_ln51_28_fu_1179_p2;
wire   [9:0] trunc_ln44_58_fu_675_p4;
wire   [10:0] trunc_ln44_29_fu_685_p4;
wire   [0:0] icmp_ln51_29_fu_1193_p2;
wire   [9:0] trunc_ln44_59_fu_695_p4;
wire   [10:0] trunc_ln44_30_fu_705_p4;
wire   [0:0] icmp_ln51_30_fu_1207_p2;
wire   [9:0] trunc_ln44_60_fu_715_p4;
wire   [10:0] trunc_ln44_31_fu_725_p4;
wire   [0:0] icmp_ln51_31_fu_1221_p2;
wire   [9:0] trunc_ln44_61_fu_735_p4;
wire   [10:0] trunc_ln44_32_fu_745_p4;
wire   [0:0] icmp_ln51_32_fu_1235_p2;
wire   [9:0] trunc_ln44_62_fu_755_p4;
wire   [10:0] trunc_ln44_33_fu_765_p4;
wire   [0:0] icmp_ln51_33_fu_1249_p2;
wire   [9:0] trunc_ln44_63_fu_775_p4;
wire   [10:0] trunc_ln44_34_fu_785_p4;
wire   [0:0] icmp_ln51_34_fu_1263_p2;
wire   [9:0] trunc_ln44_64_fu_795_p4;
wire   [10:0] trunc_ln44_35_fu_805_p4;
wire   [0:0] icmp_ln51_35_fu_1277_p2;
wire   [9:0] trunc_ln44_65_fu_815_p4;
wire   [10:0] trunc_ln44_36_fu_825_p4;
wire   [0:0] icmp_ln51_36_fu_1291_p2;
wire   [9:0] trunc_ln44_66_fu_835_p4;
wire   [10:0] trunc_ln44_37_fu_845_p4;
wire   [0:0] icmp_ln51_37_fu_1305_p2;
wire   [9:0] trunc_ln44_67_fu_855_p4;
wire   [10:0] trunc_ln44_38_fu_865_p4;
wire   [0:0] icmp_ln51_38_fu_1319_p2;
wire   [9:0] trunc_ln2_fu_875_p4;
wire   [10:0] zext_ln51_36_fu_1440_p1;
wire   [10:0] zext_ln51_35_fu_1437_p1;
wire   [10:0] zext_ln51_34_fu_1434_p1;
wire   [10:0] zext_ln51_33_fu_1431_p1;
wire   [10:0] zext_ln51_32_fu_1428_p1;
wire   [10:0] zext_ln51_31_fu_1425_p1;
wire   [10:0] zext_ln51_30_fu_1422_p1;
wire   [10:0] zext_ln51_29_fu_1419_p1;
wire   [10:0] zext_ln51_28_fu_1416_p1;
wire   [10:0] zext_ln51_27_fu_1413_p1;
wire   [10:0] zext_ln51_26_fu_1410_p1;
wire   [10:0] zext_ln51_25_fu_1407_p1;
wire   [10:0] zext_ln51_24_fu_1404_p1;
wire   [10:0] zext_ln51_23_fu_1401_p1;
wire   [10:0] zext_ln51_22_fu_1398_p1;
wire   [10:0] zext_ln51_21_fu_1395_p1;
wire   [10:0] zext_ln51_20_fu_1392_p1;
wire   [10:0] zext_ln51_19_fu_1389_p1;
wire   [10:0] zext_ln51_18_fu_1386_p1;
wire   [10:0] zext_ln51_17_fu_1383_p1;
wire   [10:0] zext_ln51_16_fu_1380_p1;
wire   [10:0] zext_ln51_15_fu_1377_p1;
wire   [10:0] zext_ln51_14_fu_1374_p1;
wire   [10:0] zext_ln51_13_fu_1371_p1;
wire   [10:0] zext_ln51_12_fu_1368_p1;
wire   [10:0] zext_ln51_11_fu_1365_p1;
wire   [10:0] zext_ln51_10_fu_1362_p1;
wire   [10:0] zext_ln51_9_fu_1359_p1;
wire   [10:0] zext_ln51_8_fu_1356_p1;
wire   [10:0] zext_ln51_7_fu_1353_p1;
wire   [10:0] zext_ln51_fu_1350_p1;
wire   [350:0] or_ln57_s_fu_1443_p33;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_done_sig;
reg    ap_condition_177;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 i_fu_232 = 4'd0;
end

cifar10_axis_wrapper_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_177)) begin
        i_fu_232 <= i_5_fu_1333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln51_10_reg_1537 <= select_ln51_10_fu_933_p3;
        select_ln51_11_reg_1542 <= select_ln51_11_fu_947_p3;
        select_ln51_12_reg_1547 <= select_ln51_12_fu_961_p3;
        select_ln51_13_reg_1552 <= select_ln51_13_fu_975_p3;
        select_ln51_14_reg_1557 <= select_ln51_14_fu_989_p3;
        select_ln51_15_reg_1562 <= select_ln51_15_fu_1003_p3;
        select_ln51_16_reg_1567 <= select_ln51_16_fu_1017_p3;
        select_ln51_17_reg_1572 <= select_ln51_17_fu_1031_p3;
        select_ln51_18_reg_1577 <= select_ln51_18_fu_1045_p3;
        select_ln51_19_reg_1582 <= select_ln51_19_fu_1059_p3;
        select_ln51_20_reg_1587 <= select_ln51_20_fu_1073_p3;
        select_ln51_21_reg_1592 <= select_ln51_21_fu_1087_p3;
        select_ln51_22_reg_1597 <= select_ln51_22_fu_1101_p3;
        select_ln51_23_reg_1602 <= select_ln51_23_fu_1115_p3;
        select_ln51_24_reg_1607 <= select_ln51_24_fu_1129_p3;
        select_ln51_25_reg_1612 <= select_ln51_25_fu_1143_p3;
        select_ln51_26_reg_1617 <= select_ln51_26_fu_1157_p3;
        select_ln51_27_reg_1622 <= select_ln51_27_fu_1171_p3;
        select_ln51_28_reg_1627 <= select_ln51_28_fu_1185_p3;
        select_ln51_29_reg_1632 <= select_ln51_29_fu_1199_p3;
        select_ln51_30_reg_1637 <= select_ln51_30_fu_1213_p3;
        select_ln51_31_reg_1642 <= select_ln51_31_fu_1227_p3;
        select_ln51_32_reg_1647 <= select_ln51_32_fu_1241_p3;
        select_ln51_33_reg_1652 <= select_ln51_33_fu_1255_p3;
        select_ln51_34_reg_1657 <= select_ln51_34_fu_1269_p3;
        select_ln51_35_reg_1662 <= select_ln51_35_fu_1283_p3;
        select_ln51_36_reg_1667 <= select_ln51_36_fu_1297_p3;
        select_ln51_37_reg_1672 <= select_ln51_37_fu_1311_p3;
        select_ln51_38_reg_1677 <= select_ln51_38_fu_1325_p3;
        select_ln51_8_reg_1527 <= select_ln51_8_fu_905_p3;
        select_ln51_9_reg_1532 <= select_ln51_9_fu_919_p3;
        select_ln51_reg_1522 <= select_ln51_fu_891_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_1339_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_232;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_done_reg == 1'b0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer9_out_blk_n = layer9_out_full_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer9_out_write = 1'b1;
    end else begin
        layer9_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_done_reg == 1'b1) | ((layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_done_reg == 1'b1) | ((layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer9_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start_int == 1'b1) & ((ap_done_reg == 1'b1) | (1'b1 == ap_block_state1_pp0_stage0_iter0_grp1))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_grp1 = ((ap_done_reg == 1'b1) | (layer8_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_condition_177 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_5_fu_1333_p2 = (ap_sig_allocacmp_i_4 + 4'd1);

assign icmp_ln41_fu_1339_p2 = ((ap_sig_allocacmp_i_4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln51_10_fu_927_p2 = (($signed(trunc_ln44_10_fu_305_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_941_p2 = (($signed(trunc_ln44_11_fu_325_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_955_p2 = (($signed(trunc_ln44_12_fu_345_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_969_p2 = (($signed(trunc_ln44_13_fu_365_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_983_p2 = (($signed(trunc_ln44_14_fu_385_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_997_p2 = (($signed(trunc_ln44_15_fu_405_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_1011_p2 = (($signed(trunc_ln44_16_fu_425_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_1025_p2 = (($signed(trunc_ln44_17_fu_445_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_1039_p2 = (($signed(trunc_ln44_18_fu_465_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_1053_p2 = (($signed(trunc_ln44_19_fu_485_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_1067_p2 = (($signed(trunc_ln44_20_fu_505_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_1081_p2 = (($signed(trunc_ln44_21_fu_525_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_1095_p2 = (($signed(trunc_ln44_22_fu_545_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_1109_p2 = (($signed(trunc_ln44_23_fu_565_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1123_p2 = (($signed(trunc_ln44_24_fu_585_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1137_p2 = (($signed(trunc_ln44_25_fu_605_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1151_p2 = (($signed(trunc_ln44_26_fu_625_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_1165_p2 = (($signed(trunc_ln44_27_fu_645_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_1179_p2 = (($signed(trunc_ln44_28_fu_665_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_1193_p2 = (($signed(trunc_ln44_29_fu_685_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_1207_p2 = (($signed(trunc_ln44_30_fu_705_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_1221_p2 = (($signed(trunc_ln44_31_fu_725_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_1235_p2 = (($signed(trunc_ln44_32_fu_745_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_1249_p2 = (($signed(trunc_ln44_33_fu_765_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1263_p2 = (($signed(trunc_ln44_34_fu_785_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_1277_p2 = (($signed(trunc_ln44_35_fu_805_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_1291_p2 = (($signed(trunc_ln44_36_fu_825_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_1305_p2 = (($signed(trunc_ln44_37_fu_845_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_1319_p2 = (($signed(trunc_ln44_38_fu_865_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_899_p2 = (($signed(trunc_ln44_8_fu_265_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_913_p2 = (($signed(trunc_ln44_9_fu_285_p4) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_885_p2 = (($signed(trunc_ln44_fu_257_p1) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign layer9_out_din = or_ln57_s_fu_1443_p33;

assign or_ln57_s_fu_1443_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_38_reg_1677}, {zext_ln51_36_fu_1440_p1}}, {zext_ln51_35_fu_1437_p1}}, {zext_ln51_34_fu_1434_p1}}, {zext_ln51_33_fu_1431_p1}}, {zext_ln51_32_fu_1428_p1}}, {zext_ln51_31_fu_1425_p1}}, {zext_ln51_30_fu_1422_p1}}, {zext_ln51_29_fu_1419_p1}}, {zext_ln51_28_fu_1416_p1}}, {zext_ln51_27_fu_1413_p1}}, {zext_ln51_26_fu_1410_p1}}, {zext_ln51_25_fu_1407_p1}}, {zext_ln51_24_fu_1404_p1}}, {zext_ln51_23_fu_1401_p1}}, {zext_ln51_22_fu_1398_p1}}, {zext_ln51_21_fu_1395_p1}}, {zext_ln51_20_fu_1392_p1}}, {zext_ln51_19_fu_1389_p1}}, {zext_ln51_18_fu_1386_p1}}, {zext_ln51_17_fu_1383_p1}}, {zext_ln51_16_fu_1380_p1}}, {zext_ln51_15_fu_1377_p1}}, {zext_ln51_14_fu_1374_p1}}, {zext_ln51_13_fu_1371_p1}}, {zext_ln51_12_fu_1368_p1}}, {zext_ln51_11_fu_1365_p1}}, {zext_ln51_10_fu_1362_p1}}, {zext_ln51_9_fu_1359_p1}}, {zext_ln51_8_fu_1356_p1}}, {zext_ln51_7_fu_1353_p1}}, {zext_ln51_fu_1350_p1}};

assign select_ln51_10_fu_933_p3 = ((icmp_ln51_10_fu_927_p2[0:0] == 1'b1) ? trunc_ln44_40_fu_315_p4 : 10'd0);

assign select_ln51_11_fu_947_p3 = ((icmp_ln51_11_fu_941_p2[0:0] == 1'b1) ? trunc_ln44_41_fu_335_p4 : 10'd0);

assign select_ln51_12_fu_961_p3 = ((icmp_ln51_12_fu_955_p2[0:0] == 1'b1) ? trunc_ln44_42_fu_355_p4 : 10'd0);

assign select_ln51_13_fu_975_p3 = ((icmp_ln51_13_fu_969_p2[0:0] == 1'b1) ? trunc_ln44_43_fu_375_p4 : 10'd0);

assign select_ln51_14_fu_989_p3 = ((icmp_ln51_14_fu_983_p2[0:0] == 1'b1) ? trunc_ln44_44_fu_395_p4 : 10'd0);

assign select_ln51_15_fu_1003_p3 = ((icmp_ln51_15_fu_997_p2[0:0] == 1'b1) ? trunc_ln44_45_fu_415_p4 : 10'd0);

assign select_ln51_16_fu_1017_p3 = ((icmp_ln51_16_fu_1011_p2[0:0] == 1'b1) ? trunc_ln44_46_fu_435_p4 : 10'd0);

assign select_ln51_17_fu_1031_p3 = ((icmp_ln51_17_fu_1025_p2[0:0] == 1'b1) ? trunc_ln44_47_fu_455_p4 : 10'd0);

assign select_ln51_18_fu_1045_p3 = ((icmp_ln51_18_fu_1039_p2[0:0] == 1'b1) ? trunc_ln44_48_fu_475_p4 : 10'd0);

assign select_ln51_19_fu_1059_p3 = ((icmp_ln51_19_fu_1053_p2[0:0] == 1'b1) ? trunc_ln44_49_fu_495_p4 : 10'd0);

assign select_ln51_20_fu_1073_p3 = ((icmp_ln51_20_fu_1067_p2[0:0] == 1'b1) ? trunc_ln44_50_fu_515_p4 : 10'd0);

assign select_ln51_21_fu_1087_p3 = ((icmp_ln51_21_fu_1081_p2[0:0] == 1'b1) ? trunc_ln44_51_fu_535_p4 : 10'd0);

assign select_ln51_22_fu_1101_p3 = ((icmp_ln51_22_fu_1095_p2[0:0] == 1'b1) ? trunc_ln44_52_fu_555_p4 : 10'd0);

assign select_ln51_23_fu_1115_p3 = ((icmp_ln51_23_fu_1109_p2[0:0] == 1'b1) ? trunc_ln44_53_fu_575_p4 : 10'd0);

assign select_ln51_24_fu_1129_p3 = ((icmp_ln51_24_fu_1123_p2[0:0] == 1'b1) ? trunc_ln44_54_fu_595_p4 : 10'd0);

assign select_ln51_25_fu_1143_p3 = ((icmp_ln51_25_fu_1137_p2[0:0] == 1'b1) ? trunc_ln44_55_fu_615_p4 : 10'd0);

assign select_ln51_26_fu_1157_p3 = ((icmp_ln51_26_fu_1151_p2[0:0] == 1'b1) ? trunc_ln44_56_fu_635_p4 : 10'd0);

assign select_ln51_27_fu_1171_p3 = ((icmp_ln51_27_fu_1165_p2[0:0] == 1'b1) ? trunc_ln44_57_fu_655_p4 : 10'd0);

assign select_ln51_28_fu_1185_p3 = ((icmp_ln51_28_fu_1179_p2[0:0] == 1'b1) ? trunc_ln44_58_fu_675_p4 : 10'd0);

assign select_ln51_29_fu_1199_p3 = ((icmp_ln51_29_fu_1193_p2[0:0] == 1'b1) ? trunc_ln44_59_fu_695_p4 : 10'd0);

assign select_ln51_30_fu_1213_p3 = ((icmp_ln51_30_fu_1207_p2[0:0] == 1'b1) ? trunc_ln44_60_fu_715_p4 : 10'd0);

assign select_ln51_31_fu_1227_p3 = ((icmp_ln51_31_fu_1221_p2[0:0] == 1'b1) ? trunc_ln44_61_fu_735_p4 : 10'd0);

assign select_ln51_32_fu_1241_p3 = ((icmp_ln51_32_fu_1235_p2[0:0] == 1'b1) ? trunc_ln44_62_fu_755_p4 : 10'd0);

assign select_ln51_33_fu_1255_p3 = ((icmp_ln51_33_fu_1249_p2[0:0] == 1'b1) ? trunc_ln44_63_fu_775_p4 : 10'd0);

assign select_ln51_34_fu_1269_p3 = ((icmp_ln51_34_fu_1263_p2[0:0] == 1'b1) ? trunc_ln44_64_fu_795_p4 : 10'd0);

assign select_ln51_35_fu_1283_p3 = ((icmp_ln51_35_fu_1277_p2[0:0] == 1'b1) ? trunc_ln44_65_fu_815_p4 : 10'd0);

assign select_ln51_36_fu_1297_p3 = ((icmp_ln51_36_fu_1291_p2[0:0] == 1'b1) ? trunc_ln44_66_fu_835_p4 : 10'd0);

assign select_ln51_37_fu_1311_p3 = ((icmp_ln51_37_fu_1305_p2[0:0] == 1'b1) ? trunc_ln44_67_fu_855_p4 : 10'd0);

assign select_ln51_38_fu_1325_p3 = ((icmp_ln51_38_fu_1319_p2[0:0] == 1'b1) ? trunc_ln2_fu_875_p4 : 10'd0);

assign select_ln51_8_fu_905_p3 = ((icmp_ln51_8_fu_899_p2[0:0] == 1'b1) ? trunc_ln44_s_fu_275_p4 : 10'd0);

assign select_ln51_9_fu_919_p3 = ((icmp_ln51_9_fu_913_p2[0:0] == 1'b1) ? trunc_ln44_39_fu_295_p4 : 10'd0);

assign select_ln51_fu_891_p3 = ((icmp_ln51_fu_885_p2[0:0] == 1'b1) ? trunc_ln44_69_fu_261_p1 : 10'd0);

assign start_out = real_start;

assign trunc_ln2_fu_875_p4 = {{layer8_out_dout[350:341]}};

assign trunc_ln44_10_fu_305_p4 = {{layer8_out_dout[43:33]}};

assign trunc_ln44_11_fu_325_p4 = {{layer8_out_dout[54:44]}};

assign trunc_ln44_12_fu_345_p4 = {{layer8_out_dout[65:55]}};

assign trunc_ln44_13_fu_365_p4 = {{layer8_out_dout[76:66]}};

assign trunc_ln44_14_fu_385_p4 = {{layer8_out_dout[87:77]}};

assign trunc_ln44_15_fu_405_p4 = {{layer8_out_dout[98:88]}};

assign trunc_ln44_16_fu_425_p4 = {{layer8_out_dout[109:99]}};

assign trunc_ln44_17_fu_445_p4 = {{layer8_out_dout[120:110]}};

assign trunc_ln44_18_fu_465_p4 = {{layer8_out_dout[131:121]}};

assign trunc_ln44_19_fu_485_p4 = {{layer8_out_dout[142:132]}};

assign trunc_ln44_20_fu_505_p4 = {{layer8_out_dout[153:143]}};

assign trunc_ln44_21_fu_525_p4 = {{layer8_out_dout[164:154]}};

assign trunc_ln44_22_fu_545_p4 = {{layer8_out_dout[175:165]}};

assign trunc_ln44_23_fu_565_p4 = {{layer8_out_dout[186:176]}};

assign trunc_ln44_24_fu_585_p4 = {{layer8_out_dout[197:187]}};

assign trunc_ln44_25_fu_605_p4 = {{layer8_out_dout[208:198]}};

assign trunc_ln44_26_fu_625_p4 = {{layer8_out_dout[219:209]}};

assign trunc_ln44_27_fu_645_p4 = {{layer8_out_dout[230:220]}};

assign trunc_ln44_28_fu_665_p4 = {{layer8_out_dout[241:231]}};

assign trunc_ln44_29_fu_685_p4 = {{layer8_out_dout[252:242]}};

assign trunc_ln44_30_fu_705_p4 = {{layer8_out_dout[263:253]}};

assign trunc_ln44_31_fu_725_p4 = {{layer8_out_dout[274:264]}};

assign trunc_ln44_32_fu_745_p4 = {{layer8_out_dout[285:275]}};

assign trunc_ln44_33_fu_765_p4 = {{layer8_out_dout[296:286]}};

assign trunc_ln44_34_fu_785_p4 = {{layer8_out_dout[307:297]}};

assign trunc_ln44_35_fu_805_p4 = {{layer8_out_dout[318:308]}};

assign trunc_ln44_36_fu_825_p4 = {{layer8_out_dout[329:319]}};

assign trunc_ln44_37_fu_845_p4 = {{layer8_out_dout[340:330]}};

assign trunc_ln44_38_fu_865_p4 = {{layer8_out_dout[351:341]}};

assign trunc_ln44_39_fu_295_p4 = {{layer8_out_dout[31:22]}};

assign trunc_ln44_40_fu_315_p4 = {{layer8_out_dout[42:33]}};

assign trunc_ln44_41_fu_335_p4 = {{layer8_out_dout[53:44]}};

assign trunc_ln44_42_fu_355_p4 = {{layer8_out_dout[64:55]}};

assign trunc_ln44_43_fu_375_p4 = {{layer8_out_dout[75:66]}};

assign trunc_ln44_44_fu_395_p4 = {{layer8_out_dout[86:77]}};

assign trunc_ln44_45_fu_415_p4 = {{layer8_out_dout[97:88]}};

assign trunc_ln44_46_fu_435_p4 = {{layer8_out_dout[108:99]}};

assign trunc_ln44_47_fu_455_p4 = {{layer8_out_dout[119:110]}};

assign trunc_ln44_48_fu_475_p4 = {{layer8_out_dout[130:121]}};

assign trunc_ln44_49_fu_495_p4 = {{layer8_out_dout[141:132]}};

assign trunc_ln44_50_fu_515_p4 = {{layer8_out_dout[152:143]}};

assign trunc_ln44_51_fu_535_p4 = {{layer8_out_dout[163:154]}};

assign trunc_ln44_52_fu_555_p4 = {{layer8_out_dout[174:165]}};

assign trunc_ln44_53_fu_575_p4 = {{layer8_out_dout[185:176]}};

assign trunc_ln44_54_fu_595_p4 = {{layer8_out_dout[196:187]}};

assign trunc_ln44_55_fu_615_p4 = {{layer8_out_dout[207:198]}};

assign trunc_ln44_56_fu_635_p4 = {{layer8_out_dout[218:209]}};

assign trunc_ln44_57_fu_655_p4 = {{layer8_out_dout[229:220]}};

assign trunc_ln44_58_fu_675_p4 = {{layer8_out_dout[240:231]}};

assign trunc_ln44_59_fu_695_p4 = {{layer8_out_dout[251:242]}};

assign trunc_ln44_60_fu_715_p4 = {{layer8_out_dout[262:253]}};

assign trunc_ln44_61_fu_735_p4 = {{layer8_out_dout[273:264]}};

assign trunc_ln44_62_fu_755_p4 = {{layer8_out_dout[284:275]}};

assign trunc_ln44_63_fu_775_p4 = {{layer8_out_dout[295:286]}};

assign trunc_ln44_64_fu_795_p4 = {{layer8_out_dout[306:297]}};

assign trunc_ln44_65_fu_815_p4 = {{layer8_out_dout[317:308]}};

assign trunc_ln44_66_fu_835_p4 = {{layer8_out_dout[328:319]}};

assign trunc_ln44_67_fu_855_p4 = {{layer8_out_dout[339:330]}};

assign trunc_ln44_69_fu_261_p1 = layer8_out_dout[9:0];

assign trunc_ln44_8_fu_265_p4 = {{layer8_out_dout[21:11]}};

assign trunc_ln44_9_fu_285_p4 = {{layer8_out_dout[32:22]}};

assign trunc_ln44_fu_257_p1 = layer8_out_dout[10:0];

assign trunc_ln44_s_fu_275_p4 = {{layer8_out_dout[20:11]}};

assign zext_ln51_10_fu_1362_p1 = select_ln51_11_reg_1542;

assign zext_ln51_11_fu_1365_p1 = select_ln51_12_reg_1547;

assign zext_ln51_12_fu_1368_p1 = select_ln51_13_reg_1552;

assign zext_ln51_13_fu_1371_p1 = select_ln51_14_reg_1557;

assign zext_ln51_14_fu_1374_p1 = select_ln51_15_reg_1562;

assign zext_ln51_15_fu_1377_p1 = select_ln51_16_reg_1567;

assign zext_ln51_16_fu_1380_p1 = select_ln51_17_reg_1572;

assign zext_ln51_17_fu_1383_p1 = select_ln51_18_reg_1577;

assign zext_ln51_18_fu_1386_p1 = select_ln51_19_reg_1582;

assign zext_ln51_19_fu_1389_p1 = select_ln51_20_reg_1587;

assign zext_ln51_20_fu_1392_p1 = select_ln51_21_reg_1592;

assign zext_ln51_21_fu_1395_p1 = select_ln51_22_reg_1597;

assign zext_ln51_22_fu_1398_p1 = select_ln51_23_reg_1602;

assign zext_ln51_23_fu_1401_p1 = select_ln51_24_reg_1607;

assign zext_ln51_24_fu_1404_p1 = select_ln51_25_reg_1612;

assign zext_ln51_25_fu_1407_p1 = select_ln51_26_reg_1617;

assign zext_ln51_26_fu_1410_p1 = select_ln51_27_reg_1622;

assign zext_ln51_27_fu_1413_p1 = select_ln51_28_reg_1627;

assign zext_ln51_28_fu_1416_p1 = select_ln51_29_reg_1632;

assign zext_ln51_29_fu_1419_p1 = select_ln51_30_reg_1637;

assign zext_ln51_30_fu_1422_p1 = select_ln51_31_reg_1642;

assign zext_ln51_31_fu_1425_p1 = select_ln51_32_reg_1647;

assign zext_ln51_32_fu_1428_p1 = select_ln51_33_reg_1652;

assign zext_ln51_33_fu_1431_p1 = select_ln51_34_reg_1657;

assign zext_ln51_34_fu_1434_p1 = select_ln51_35_reg_1662;

assign zext_ln51_35_fu_1437_p1 = select_ln51_36_reg_1667;

assign zext_ln51_36_fu_1440_p1 = select_ln51_37_reg_1672;

assign zext_ln51_7_fu_1353_p1 = select_ln51_8_reg_1527;

assign zext_ln51_8_fu_1356_p1 = select_ln51_9_reg_1532;

assign zext_ln51_9_fu_1359_p1 = select_ln51_10_reg_1537;

assign zext_ln51_fu_1350_p1 = select_ln51_reg_1522;

endmodule //cifar10_axis_wrapper_relu_array_ap_fixed_32u_array_ap_fixed_11_5_0_3_0_32u_relu_config9_s
