// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module cifar10_axis_wrapper_pooling2d_cl_array_array_ap_fixed_10_4_0_3_0_14u_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer7_out_din,
        layer7_out_full_n,
        layer7_out_write,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [139:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
input  [8:0] layer6_out_num_data_valid;
input  [8:0] layer6_out_fifo_cap;
output  [139:0] layer7_out_din;
input   layer7_out_full_n;
output   layer7_out_write;
input  [6:0] layer7_out_num_data_valid;
input  [6:0] layer7_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer6_out_read;
reg layer7_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_12;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_8;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_7;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_6;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_5;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_4;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_3;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_2;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_1;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_s;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_11;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_10;
reg   [9:0] void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_14u_0_line_buffer;
reg   [9:0] p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_9;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_27;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_26;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_25;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_24;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_23;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_22;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_21;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_20;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_19;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_18;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_17;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_16;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_15;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_14;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_13;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_12;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_11;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_10;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_9;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_8;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_7;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_6;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_5;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_4;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_3;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_2;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_1;
reg   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap;
reg   [31:0] sX_1;
reg   [31:0] pX_1;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg    layer6_out_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    layer7_out_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln191_reg_3878;
reg   [0:0] icmp_ln191_reg_3878_pp0_iter1_reg;
reg   [0:0] and_ln191_2_reg_3969;
reg   [0:0] icmp_ln24376_reg_395;
reg   [9:0] p_0_0_0_0_013474_reg_406;
reg    ap_block_state1;
wire   [9:0] trunc_ln247_fu_813_p1;
reg   [9:0] trunc_ln247_reg_3752;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op539_write_state4;
reg    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [9:0] trunc_ln247_reg_3752_pp0_iter1_reg;
reg   [9:0] trunc_ln247_1_reg_3761;
reg   [9:0] trunc_ln247_2_reg_3770;
reg   [9:0] trunc_ln247_3_reg_3779;
reg   [9:0] trunc_ln247_4_reg_3788;
reg   [9:0] trunc_ln247_5_reg_3797;
reg   [9:0] trunc_ln247_6_reg_3806;
reg   [9:0] trunc_ln247_7_reg_3815;
reg   [9:0] trunc_ln247_8_reg_3824;
reg   [9:0] trunc_ln247_9_reg_3833;
reg   [9:0] trunc_ln247_s_reg_3842;
reg   [9:0] trunc_ln247_10_reg_3851;
reg   [9:0] trunc_ln247_11_reg_3860;
reg   [9:0] trunc_ln247_12_reg_3869;
wire   [0:0] icmp_ln191_fu_951_p2;
wire   [0:0] icmp_ln191_5_fu_971_p2;
reg   [0:0] icmp_ln191_5_reg_3882;
wire   [0:0] icmp_ln191_6_fu_977_p2;
reg   [0:0] icmp_ln191_6_reg_3887;
wire   [0:0] icmp_ln212_fu_989_p2;
reg   [0:0] icmp_ln212_reg_3892;
wire   [0:0] icmp_ln216_fu_1043_p2;
reg   [0:0] icmp_ln216_reg_3896;
wire   [0:0] icmp_ln241_fu_1061_p2;
reg   [0:0] icmp_ln241_reg_3900;
reg   [0:0] icmp_ln241_reg_3900_pp0_iter1_reg;
wire   [9:0] select_ln241_fu_1150_p3;
reg   [9:0] select_ln241_reg_3904;
reg    ap_enable_reg_pp0_iter1;
wire   [9:0] select_ln241_7_fu_1158_p3;
reg   [9:0] select_ln241_7_reg_3909;
wire   [9:0] select_ln241_8_fu_1166_p3;
reg   [9:0] select_ln241_8_reg_3914;
wire   [9:0] select_ln241_9_fu_1174_p3;
reg   [9:0] select_ln241_9_reg_3919;
wire   [9:0] select_ln241_10_fu_1182_p3;
reg   [9:0] select_ln241_10_reg_3924;
wire   [9:0] select_ln241_11_fu_1190_p3;
reg   [9:0] select_ln241_11_reg_3929;
wire   [9:0] select_ln241_12_fu_1198_p3;
reg   [9:0] select_ln241_12_reg_3934;
wire   [9:0] select_ln241_13_fu_1206_p3;
reg   [9:0] select_ln241_13_reg_3939;
wire   [9:0] select_ln241_14_fu_1214_p3;
reg   [9:0] select_ln241_14_reg_3944;
wire   [9:0] select_ln241_15_fu_1222_p3;
reg   [9:0] select_ln241_15_reg_3949;
wire   [9:0] select_ln241_16_fu_1230_p3;
reg   [9:0] select_ln241_16_reg_3954;
wire   [9:0] select_ln241_17_fu_1238_p3;
reg   [9:0] select_ln241_17_reg_3959;
wire   [9:0] select_ln241_18_fu_1246_p3;
reg   [9:0] select_ln241_18_reg_3964;
wire   [0:0] and_ln191_2_fu_1268_p2;
reg   [9:0] trunc_ln_reg_3973;
reg   [0:0] tmp_reg_3978;
reg   [9:0] trunc_ln204_8_reg_3983;
reg   [0:0] tmp_8_reg_3988;
reg   [9:0] trunc_ln204_9_reg_3993;
reg   [0:0] tmp_9_reg_3998;
reg   [9:0] trunc_ln204_s_reg_4003;
reg   [0:0] tmp_10_reg_4008;
reg   [9:0] trunc_ln204_1_reg_4013;
reg   [0:0] tmp_11_reg_4018;
reg   [9:0] trunc_ln204_2_reg_4023;
reg   [0:0] tmp_12_reg_4028;
reg   [9:0] trunc_ln204_3_reg_4033;
reg   [0:0] tmp_13_reg_4038;
reg   [9:0] trunc_ln204_4_reg_4043;
reg   [0:0] tmp_14_reg_4048;
reg   [9:0] trunc_ln204_5_reg_4053;
reg   [0:0] tmp_15_reg_4058;
reg   [9:0] trunc_ln204_6_reg_4063;
reg   [0:0] tmp_16_reg_4068;
reg   [9:0] trunc_ln204_7_reg_4073;
reg   [0:0] tmp_17_reg_4078;
reg   [9:0] trunc_ln204_10_reg_4083;
reg   [0:0] tmp_18_reg_4088;
reg   [9:0] trunc_ln204_11_reg_4093;
reg   [0:0] tmp_19_reg_4098;
reg   [9:0] trunc_ln204_12_reg_4103;
reg   [0:0] tmp_20_reg_4108;
wire   [0:0] icmp_ln243_fu_2901_p2;
reg   [0:0] icmp_ln243_reg_4113;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_flush_enable;
reg   [0:0] ap_phi_mux_icmp_ln24376_phi_fu_399_p4;
reg   [9:0] ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_420_p4;
wire   [31:0] select_ln222_fu_2869_p3;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_i_i_reg_416;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_i_reg_416;
wire    ap_CS_fsm_state5;
wire   [31:0] select_ln227_fu_1007_p3;
wire   [31:0] add_ln212_fu_983_p2;
wire   [31:0] add_ln216_fu_1037_p2;
reg   [7:0] indvar_flatten3_fu_210;
wire   [7:0] add_ln241_fu_961_p2;
reg   [9:0] p_0_13_0_0_02566_fu_214;
reg   [9:0] p_0_12_0_0_02528_fu_218;
reg   [9:0] p_0_11_0_0_024810_fu_222;
reg   [9:0] p_0_10_0_0_024412_fu_226;
reg   [9:0] p_0_9_0_0_024014_fu_230;
reg   [9:0] p_0_8_0_0_023616_fu_234;
reg   [9:0] p_0_7_0_0_023218_fu_238;
reg   [9:0] p_0_6_0_0_022820_fu_242;
reg   [9:0] p_0_5_0_0_022422_fu_246;
reg   [9:0] p_0_4_0_0_022024_fu_250;
reg   [9:0] p_0_3_0_0_021626_fu_254;
reg   [9:0] p_0_2_0_0_021228_fu_258;
reg   [9:0] p_0_1_0_0_020830_fu_262;
reg   [9:0] p_0_0_0_0_020432_fu_266;
reg   [9:0] p_0_13_0_0_016020133_fu_270;
reg   [9:0] p_0_12_0_0_015819835_fu_274;
reg   [9:0] p_0_11_0_0_015619537_fu_278;
reg   [9:0] p_0_10_0_0_015419239_fu_282;
reg   [9:0] p_0_9_0_0_015218941_fu_286;
reg   [9:0] p_0_8_0_0_015018643_fu_290;
reg   [9:0] p_0_7_0_0_014818345_fu_294;
reg   [9:0] p_0_6_0_0_014618047_fu_298;
reg   [9:0] p_0_5_0_0_014417749_fu_302;
reg   [9:0] p_0_4_0_0_014217451_fu_306;
reg   [9:0] p_0_3_0_0_014017153_fu_310;
reg   [9:0] p_0_2_0_0_013816855_fu_314;
reg   [9:0] p_0_1_0_0_013616557_fu_318;
reg   [9:0] p_0_0_0_0_013416259_fu_322;
reg   [9:0] p_0_13_0_0_016061_fu_326;
reg   [9:0] p_0_12_0_0_015862_fu_330;
reg   [9:0] p_0_11_0_0_015663_fu_334;
reg   [9:0] p_0_10_0_0_015464_fu_338;
reg   [9:0] p_0_9_0_0_015265_fu_342;
reg   [9:0] p_0_8_0_0_015066_fu_346;
reg   [9:0] p_0_7_0_0_014867_fu_350;
reg   [9:0] p_0_6_0_0_014668_fu_354;
reg   [9:0] p_0_5_0_0_014469_fu_358;
reg   [9:0] p_0_4_0_0_014270_fu_362;
reg   [9:0] p_0_3_0_0_014071_fu_366;
reg   [9:0] p_0_2_0_0_013872_fu_370;
reg   [9:0] p_0_1_0_0_013673_fu_374;
reg   [3:0] i_iw_fu_378;
wire   [3:0] i_iw_3_fu_2893_p3;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] add_ln227_fu_1001_p2;
wire   [0:0] and_ln191_fu_1264_p2;
wire   [0:0] icmp_ln191_4_fu_1258_p2;
wire   [9:0] select_ln24177_fu_1335_p3;
wire   [12:0] shl_ln_fu_1319_p3;
wire   [12:0] shl_ln199_s_fu_1327_p3;
wire   [0:0] icmp_ln66_fu_1358_p2;
wire   [0:0] xor_ln66_fu_1364_p2;
wire   [12:0] shl_ln199_31_fu_1343_p3;
wire   [12:0] shl_ln199_32_fu_1351_p3;
wire   [0:0] icmp_ln66_24_fu_1378_p2;
wire   [0:0] xor_ln66_24_fu_1384_p2;
wire   [12:0] select_ln0_fu_1370_p3;
wire   [12:0] select_ln0_16_fu_1390_p3;
wire   [0:0] icmp_ln66_25_fu_1398_p2;
wire   [0:0] xor_ln66_25_fu_1404_p2;
wire   [12:0] select_ln66_fu_1410_p3;
wire   [12:0] shl_ln199_33_fu_1436_p3;
wire   [12:0] shl_ln199_34_fu_1444_p3;
wire   [0:0] icmp_ln66_26_fu_1467_p2;
wire   [0:0] xor_ln66_26_fu_1473_p2;
wire   [12:0] shl_ln199_35_fu_1452_p3;
wire   [12:0] shl_ln199_36_fu_1460_p3;
wire   [0:0] icmp_ln66_27_fu_1487_p2;
wire   [0:0] xor_ln66_27_fu_1493_p2;
wire   [12:0] select_ln0_17_fu_1479_p3;
wire   [12:0] select_ln0_18_fu_1499_p3;
wire   [0:0] icmp_ln66_28_fu_1507_p2;
wire   [0:0] xor_ln66_28_fu_1513_p2;
wire   [12:0] select_ln66_8_fu_1519_p3;
wire   [12:0] shl_ln199_37_fu_1545_p3;
wire   [12:0] shl_ln199_38_fu_1553_p3;
wire   [0:0] icmp_ln66_29_fu_1576_p2;
wire   [0:0] xor_ln66_29_fu_1582_p2;
wire   [12:0] shl_ln199_39_fu_1561_p3;
wire   [12:0] shl_ln199_40_fu_1569_p3;
wire   [0:0] icmp_ln66_30_fu_1596_p2;
wire   [0:0] xor_ln66_30_fu_1602_p2;
wire   [12:0] select_ln0_19_fu_1588_p3;
wire   [12:0] select_ln0_20_fu_1608_p3;
wire   [0:0] icmp_ln66_31_fu_1616_p2;
wire   [0:0] xor_ln66_31_fu_1622_p2;
wire   [12:0] select_ln66_9_fu_1628_p3;
wire   [12:0] shl_ln199_41_fu_1654_p3;
wire   [12:0] shl_ln199_42_fu_1662_p3;
wire   [0:0] icmp_ln66_32_fu_1685_p2;
wire   [0:0] xor_ln66_32_fu_1691_p2;
wire   [12:0] shl_ln199_43_fu_1670_p3;
wire   [12:0] shl_ln199_44_fu_1678_p3;
wire   [0:0] icmp_ln66_33_fu_1705_p2;
wire   [0:0] xor_ln66_33_fu_1711_p2;
wire   [12:0] select_ln0_21_fu_1697_p3;
wire   [12:0] select_ln0_22_fu_1717_p3;
wire   [0:0] icmp_ln66_34_fu_1725_p2;
wire   [0:0] xor_ln66_34_fu_1731_p2;
wire   [12:0] select_ln66_10_fu_1737_p3;
wire   [12:0] shl_ln199_45_fu_1763_p3;
wire   [12:0] shl_ln199_46_fu_1771_p3;
wire   [0:0] icmp_ln66_35_fu_1794_p2;
wire   [0:0] xor_ln66_35_fu_1800_p2;
wire   [12:0] shl_ln199_47_fu_1779_p3;
wire   [12:0] shl_ln199_48_fu_1787_p3;
wire   [0:0] icmp_ln66_36_fu_1814_p2;
wire   [0:0] xor_ln66_36_fu_1820_p2;
wire   [12:0] select_ln0_23_fu_1806_p3;
wire   [12:0] select_ln0_24_fu_1826_p3;
wire   [0:0] icmp_ln66_37_fu_1834_p2;
wire   [0:0] xor_ln66_37_fu_1840_p2;
wire   [12:0] select_ln66_11_fu_1846_p3;
wire   [12:0] shl_ln199_49_fu_1872_p3;
wire   [12:0] shl_ln199_50_fu_1880_p3;
wire   [0:0] icmp_ln66_38_fu_1903_p2;
wire   [0:0] xor_ln66_38_fu_1909_p2;
wire   [12:0] shl_ln199_51_fu_1888_p3;
wire   [12:0] shl_ln199_52_fu_1896_p3;
wire   [0:0] icmp_ln66_39_fu_1923_p2;
wire   [0:0] xor_ln66_39_fu_1929_p2;
wire   [12:0] select_ln0_25_fu_1915_p3;
wire   [12:0] select_ln0_26_fu_1935_p3;
wire   [0:0] icmp_ln66_40_fu_1943_p2;
wire   [0:0] xor_ln66_40_fu_1949_p2;
wire   [12:0] select_ln66_12_fu_1955_p3;
wire   [12:0] shl_ln199_53_fu_1981_p3;
wire   [12:0] shl_ln199_54_fu_1989_p3;
wire   [0:0] icmp_ln66_41_fu_2012_p2;
wire   [0:0] xor_ln66_41_fu_2018_p2;
wire   [12:0] shl_ln199_55_fu_1997_p3;
wire   [12:0] shl_ln199_56_fu_2005_p3;
wire   [0:0] icmp_ln66_42_fu_2032_p2;
wire   [0:0] xor_ln66_42_fu_2038_p2;
wire   [12:0] select_ln0_27_fu_2024_p3;
wire   [12:0] select_ln0_28_fu_2044_p3;
wire   [0:0] icmp_ln66_43_fu_2052_p2;
wire   [0:0] xor_ln66_43_fu_2058_p2;
wire   [12:0] select_ln66_13_fu_2064_p3;
wire   [12:0] shl_ln199_57_fu_2090_p3;
wire   [12:0] shl_ln199_58_fu_2098_p3;
wire   [0:0] icmp_ln66_44_fu_2121_p2;
wire   [0:0] xor_ln66_44_fu_2127_p2;
wire   [12:0] shl_ln199_59_fu_2106_p3;
wire   [12:0] shl_ln199_60_fu_2114_p3;
wire   [0:0] icmp_ln66_45_fu_2141_p2;
wire   [0:0] xor_ln66_45_fu_2147_p2;
wire   [12:0] select_ln0_29_fu_2133_p3;
wire   [12:0] select_ln0_30_fu_2153_p3;
wire   [0:0] icmp_ln66_46_fu_2161_p2;
wire   [0:0] xor_ln66_46_fu_2167_p2;
wire   [12:0] select_ln66_14_fu_2173_p3;
wire   [12:0] shl_ln199_61_fu_2199_p3;
wire   [12:0] shl_ln199_62_fu_2207_p3;
wire   [0:0] icmp_ln66_47_fu_2230_p2;
wire   [0:0] xor_ln66_47_fu_2236_p2;
wire   [12:0] shl_ln199_63_fu_2215_p3;
wire   [12:0] shl_ln199_64_fu_2223_p3;
wire   [0:0] icmp_ln66_48_fu_2250_p2;
wire   [0:0] xor_ln66_48_fu_2256_p2;
wire   [12:0] select_ln0_31_fu_2242_p3;
wire   [12:0] select_ln0_32_fu_2262_p3;
wire   [0:0] icmp_ln66_49_fu_2270_p2;
wire   [0:0] xor_ln66_49_fu_2276_p2;
wire   [12:0] select_ln66_15_fu_2282_p3;
wire   [12:0] shl_ln199_65_fu_2308_p3;
wire   [12:0] shl_ln199_66_fu_2316_p3;
wire   [0:0] icmp_ln66_50_fu_2339_p2;
wire   [0:0] xor_ln66_50_fu_2345_p2;
wire   [12:0] shl_ln199_67_fu_2324_p3;
wire   [12:0] shl_ln199_68_fu_2332_p3;
wire   [0:0] icmp_ln66_51_fu_2359_p2;
wire   [0:0] xor_ln66_51_fu_2365_p2;
wire   [12:0] select_ln0_33_fu_2351_p3;
wire   [12:0] select_ln0_34_fu_2371_p3;
wire   [0:0] icmp_ln66_52_fu_2379_p2;
wire   [0:0] xor_ln66_52_fu_2385_p2;
wire   [12:0] select_ln66_16_fu_2391_p3;
wire   [12:0] shl_ln199_69_fu_2417_p3;
wire   [12:0] shl_ln199_70_fu_2425_p3;
wire   [0:0] icmp_ln66_53_fu_2448_p2;
wire   [0:0] xor_ln66_53_fu_2454_p2;
wire   [12:0] shl_ln199_71_fu_2433_p3;
wire   [12:0] shl_ln199_72_fu_2441_p3;
wire   [0:0] icmp_ln66_54_fu_2468_p2;
wire   [0:0] xor_ln66_54_fu_2474_p2;
wire   [12:0] select_ln0_35_fu_2460_p3;
wire   [12:0] select_ln0_36_fu_2480_p3;
wire   [0:0] icmp_ln66_55_fu_2488_p2;
wire   [0:0] xor_ln66_55_fu_2494_p2;
wire   [12:0] select_ln66_17_fu_2500_p3;
wire   [12:0] shl_ln199_73_fu_2526_p3;
wire   [12:0] shl_ln199_74_fu_2534_p3;
wire   [0:0] icmp_ln66_56_fu_2557_p2;
wire   [0:0] xor_ln66_56_fu_2563_p2;
wire   [12:0] shl_ln199_75_fu_2542_p3;
wire   [12:0] shl_ln199_76_fu_2550_p3;
wire   [0:0] icmp_ln66_57_fu_2577_p2;
wire   [0:0] xor_ln66_57_fu_2583_p2;
wire   [12:0] select_ln0_37_fu_2569_p3;
wire   [12:0] select_ln0_38_fu_2589_p3;
wire   [0:0] icmp_ln66_58_fu_2597_p2;
wire   [0:0] xor_ln66_58_fu_2603_p2;
wire   [12:0] select_ln66_18_fu_2609_p3;
wire   [12:0] shl_ln199_77_fu_2635_p3;
wire   [12:0] shl_ln199_78_fu_2643_p3;
wire   [0:0] icmp_ln66_59_fu_2666_p2;
wire   [0:0] xor_ln66_59_fu_2672_p2;
wire   [12:0] shl_ln199_79_fu_2651_p3;
wire   [12:0] shl_ln199_80_fu_2659_p3;
wire   [0:0] icmp_ln66_60_fu_2686_p2;
wire   [0:0] xor_ln66_60_fu_2692_p2;
wire   [12:0] select_ln0_39_fu_2678_p3;
wire   [12:0] select_ln0_40_fu_2698_p3;
wire   [0:0] icmp_ln66_61_fu_2706_p2;
wire   [0:0] xor_ln66_61_fu_2712_p2;
wire   [12:0] select_ln66_19_fu_2718_p3;
wire   [12:0] shl_ln199_81_fu_2744_p3;
wire   [12:0] shl_ln199_82_fu_2752_p3;
wire   [0:0] icmp_ln66_62_fu_2775_p2;
wire   [0:0] xor_ln66_62_fu_2781_p2;
wire   [12:0] shl_ln199_83_fu_2760_p3;
wire   [12:0] shl_ln199_84_fu_2768_p3;
wire   [0:0] icmp_ln66_63_fu_2795_p2;
wire   [0:0] xor_ln66_63_fu_2801_p2;
wire   [12:0] select_ln0_41_fu_2787_p3;
wire   [12:0] select_ln0_42_fu_2807_p3;
wire   [0:0] icmp_ln66_64_fu_2815_p2;
wire   [0:0] xor_ln66_64_fu_2821_p2;
wire   [12:0] select_ln66_20_fu_2827_p3;
wire   [0:0] icmp_ln222_fu_2857_p2;
wire   [31:0] add_ln222_fu_2863_p2;
wire   [3:0] add_ln243_fu_2887_p2;
wire   [9:0] zext_ln204_fu_3090_p1;
wire   [9:0] zext_ln204_8_fu_3098_p1;
wire   [9:0] zext_ln204_9_fu_3106_p1;
wire   [9:0] zext_ln204_10_fu_3114_p1;
wire   [9:0] zext_ln204_11_fu_3122_p1;
wire   [9:0] zext_ln204_12_fu_3130_p1;
wire   [9:0] zext_ln204_13_fu_3138_p1;
wire   [9:0] zext_ln204_14_fu_3146_p1;
wire   [9:0] zext_ln204_15_fu_3154_p1;
wire   [9:0] zext_ln204_16_fu_3162_p1;
wire   [9:0] zext_ln204_17_fu_3170_p1;
wire   [9:0] zext_ln204_18_fu_3178_p1;
wire   [9:0] zext_ln204_19_fu_3186_p1;
wire   [9:0] zext_ln204_20_fu_3194_p1;
wire   [9:0] res_pack_20_fu_3197_p2;
wire   [9:0] res_pack_19_fu_3189_p2;
wire   [9:0] res_pack_18_fu_3181_p2;
wire   [9:0] res_pack_17_fu_3173_p2;
wire   [9:0] res_pack_16_fu_3165_p2;
wire   [9:0] res_pack_15_fu_3157_p2;
wire   [9:0] res_pack_14_fu_3149_p2;
wire   [9:0] res_pack_13_fu_3141_p2;
wire   [9:0] res_pack_12_fu_3133_p2;
wire   [9:0] res_pack_11_fu_3125_p2;
wire   [9:0] res_pack_10_fu_3117_p2;
wire   [9:0] res_pack_9_fu_3109_p2;
wire   [9:0] res_pack_8_fu_3101_p2;
wire   [9:0] res_pack_fu_3093_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_157;
reg    ap_condition_416;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_12 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_8 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_7 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_6 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_5 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_4 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_3 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_2 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_1 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_s = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_11 = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_10 = 10'd0;
#0 void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_14u_0_line_buffer = 10'd0;
#0 p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_9 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_27 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_26 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_25 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_24 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_23 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_22 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_21 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_20 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_19 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_18 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_17 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_16 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_15 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_14 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_13 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_12 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_11 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_10 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_9 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_8 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_7 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_6 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_5 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_4 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_3 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_2 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_1 = 10'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap = 10'd0;
#0 sX_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 indvar_flatten3_fu_210 = 8'd0;
#0 p_0_13_0_0_02566_fu_214 = 10'd0;
#0 p_0_12_0_0_02528_fu_218 = 10'd0;
#0 p_0_11_0_0_024810_fu_222 = 10'd0;
#0 p_0_10_0_0_024412_fu_226 = 10'd0;
#0 p_0_9_0_0_024014_fu_230 = 10'd0;
#0 p_0_8_0_0_023616_fu_234 = 10'd0;
#0 p_0_7_0_0_023218_fu_238 = 10'd0;
#0 p_0_6_0_0_022820_fu_242 = 10'd0;
#0 p_0_5_0_0_022422_fu_246 = 10'd0;
#0 p_0_4_0_0_022024_fu_250 = 10'd0;
#0 p_0_3_0_0_021626_fu_254 = 10'd0;
#0 p_0_2_0_0_021228_fu_258 = 10'd0;
#0 p_0_1_0_0_020830_fu_262 = 10'd0;
#0 p_0_0_0_0_020432_fu_266 = 10'd0;
#0 p_0_13_0_0_016020133_fu_270 = 10'd0;
#0 p_0_12_0_0_015819835_fu_274 = 10'd0;
#0 p_0_11_0_0_015619537_fu_278 = 10'd0;
#0 p_0_10_0_0_015419239_fu_282 = 10'd0;
#0 p_0_9_0_0_015218941_fu_286 = 10'd0;
#0 p_0_8_0_0_015018643_fu_290 = 10'd0;
#0 p_0_7_0_0_014818345_fu_294 = 10'd0;
#0 p_0_6_0_0_014618047_fu_298 = 10'd0;
#0 p_0_5_0_0_014417749_fu_302 = 10'd0;
#0 p_0_4_0_0_014217451_fu_306 = 10'd0;
#0 p_0_3_0_0_014017153_fu_310 = 10'd0;
#0 p_0_2_0_0_013816855_fu_314 = 10'd0;
#0 p_0_1_0_0_013616557_fu_318 = 10'd0;
#0 p_0_0_0_0_013416259_fu_322 = 10'd0;
#0 p_0_13_0_0_016061_fu_326 = 10'd0;
#0 p_0_12_0_0_015862_fu_330 = 10'd0;
#0 p_0_11_0_0_015663_fu_334 = 10'd0;
#0 p_0_10_0_0_015464_fu_338 = 10'd0;
#0 p_0_9_0_0_015265_fu_342 = 10'd0;
#0 p_0_8_0_0_015066_fu_346 = 10'd0;
#0 p_0_7_0_0_014867_fu_350 = 10'd0;
#0 p_0_6_0_0_014668_fu_354 = 10'd0;
#0 p_0_5_0_0_014469_fu_358 = 10'd0;
#0 p_0_4_0_0_014270_fu_362 = 10'd0;
#0 p_0_3_0_0_014071_fu_366 = 10'd0;
#0 p_0_2_0_0_013872_fu_370 = 10'd0;
#0 p_0_1_0_0_013673_fu_374 = 10'd0;
#0 i_iw_fu_378 = 4'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_pp0_flush_enable)) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_157)) begin
        if (((icmp_ln216_fu_1043_p2 == 1'd1) & (icmp_ln212_fu_989_p2 == 1'd1))) begin
            ap_phi_reg_pp0_iter1_storemerge_i_i_reg_416 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_i_i_reg_416 <= ap_phi_reg_pp0_iter0_storemerge_i_i_reg_416;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        i_iw_fu_378 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_iw_fu_378 <= i_iw_3_fu_2893_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_3900_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln24376_reg_395 <= icmp_ln243_reg_4113;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        icmp_ln24376_reg_395 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        indvar_flatten3_fu_210 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten3_fu_210 <= add_ln241_fu_961_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_157)) begin
        if ((icmp_ln212_fu_989_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln212_fu_989_p2 == 1'd0)) begin
            pX_1 <= add_ln212_fu_983_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_416)) begin
        if ((icmp_ln216_fu_1043_p2 == 1'd1)) begin
            pY_1 <= 32'd0;
        end else if ((icmp_ln216_fu_1043_p2 == 1'd0)) begin
            pY_1 <= add_ln216_fu_1037_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_013416259_fu_322 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_27;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_013416259_fu_322 <= ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln241_reg_3900_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_013474_reg_406 <= trunc_ln247_reg_3752_pp0_iter1_reg;
    end else if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_013474_reg_406 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_12;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_0_0_0_020432_fu_266 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_13;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_0_0_0_020432_fu_266 <= trunc_ln247_reg_3752;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_015419239_fu_282 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_17;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_10_0_0_015419239_fu_282 <= select_ln241_9_fu_1174_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_015464_fu_338 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_11;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_10_0_0_015464_fu_338 <= trunc_ln247_s_reg_3842;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_10_0_0_024412_fu_226 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_3;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_10_0_0_024412_fu_226 <= trunc_ln247_s_reg_3842;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_015619537_fu_278 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_16;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_11_0_0_015619537_fu_278 <= select_ln241_8_fu_1166_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_015663_fu_334 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_10;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_11_0_0_015663_fu_334 <= trunc_ln247_10_reg_3851;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_11_0_0_024810_fu_222 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_2;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_11_0_0_024810_fu_222 <= trunc_ln247_10_reg_3851;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_015819835_fu_274 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_15;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_12_0_0_015819835_fu_274 <= select_ln241_7_fu_1158_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_015862_fu_330 <= void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_14u_0_line_buffer;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_12_0_0_015862_fu_330 <= trunc_ln247_11_reg_3860;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_12_0_0_02528_fu_218 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_12_0_0_02528_fu_218 <= trunc_ln247_11_reg_3860;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_016020133_fu_270 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_14;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_13_0_0_016020133_fu_270 <= select_ln241_fu_1150_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_016061_fu_326 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_9;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_13_0_0_016061_fu_326 <= trunc_ln247_12_reg_3869;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_13_0_0_02566_fu_214 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_13_0_0_02566_fu_214 <= trunc_ln247_12_reg_3869;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_013616557_fu_318 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_26;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_1_0_0_013616557_fu_318 <= select_ln241_18_fu_1246_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_013673_fu_374 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_8;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_1_0_0_013673_fu_374 <= trunc_ln247_1_reg_3761;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_1_0_0_020830_fu_262 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_12;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_1_0_0_020830_fu_262 <= trunc_ln247_1_reg_3761;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_013816855_fu_314 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_25;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_2_0_0_013816855_fu_314 <= select_ln241_17_fu_1238_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_013872_fu_370 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_7;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_2_0_0_013872_fu_370 <= trunc_ln247_2_reg_3770;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_2_0_0_021228_fu_258 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_11;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_2_0_0_021228_fu_258 <= trunc_ln247_2_reg_3770;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_014017153_fu_310 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_24;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_3_0_0_014017153_fu_310 <= select_ln241_16_fu_1230_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_014071_fu_366 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_6;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_3_0_0_014071_fu_366 <= trunc_ln247_3_reg_3779;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_3_0_0_021626_fu_254 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_10;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_3_0_0_021626_fu_254 <= trunc_ln247_3_reg_3779;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_014217451_fu_306 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_23;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_4_0_0_014217451_fu_306 <= select_ln241_15_fu_1222_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_014270_fu_362 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_5;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_4_0_0_014270_fu_362 <= trunc_ln247_4_reg_3788;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_4_0_0_022024_fu_250 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_9;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_4_0_0_022024_fu_250 <= trunc_ln247_4_reg_3788;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_014417749_fu_302 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_22;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_5_0_0_014417749_fu_302 <= select_ln241_14_fu_1214_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_014469_fu_358 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_4;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_5_0_0_014469_fu_358 <= trunc_ln247_5_reg_3797;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_5_0_0_022422_fu_246 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_8;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_5_0_0_022422_fu_246 <= trunc_ln247_5_reg_3797;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_014618047_fu_298 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_21;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_6_0_0_014618047_fu_298 <= select_ln241_13_fu_1206_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_014668_fu_354 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_3;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_6_0_0_014668_fu_354 <= trunc_ln247_6_reg_3806;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_6_0_0_022820_fu_242 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_7;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_6_0_0_022820_fu_242 <= trunc_ln247_6_reg_3806;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_014818345_fu_294 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_20;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_7_0_0_014818345_fu_294 <= select_ln241_12_fu_1198_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_014867_fu_350 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_2;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_7_0_0_014867_fu_350 <= trunc_ln247_7_reg_3815;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_7_0_0_023218_fu_238 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_6;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_7_0_0_023218_fu_238 <= trunc_ln247_7_reg_3815;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_015018643_fu_290 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_19;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_8_0_0_015018643_fu_290 <= select_ln241_11_fu_1190_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_015066_fu_346 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_8_0_0_015066_fu_346 <= trunc_ln247_8_reg_3824;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_8_0_0_023616_fu_234 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_5;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_8_0_0_023616_fu_234 <= trunc_ln247_8_reg_3824;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_015218941_fu_286 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_18;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_9_0_0_015218941_fu_286 <= select_ln241_10_fu_1182_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_015265_fu_342 <= p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_s;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_9_0_0_015265_fu_342 <= trunc_ln247_9_reg_3833;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        p_0_9_0_0_024014_fu_230 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_4;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_0_9_0_0_024014_fu_230 <= trunc_ln247_9_reg_3833;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_157)) begin
        if ((icmp_ln212_fu_989_p2 == 1'd1)) begin
            sX_1 <= 32'd0;
        end else if ((icmp_ln212_fu_989_p2 == 1'd0)) begin
            sX_1 <= select_ln227_fu_1007_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln191_2_reg_3969 <= and_ln191_2_fu_1268_p2;
        icmp_ln191_5_reg_3882 <= icmp_ln191_5_fu_971_p2;
        icmp_ln191_6_reg_3887 <= icmp_ln191_6_fu_977_p2;
        icmp_ln191_reg_3878 <= icmp_ln191_fu_951_p2;
        icmp_ln191_reg_3878_pp0_iter1_reg <= icmp_ln191_reg_3878;
        icmp_ln212_reg_3892 <= icmp_ln212_fu_989_p2;
        icmp_ln216_reg_3896 <= icmp_ln216_fu_1043_p2;
        icmp_ln241_reg_3900 <= icmp_ln241_fu_1061_p2;
        icmp_ln241_reg_3900_pp0_iter1_reg <= icmp_ln241_reg_3900;
        tmp_10_reg_4008 <= select_ln66_10_fu_1737_p3[32'd2];
        tmp_11_reg_4018 <= select_ln66_11_fu_1846_p3[32'd2];
        tmp_12_reg_4028 <= select_ln66_12_fu_1955_p3[32'd2];
        tmp_13_reg_4038 <= select_ln66_13_fu_2064_p3[32'd2];
        tmp_14_reg_4048 <= select_ln66_14_fu_2173_p3[32'd2];
        tmp_15_reg_4058 <= select_ln66_15_fu_2282_p3[32'd2];
        tmp_16_reg_4068 <= select_ln66_16_fu_2391_p3[32'd2];
        tmp_17_reg_4078 <= select_ln66_17_fu_2500_p3[32'd2];
        tmp_18_reg_4088 <= select_ln66_18_fu_2609_p3[32'd2];
        tmp_19_reg_4098 <= select_ln66_19_fu_2718_p3[32'd2];
        tmp_20_reg_4108 <= select_ln66_20_fu_2827_p3[32'd2];
        tmp_8_reg_3988 <= select_ln66_8_fu_1519_p3[32'd2];
        tmp_9_reg_3998 <= select_ln66_9_fu_1628_p3[32'd2];
        tmp_reg_3978 <= select_ln66_fu_1410_p3[32'd2];
        trunc_ln204_10_reg_4083 <= {{select_ln66_18_fu_2609_p3[12:3]}};
        trunc_ln204_11_reg_4093 <= {{select_ln66_19_fu_2718_p3[12:3]}};
        trunc_ln204_12_reg_4103 <= {{select_ln66_20_fu_2827_p3[12:3]}};
        trunc_ln204_1_reg_4013 <= {{select_ln66_11_fu_1846_p3[12:3]}};
        trunc_ln204_2_reg_4023 <= {{select_ln66_12_fu_1955_p3[12:3]}};
        trunc_ln204_3_reg_4033 <= {{select_ln66_13_fu_2064_p3[12:3]}};
        trunc_ln204_4_reg_4043 <= {{select_ln66_14_fu_2173_p3[12:3]}};
        trunc_ln204_5_reg_4053 <= {{select_ln66_15_fu_2282_p3[12:3]}};
        trunc_ln204_6_reg_4063 <= {{select_ln66_16_fu_2391_p3[12:3]}};
        trunc_ln204_7_reg_4073 <= {{select_ln66_17_fu_2500_p3[12:3]}};
        trunc_ln204_8_reg_3983 <= {{select_ln66_8_fu_1519_p3[12:3]}};
        trunc_ln204_9_reg_3993 <= {{select_ln66_9_fu_1628_p3[12:3]}};
        trunc_ln204_s_reg_4003 <= {{select_ln66_10_fu_1737_p3[12:3]}};
        trunc_ln247_reg_3752_pp0_iter1_reg <= trunc_ln247_reg_3752;
        trunc_ln_reg_3973 <= {{select_ln66_fu_1410_p3[12:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln243_reg_4113 <= icmp_ln243_fu_2901_p2;
        select_ln241_10_reg_3924 <= select_ln241_10_fu_1182_p3;
        select_ln241_11_reg_3929 <= select_ln241_11_fu_1190_p3;
        select_ln241_12_reg_3934 <= select_ln241_12_fu_1198_p3;
        select_ln241_13_reg_3939 <= select_ln241_13_fu_1206_p3;
        select_ln241_14_reg_3944 <= select_ln241_14_fu_1214_p3;
        select_ln241_15_reg_3949 <= select_ln241_15_fu_1222_p3;
        select_ln241_16_reg_3954 <= select_ln241_16_fu_1230_p3;
        select_ln241_17_reg_3959 <= select_ln241_17_fu_1238_p3;
        select_ln241_18_reg_3964 <= select_ln241_18_fu_1246_p3;
        select_ln241_7_reg_3909 <= select_ln241_7_fu_1158_p3;
        select_ln241_8_reg_3914 <= select_ln241_8_fu_1166_p3;
        select_ln241_9_reg_3919 <= select_ln241_9_fu_1174_p3;
        select_ln241_reg_3904 <= select_ln241_fu_1150_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_1 <= trunc_ln247_8_reg_3824;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_10 <= trunc_ln247_10_reg_3851;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_11 <= trunc_ln247_s_reg_3842;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_12 <= trunc_ln247_reg_3752;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_2 <= trunc_ln247_7_reg_3815;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_3 <= trunc_ln247_6_reg_3806;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_4 <= trunc_ln247_5_reg_3797;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_5 <= trunc_ln247_4_reg_3788;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_6 <= trunc_ln247_3_reg_3779;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_7 <= trunc_ln247_2_reg_3770;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_8 <= trunc_ln247_1_reg_3761;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_9 <= trunc_ln247_12_reg_3869;
        p_ZZN4nnet19pooling2d_buffer_clINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_o_s <= trunc_ln247_9_reg_3833;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap <= trunc_ln247_12_reg_3869;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_1 <= trunc_ln247_11_reg_3860;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_10 <= trunc_ln247_3_reg_3779;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_11 <= trunc_ln247_2_reg_3770;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_12 <= trunc_ln247_1_reg_3761;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_13 <= trunc_ln247_reg_3752;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_14 <= select_ln241_reg_3904;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_15 <= select_ln241_7_reg_3909;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_16 <= select_ln241_8_reg_3914;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_17 <= select_ln241_9_reg_3919;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_18 <= select_ln241_10_reg_3924;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_19 <= select_ln241_11_reg_3929;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_2 <= trunc_ln247_10_reg_3851;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_20 <= select_ln241_12_reg_3934;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_21 <= select_ln241_13_reg_3939;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_22 <= select_ln241_14_reg_3944;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_23 <= select_ln241_15_reg_3949;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_24 <= select_ln241_16_reg_3954;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_25 <= select_ln241_17_reg_3959;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_26 <= select_ln241_18_reg_3964;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_27 <= p_0_0_0_0_013474_reg_406;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_3 <= trunc_ln247_s_reg_3842;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_4 <= trunc_ln247_9_reg_3833;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_5 <= trunc_ln247_8_reg_3824;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_6 <= trunc_ln247_7_reg_3815;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_7 <= trunc_ln247_6_reg_3806;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_8 <= trunc_ln247_5_reg_3797;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi10ELi4EL9ap_q_mode0EL9ap_9 <= trunc_ln247_4_reg_3788;
        void_pooling2d_buffer_cl_stream_stream_array_ap_fixed_14u_0_line_buffer <= trunc_ln247_11_reg_3860;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln212_reg_3892 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sY_1 <= ap_phi_mux_storemerge_i_i_phi_fu_420_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        trunc_ln247_10_reg_3851 <= {{layer6_out_dout[119:110]}};
        trunc_ln247_11_reg_3860 <= {{layer6_out_dout[129:120]}};
        trunc_ln247_12_reg_3869 <= {{layer6_out_dout[139:130]}};
        trunc_ln247_1_reg_3761 <= {{layer6_out_dout[19:10]}};
        trunc_ln247_2_reg_3770 <= {{layer6_out_dout[29:20]}};
        trunc_ln247_3_reg_3779 <= {{layer6_out_dout[39:30]}};
        trunc_ln247_4_reg_3788 <= {{layer6_out_dout[49:40]}};
        trunc_ln247_5_reg_3797 <= {{layer6_out_dout[59:50]}};
        trunc_ln247_6_reg_3806 <= {{layer6_out_dout[69:60]}};
        trunc_ln247_7_reg_3815 <= {{layer6_out_dout[79:70]}};
        trunc_ln247_8_reg_3824 <= {{layer6_out_dout[89:80]}};
        trunc_ln247_9_reg_3833 <= {{layer6_out_dout[99:90]}};
        trunc_ln247_reg_3752 <= trunc_ln247_fu_813_p1;
        trunc_ln247_s_reg_3842 <= {{layer6_out_dout[109:100]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln241_fu_1061_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_pp0_flush_enable = 1'b1;
    end else begin
        ap_condition_pp0_flush_enable = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_3900_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_icmp_ln24376_phi_fu_399_p4 = icmp_ln243_reg_4113;
    end else begin
        ap_phi_mux_icmp_ln24376_phi_fu_399_p4 = icmp_ln24376_reg_395;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_3900_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4 = trunc_ln247_reg_3752_pp0_iter1_reg;
    end else begin
        ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4 = p_0_0_0_0_013474_reg_406;
    end
end

always @ (*) begin
    if (((icmp_ln216_reg_3896 == 1'd0) & (icmp_ln212_reg_3892 == 1'd1))) begin
        ap_phi_mux_storemerge_i_i_phi_fu_420_p4 = select_ln222_fu_2869_p3;
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_420_p4 = ap_phi_reg_pp0_iter1_storemerge_i_i_reg_416;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_2_reg_3969) & (icmp_ln191_reg_3878_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op539_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        layer7_out_write = 1'b1;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln212_fu_983_p2 = (pX_1 + 32'd1);

assign add_ln216_fu_1037_p2 = (pY_1 + 32'd1);

assign add_ln222_fu_2863_p2 = (sY_1 + 32'd1);

assign add_ln227_fu_1001_p2 = (sX_1 + 32'd1);

assign add_ln241_fu_961_p2 = (indvar_flatten3_fu_210 + 8'd1);

assign add_ln243_fu_2887_p2 = (i_iw_fu_378 + 4'd1);

assign and_ln191_2_fu_1268_p2 = (icmp_ln191_4_fu_1258_p2 & and_ln191_fu_1264_p2);

assign and_ln191_fu_1264_p2 = (icmp_ln191_6_reg_3887 & icmp_ln191_5_reg_3882);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((1'b1 == ap_block_state4_pp0_stage0_iter2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state4_pp0_stage0_iter2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state4_pp0_stage0_iter2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state2_pp0_stage0_iter0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (layer6_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((layer7_out_full_n == 1'b0) & (ap_predicate_op539_write_state4 == 1'b1));
end

always @ (*) begin
    ap_condition_157 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_condition_416 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln212_fu_989_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_i_reg_416 = 'bx;

always @ (*) begin
    ap_predicate_op539_write_state4 = ((1'd1 == and_ln191_2_reg_3969) & (icmp_ln191_reg_3878_pp0_iter1_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign i_iw_3_fu_2893_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? 4'd1 : add_ln243_fu_2887_p2);

assign icmp_ln191_4_fu_1258_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln191_5_fu_971_p2 = (($signed(pY_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_6_fu_977_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_951_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_989_p2 = ((add_ln212_fu_983_p2 == 32'd13) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_1043_p2 = ((add_ln216_fu_1037_p2 == 32'd13) ? 1'b1 : 1'b0);

assign icmp_ln222_fu_2857_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_1061_p2 = ((indvar_flatten3_fu_210 == 8'd168) ? 1'b1 : 1'b0);

assign icmp_ln243_fu_2901_p2 = ((i_iw_3_fu_2893_p3 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln66_24_fu_1378_p2 = (($signed(shl_ln199_31_fu_1343_p3) < $signed(shl_ln199_32_fu_1351_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_25_fu_1398_p2 = (($signed(select_ln0_fu_1370_p3) < $signed(select_ln0_16_fu_1390_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_26_fu_1467_p2 = (($signed(shl_ln199_33_fu_1436_p3) < $signed(shl_ln199_34_fu_1444_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_27_fu_1487_p2 = (($signed(shl_ln199_35_fu_1452_p3) < $signed(shl_ln199_36_fu_1460_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_28_fu_1507_p2 = (($signed(select_ln0_17_fu_1479_p3) < $signed(select_ln0_18_fu_1499_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_29_fu_1576_p2 = (($signed(shl_ln199_37_fu_1545_p3) < $signed(shl_ln199_38_fu_1553_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_30_fu_1596_p2 = (($signed(shl_ln199_39_fu_1561_p3) < $signed(shl_ln199_40_fu_1569_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_31_fu_1616_p2 = (($signed(select_ln0_19_fu_1588_p3) < $signed(select_ln0_20_fu_1608_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_32_fu_1685_p2 = (($signed(shl_ln199_41_fu_1654_p3) < $signed(shl_ln199_42_fu_1662_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_33_fu_1705_p2 = (($signed(shl_ln199_43_fu_1670_p3) < $signed(shl_ln199_44_fu_1678_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_34_fu_1725_p2 = (($signed(select_ln0_21_fu_1697_p3) < $signed(select_ln0_22_fu_1717_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_35_fu_1794_p2 = (($signed(shl_ln199_45_fu_1763_p3) < $signed(shl_ln199_46_fu_1771_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_36_fu_1814_p2 = (($signed(shl_ln199_47_fu_1779_p3) < $signed(shl_ln199_48_fu_1787_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_37_fu_1834_p2 = (($signed(select_ln0_23_fu_1806_p3) < $signed(select_ln0_24_fu_1826_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_38_fu_1903_p2 = (($signed(shl_ln199_49_fu_1872_p3) < $signed(shl_ln199_50_fu_1880_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_39_fu_1923_p2 = (($signed(shl_ln199_51_fu_1888_p3) < $signed(shl_ln199_52_fu_1896_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_40_fu_1943_p2 = (($signed(select_ln0_25_fu_1915_p3) < $signed(select_ln0_26_fu_1935_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_41_fu_2012_p2 = (($signed(shl_ln199_53_fu_1981_p3) < $signed(shl_ln199_54_fu_1989_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_42_fu_2032_p2 = (($signed(shl_ln199_55_fu_1997_p3) < $signed(shl_ln199_56_fu_2005_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_43_fu_2052_p2 = (($signed(select_ln0_27_fu_2024_p3) < $signed(select_ln0_28_fu_2044_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_44_fu_2121_p2 = (($signed(shl_ln199_57_fu_2090_p3) < $signed(shl_ln199_58_fu_2098_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_45_fu_2141_p2 = (($signed(shl_ln199_59_fu_2106_p3) < $signed(shl_ln199_60_fu_2114_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_46_fu_2161_p2 = (($signed(select_ln0_29_fu_2133_p3) < $signed(select_ln0_30_fu_2153_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_47_fu_2230_p2 = (($signed(shl_ln199_61_fu_2199_p3) < $signed(shl_ln199_62_fu_2207_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_48_fu_2250_p2 = (($signed(shl_ln199_63_fu_2215_p3) < $signed(shl_ln199_64_fu_2223_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_49_fu_2270_p2 = (($signed(select_ln0_31_fu_2242_p3) < $signed(select_ln0_32_fu_2262_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_50_fu_2339_p2 = (($signed(shl_ln199_65_fu_2308_p3) < $signed(shl_ln199_66_fu_2316_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_51_fu_2359_p2 = (($signed(shl_ln199_67_fu_2324_p3) < $signed(shl_ln199_68_fu_2332_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_52_fu_2379_p2 = (($signed(select_ln0_33_fu_2351_p3) < $signed(select_ln0_34_fu_2371_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_53_fu_2448_p2 = (($signed(shl_ln199_69_fu_2417_p3) < $signed(shl_ln199_70_fu_2425_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_54_fu_2468_p2 = (($signed(shl_ln199_71_fu_2433_p3) < $signed(shl_ln199_72_fu_2441_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_55_fu_2488_p2 = (($signed(select_ln0_35_fu_2460_p3) < $signed(select_ln0_36_fu_2480_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_56_fu_2557_p2 = (($signed(shl_ln199_73_fu_2526_p3) < $signed(shl_ln199_74_fu_2534_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_57_fu_2577_p2 = (($signed(shl_ln199_75_fu_2542_p3) < $signed(shl_ln199_76_fu_2550_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_58_fu_2597_p2 = (($signed(select_ln0_37_fu_2569_p3) < $signed(select_ln0_38_fu_2589_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_59_fu_2666_p2 = (($signed(shl_ln199_77_fu_2635_p3) < $signed(shl_ln199_78_fu_2643_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_60_fu_2686_p2 = (($signed(shl_ln199_79_fu_2651_p3) < $signed(shl_ln199_80_fu_2659_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_61_fu_2706_p2 = (($signed(select_ln0_39_fu_2678_p3) < $signed(select_ln0_40_fu_2698_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_62_fu_2775_p2 = (($signed(shl_ln199_81_fu_2744_p3) < $signed(shl_ln199_82_fu_2752_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_63_fu_2795_p2 = (($signed(shl_ln199_83_fu_2760_p3) < $signed(shl_ln199_84_fu_2768_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_64_fu_2815_p2 = (($signed(select_ln0_41_fu_2787_p3) < $signed(select_ln0_42_fu_2807_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1358_p2 = (($signed(shl_ln_fu_1319_p3) < $signed(shl_ln199_s_fu_1327_p3)) ? 1'b1 : 1'b0);

assign layer7_out_din = {{{{{{{{{{{{{{res_pack_20_fu_3197_p2}, {res_pack_19_fu_3189_p2}}, {res_pack_18_fu_3181_p2}}, {res_pack_17_fu_3173_p2}}, {res_pack_16_fu_3165_p2}}, {res_pack_15_fu_3157_p2}}, {res_pack_14_fu_3149_p2}}, {res_pack_13_fu_3141_p2}}, {res_pack_12_fu_3133_p2}}, {res_pack_11_fu_3125_p2}}, {res_pack_10_fu_3117_p2}}, {res_pack_9_fu_3109_p2}}, {res_pack_8_fu_3101_p2}}, {res_pack_fu_3093_p2}};

assign res_pack_10_fu_3117_p2 = (trunc_ln204_s_reg_4003 + zext_ln204_10_fu_3114_p1);

assign res_pack_11_fu_3125_p2 = (trunc_ln204_1_reg_4013 + zext_ln204_11_fu_3122_p1);

assign res_pack_12_fu_3133_p2 = (trunc_ln204_2_reg_4023 + zext_ln204_12_fu_3130_p1);

assign res_pack_13_fu_3141_p2 = (trunc_ln204_3_reg_4033 + zext_ln204_13_fu_3138_p1);

assign res_pack_14_fu_3149_p2 = (trunc_ln204_4_reg_4043 + zext_ln204_14_fu_3146_p1);

assign res_pack_15_fu_3157_p2 = (trunc_ln204_5_reg_4053 + zext_ln204_15_fu_3154_p1);

assign res_pack_16_fu_3165_p2 = (trunc_ln204_6_reg_4063 + zext_ln204_16_fu_3162_p1);

assign res_pack_17_fu_3173_p2 = (trunc_ln204_7_reg_4073 + zext_ln204_17_fu_3170_p1);

assign res_pack_18_fu_3181_p2 = (trunc_ln204_10_reg_4083 + zext_ln204_18_fu_3178_p1);

assign res_pack_19_fu_3189_p2 = (trunc_ln204_11_reg_4093 + zext_ln204_19_fu_3186_p1);

assign res_pack_20_fu_3197_p2 = (trunc_ln204_12_reg_4103 + zext_ln204_20_fu_3194_p1);

assign res_pack_8_fu_3101_p2 = (trunc_ln204_8_reg_3983 + zext_ln204_8_fu_3098_p1);

assign res_pack_9_fu_3109_p2 = (trunc_ln204_9_reg_3993 + zext_ln204_9_fu_3106_p1);

assign res_pack_fu_3093_p2 = (trunc_ln_reg_3973 + zext_ln204_fu_3090_p1);

assign select_ln0_16_fu_1390_p3 = ((xor_ln66_24_fu_1384_p2[0:0] == 1'b1) ? shl_ln199_31_fu_1343_p3 : shl_ln199_32_fu_1351_p3);

assign select_ln0_17_fu_1479_p3 = ((xor_ln66_26_fu_1473_p2[0:0] == 1'b1) ? shl_ln199_33_fu_1436_p3 : shl_ln199_34_fu_1444_p3);

assign select_ln0_18_fu_1499_p3 = ((xor_ln66_27_fu_1493_p2[0:0] == 1'b1) ? shl_ln199_35_fu_1452_p3 : shl_ln199_36_fu_1460_p3);

assign select_ln0_19_fu_1588_p3 = ((xor_ln66_29_fu_1582_p2[0:0] == 1'b1) ? shl_ln199_37_fu_1545_p3 : shl_ln199_38_fu_1553_p3);

assign select_ln0_20_fu_1608_p3 = ((xor_ln66_30_fu_1602_p2[0:0] == 1'b1) ? shl_ln199_39_fu_1561_p3 : shl_ln199_40_fu_1569_p3);

assign select_ln0_21_fu_1697_p3 = ((xor_ln66_32_fu_1691_p2[0:0] == 1'b1) ? shl_ln199_41_fu_1654_p3 : shl_ln199_42_fu_1662_p3);

assign select_ln0_22_fu_1717_p3 = ((xor_ln66_33_fu_1711_p2[0:0] == 1'b1) ? shl_ln199_43_fu_1670_p3 : shl_ln199_44_fu_1678_p3);

assign select_ln0_23_fu_1806_p3 = ((xor_ln66_35_fu_1800_p2[0:0] == 1'b1) ? shl_ln199_45_fu_1763_p3 : shl_ln199_46_fu_1771_p3);

assign select_ln0_24_fu_1826_p3 = ((xor_ln66_36_fu_1820_p2[0:0] == 1'b1) ? shl_ln199_47_fu_1779_p3 : shl_ln199_48_fu_1787_p3);

assign select_ln0_25_fu_1915_p3 = ((xor_ln66_38_fu_1909_p2[0:0] == 1'b1) ? shl_ln199_49_fu_1872_p3 : shl_ln199_50_fu_1880_p3);

assign select_ln0_26_fu_1935_p3 = ((xor_ln66_39_fu_1929_p2[0:0] == 1'b1) ? shl_ln199_51_fu_1888_p3 : shl_ln199_52_fu_1896_p3);

assign select_ln0_27_fu_2024_p3 = ((xor_ln66_41_fu_2018_p2[0:0] == 1'b1) ? shl_ln199_53_fu_1981_p3 : shl_ln199_54_fu_1989_p3);

assign select_ln0_28_fu_2044_p3 = ((xor_ln66_42_fu_2038_p2[0:0] == 1'b1) ? shl_ln199_55_fu_1997_p3 : shl_ln199_56_fu_2005_p3);

assign select_ln0_29_fu_2133_p3 = ((xor_ln66_44_fu_2127_p2[0:0] == 1'b1) ? shl_ln199_57_fu_2090_p3 : shl_ln199_58_fu_2098_p3);

assign select_ln0_30_fu_2153_p3 = ((xor_ln66_45_fu_2147_p2[0:0] == 1'b1) ? shl_ln199_59_fu_2106_p3 : shl_ln199_60_fu_2114_p3);

assign select_ln0_31_fu_2242_p3 = ((xor_ln66_47_fu_2236_p2[0:0] == 1'b1) ? shl_ln199_61_fu_2199_p3 : shl_ln199_62_fu_2207_p3);

assign select_ln0_32_fu_2262_p3 = ((xor_ln66_48_fu_2256_p2[0:0] == 1'b1) ? shl_ln199_63_fu_2215_p3 : shl_ln199_64_fu_2223_p3);

assign select_ln0_33_fu_2351_p3 = ((xor_ln66_50_fu_2345_p2[0:0] == 1'b1) ? shl_ln199_65_fu_2308_p3 : shl_ln199_66_fu_2316_p3);

assign select_ln0_34_fu_2371_p3 = ((xor_ln66_51_fu_2365_p2[0:0] == 1'b1) ? shl_ln199_67_fu_2324_p3 : shl_ln199_68_fu_2332_p3);

assign select_ln0_35_fu_2460_p3 = ((xor_ln66_53_fu_2454_p2[0:0] == 1'b1) ? shl_ln199_69_fu_2417_p3 : shl_ln199_70_fu_2425_p3);

assign select_ln0_36_fu_2480_p3 = ((xor_ln66_54_fu_2474_p2[0:0] == 1'b1) ? shl_ln199_71_fu_2433_p3 : shl_ln199_72_fu_2441_p3);

assign select_ln0_37_fu_2569_p3 = ((xor_ln66_56_fu_2563_p2[0:0] == 1'b1) ? shl_ln199_73_fu_2526_p3 : shl_ln199_74_fu_2534_p3);

assign select_ln0_38_fu_2589_p3 = ((xor_ln66_57_fu_2583_p2[0:0] == 1'b1) ? shl_ln199_75_fu_2542_p3 : shl_ln199_76_fu_2550_p3);

assign select_ln0_39_fu_2678_p3 = ((xor_ln66_59_fu_2672_p2[0:0] == 1'b1) ? shl_ln199_77_fu_2635_p3 : shl_ln199_78_fu_2643_p3);

assign select_ln0_40_fu_2698_p3 = ((xor_ln66_60_fu_2692_p2[0:0] == 1'b1) ? shl_ln199_79_fu_2651_p3 : shl_ln199_80_fu_2659_p3);

assign select_ln0_41_fu_2787_p3 = ((xor_ln66_62_fu_2781_p2[0:0] == 1'b1) ? shl_ln199_81_fu_2744_p3 : shl_ln199_82_fu_2752_p3);

assign select_ln0_42_fu_2807_p3 = ((xor_ln66_63_fu_2801_p2[0:0] == 1'b1) ? shl_ln199_83_fu_2760_p3 : shl_ln199_84_fu_2768_p3);

assign select_ln0_fu_1370_p3 = ((xor_ln66_fu_1364_p2[0:0] == 1'b1) ? shl_ln_fu_1319_p3 : shl_ln199_s_fu_1327_p3);

assign select_ln222_fu_2869_p3 = ((icmp_ln222_fu_2857_p2[0:0] == 1'b1) ? 32'd0 : add_ln222_fu_2863_p2);

assign select_ln227_fu_1007_p3 = ((icmp_ln191_fu_951_p2[0:0] == 1'b1) ? 32'd0 : add_ln227_fu_1001_p2);

assign select_ln24177_fu_1335_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4 : p_0_0_0_0_020432_fu_266);

assign select_ln241_10_fu_1182_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_9_0_0_024014_fu_230 : p_0_9_0_0_015265_fu_342);

assign select_ln241_11_fu_1190_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_8_0_0_023616_fu_234 : p_0_8_0_0_015066_fu_346);

assign select_ln241_12_fu_1198_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_7_0_0_023218_fu_238 : p_0_7_0_0_014867_fu_350);

assign select_ln241_13_fu_1206_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_6_0_0_022820_fu_242 : p_0_6_0_0_014668_fu_354);

assign select_ln241_14_fu_1214_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_5_0_0_022422_fu_246 : p_0_5_0_0_014469_fu_358);

assign select_ln241_15_fu_1222_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_4_0_0_022024_fu_250 : p_0_4_0_0_014270_fu_362);

assign select_ln241_16_fu_1230_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_3_0_0_021626_fu_254 : p_0_3_0_0_014071_fu_366);

assign select_ln241_17_fu_1238_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_2_0_0_021228_fu_258 : p_0_2_0_0_013872_fu_370);

assign select_ln241_18_fu_1246_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_1_0_0_020830_fu_262 : p_0_1_0_0_013673_fu_374);

assign select_ln241_7_fu_1158_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_12_0_0_02528_fu_218 : p_0_12_0_0_015862_fu_330);

assign select_ln241_8_fu_1166_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_11_0_0_024810_fu_222 : p_0_11_0_0_015663_fu_334);

assign select_ln241_9_fu_1174_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_10_0_0_024412_fu_226 : p_0_10_0_0_015464_fu_338);

assign select_ln241_fu_1150_p3 = ((ap_phi_mux_icmp_ln24376_phi_fu_399_p4[0:0] == 1'b1) ? p_0_13_0_0_02566_fu_214 : p_0_13_0_0_016061_fu_326);

assign select_ln66_10_fu_1737_p3 = ((xor_ln66_34_fu_1731_p2[0:0] == 1'b1) ? select_ln0_21_fu_1697_p3 : select_ln0_22_fu_1717_p3);

assign select_ln66_11_fu_1846_p3 = ((xor_ln66_37_fu_1840_p2[0:0] == 1'b1) ? select_ln0_23_fu_1806_p3 : select_ln0_24_fu_1826_p3);

assign select_ln66_12_fu_1955_p3 = ((xor_ln66_40_fu_1949_p2[0:0] == 1'b1) ? select_ln0_25_fu_1915_p3 : select_ln0_26_fu_1935_p3);

assign select_ln66_13_fu_2064_p3 = ((xor_ln66_43_fu_2058_p2[0:0] == 1'b1) ? select_ln0_27_fu_2024_p3 : select_ln0_28_fu_2044_p3);

assign select_ln66_14_fu_2173_p3 = ((xor_ln66_46_fu_2167_p2[0:0] == 1'b1) ? select_ln0_29_fu_2133_p3 : select_ln0_30_fu_2153_p3);

assign select_ln66_15_fu_2282_p3 = ((xor_ln66_49_fu_2276_p2[0:0] == 1'b1) ? select_ln0_31_fu_2242_p3 : select_ln0_32_fu_2262_p3);

assign select_ln66_16_fu_2391_p3 = ((xor_ln66_52_fu_2385_p2[0:0] == 1'b1) ? select_ln0_33_fu_2351_p3 : select_ln0_34_fu_2371_p3);

assign select_ln66_17_fu_2500_p3 = ((xor_ln66_55_fu_2494_p2[0:0] == 1'b1) ? select_ln0_35_fu_2460_p3 : select_ln0_36_fu_2480_p3);

assign select_ln66_18_fu_2609_p3 = ((xor_ln66_58_fu_2603_p2[0:0] == 1'b1) ? select_ln0_37_fu_2569_p3 : select_ln0_38_fu_2589_p3);

assign select_ln66_19_fu_2718_p3 = ((xor_ln66_61_fu_2712_p2[0:0] == 1'b1) ? select_ln0_39_fu_2678_p3 : select_ln0_40_fu_2698_p3);

assign select_ln66_20_fu_2827_p3 = ((xor_ln66_64_fu_2821_p2[0:0] == 1'b1) ? select_ln0_41_fu_2787_p3 : select_ln0_42_fu_2807_p3);

assign select_ln66_8_fu_1519_p3 = ((xor_ln66_28_fu_1513_p2[0:0] == 1'b1) ? select_ln0_17_fu_1479_p3 : select_ln0_18_fu_1499_p3);

assign select_ln66_9_fu_1628_p3 = ((xor_ln66_31_fu_1622_p2[0:0] == 1'b1) ? select_ln0_19_fu_1588_p3 : select_ln0_20_fu_1608_p3);

assign select_ln66_fu_1410_p3 = ((xor_ln66_25_fu_1404_p2[0:0] == 1'b1) ? select_ln0_fu_1370_p3 : select_ln0_16_fu_1390_p3);

assign shl_ln199_31_fu_1343_p3 = {{select_ln24177_fu_1335_p3}, {3'd0}};

assign shl_ln199_32_fu_1351_p3 = {{trunc_ln247_reg_3752}, {3'd0}};

assign shl_ln199_33_fu_1436_p3 = {{p_0_1_0_0_013616557_fu_318}, {3'd0}};

assign shl_ln199_34_fu_1444_p3 = {{select_ln241_18_fu_1246_p3}, {3'd0}};

assign shl_ln199_35_fu_1452_p3 = {{p_0_1_0_0_020830_fu_262}, {3'd0}};

assign shl_ln199_36_fu_1460_p3 = {{trunc_ln247_1_reg_3761}, {3'd0}};

assign shl_ln199_37_fu_1545_p3 = {{p_0_2_0_0_013816855_fu_314}, {3'd0}};

assign shl_ln199_38_fu_1553_p3 = {{select_ln241_17_fu_1238_p3}, {3'd0}};

assign shl_ln199_39_fu_1561_p3 = {{p_0_2_0_0_021228_fu_258}, {3'd0}};

assign shl_ln199_40_fu_1569_p3 = {{trunc_ln247_2_reg_3770}, {3'd0}};

assign shl_ln199_41_fu_1654_p3 = {{p_0_3_0_0_014017153_fu_310}, {3'd0}};

assign shl_ln199_42_fu_1662_p3 = {{select_ln241_16_fu_1230_p3}, {3'd0}};

assign shl_ln199_43_fu_1670_p3 = {{p_0_3_0_0_021626_fu_254}, {3'd0}};

assign shl_ln199_44_fu_1678_p3 = {{trunc_ln247_3_reg_3779}, {3'd0}};

assign shl_ln199_45_fu_1763_p3 = {{p_0_4_0_0_014217451_fu_306}, {3'd0}};

assign shl_ln199_46_fu_1771_p3 = {{select_ln241_15_fu_1222_p3}, {3'd0}};

assign shl_ln199_47_fu_1779_p3 = {{p_0_4_0_0_022024_fu_250}, {3'd0}};

assign shl_ln199_48_fu_1787_p3 = {{trunc_ln247_4_reg_3788}, {3'd0}};

assign shl_ln199_49_fu_1872_p3 = {{p_0_5_0_0_014417749_fu_302}, {3'd0}};

assign shl_ln199_50_fu_1880_p3 = {{select_ln241_14_fu_1214_p3}, {3'd0}};

assign shl_ln199_51_fu_1888_p3 = {{p_0_5_0_0_022422_fu_246}, {3'd0}};

assign shl_ln199_52_fu_1896_p3 = {{trunc_ln247_5_reg_3797}, {3'd0}};

assign shl_ln199_53_fu_1981_p3 = {{p_0_6_0_0_014618047_fu_298}, {3'd0}};

assign shl_ln199_54_fu_1989_p3 = {{select_ln241_13_fu_1206_p3}, {3'd0}};

assign shl_ln199_55_fu_1997_p3 = {{p_0_6_0_0_022820_fu_242}, {3'd0}};

assign shl_ln199_56_fu_2005_p3 = {{trunc_ln247_6_reg_3806}, {3'd0}};

assign shl_ln199_57_fu_2090_p3 = {{p_0_7_0_0_014818345_fu_294}, {3'd0}};

assign shl_ln199_58_fu_2098_p3 = {{select_ln241_12_fu_1198_p3}, {3'd0}};

assign shl_ln199_59_fu_2106_p3 = {{p_0_7_0_0_023218_fu_238}, {3'd0}};

assign shl_ln199_60_fu_2114_p3 = {{trunc_ln247_7_reg_3815}, {3'd0}};

assign shl_ln199_61_fu_2199_p3 = {{p_0_8_0_0_015018643_fu_290}, {3'd0}};

assign shl_ln199_62_fu_2207_p3 = {{select_ln241_11_fu_1190_p3}, {3'd0}};

assign shl_ln199_63_fu_2215_p3 = {{p_0_8_0_0_023616_fu_234}, {3'd0}};

assign shl_ln199_64_fu_2223_p3 = {{trunc_ln247_8_reg_3824}, {3'd0}};

assign shl_ln199_65_fu_2308_p3 = {{p_0_9_0_0_015218941_fu_286}, {3'd0}};

assign shl_ln199_66_fu_2316_p3 = {{select_ln241_10_fu_1182_p3}, {3'd0}};

assign shl_ln199_67_fu_2324_p3 = {{p_0_9_0_0_024014_fu_230}, {3'd0}};

assign shl_ln199_68_fu_2332_p3 = {{trunc_ln247_9_reg_3833}, {3'd0}};

assign shl_ln199_69_fu_2417_p3 = {{p_0_10_0_0_015419239_fu_282}, {3'd0}};

assign shl_ln199_70_fu_2425_p3 = {{select_ln241_9_fu_1174_p3}, {3'd0}};

assign shl_ln199_71_fu_2433_p3 = {{p_0_10_0_0_024412_fu_226}, {3'd0}};

assign shl_ln199_72_fu_2441_p3 = {{trunc_ln247_s_reg_3842}, {3'd0}};

assign shl_ln199_73_fu_2526_p3 = {{p_0_11_0_0_015619537_fu_278}, {3'd0}};

assign shl_ln199_74_fu_2534_p3 = {{select_ln241_8_fu_1166_p3}, {3'd0}};

assign shl_ln199_75_fu_2542_p3 = {{p_0_11_0_0_024810_fu_222}, {3'd0}};

assign shl_ln199_76_fu_2550_p3 = {{trunc_ln247_10_reg_3851}, {3'd0}};

assign shl_ln199_77_fu_2635_p3 = {{p_0_12_0_0_015819835_fu_274}, {3'd0}};

assign shl_ln199_78_fu_2643_p3 = {{select_ln241_7_fu_1158_p3}, {3'd0}};

assign shl_ln199_79_fu_2651_p3 = {{p_0_12_0_0_02528_fu_218}, {3'd0}};

assign shl_ln199_80_fu_2659_p3 = {{trunc_ln247_11_reg_3860}, {3'd0}};

assign shl_ln199_81_fu_2744_p3 = {{p_0_13_0_0_016020133_fu_270}, {3'd0}};

assign shl_ln199_82_fu_2752_p3 = {{select_ln241_fu_1150_p3}, {3'd0}};

assign shl_ln199_83_fu_2760_p3 = {{p_0_13_0_0_02566_fu_214}, {3'd0}};

assign shl_ln199_84_fu_2768_p3 = {{trunc_ln247_12_reg_3869}, {3'd0}};

assign shl_ln199_s_fu_1327_p3 = {{ap_phi_mux_p_0_0_0_0_013474_phi_fu_409_p4}, {3'd0}};

assign shl_ln_fu_1319_p3 = {{p_0_0_0_0_013416259_fu_322}, {3'd0}};

assign start_out = real_start;

assign trunc_ln247_fu_813_p1 = layer6_out_dout[9:0];

assign xor_ln66_24_fu_1384_p2 = (icmp_ln66_24_fu_1378_p2 ^ 1'd1);

assign xor_ln66_25_fu_1404_p2 = (icmp_ln66_25_fu_1398_p2 ^ 1'd1);

assign xor_ln66_26_fu_1473_p2 = (icmp_ln66_26_fu_1467_p2 ^ 1'd1);

assign xor_ln66_27_fu_1493_p2 = (icmp_ln66_27_fu_1487_p2 ^ 1'd1);

assign xor_ln66_28_fu_1513_p2 = (icmp_ln66_28_fu_1507_p2 ^ 1'd1);

assign xor_ln66_29_fu_1582_p2 = (icmp_ln66_29_fu_1576_p2 ^ 1'd1);

assign xor_ln66_30_fu_1602_p2 = (icmp_ln66_30_fu_1596_p2 ^ 1'd1);

assign xor_ln66_31_fu_1622_p2 = (icmp_ln66_31_fu_1616_p2 ^ 1'd1);

assign xor_ln66_32_fu_1691_p2 = (icmp_ln66_32_fu_1685_p2 ^ 1'd1);

assign xor_ln66_33_fu_1711_p2 = (icmp_ln66_33_fu_1705_p2 ^ 1'd1);

assign xor_ln66_34_fu_1731_p2 = (icmp_ln66_34_fu_1725_p2 ^ 1'd1);

assign xor_ln66_35_fu_1800_p2 = (icmp_ln66_35_fu_1794_p2 ^ 1'd1);

assign xor_ln66_36_fu_1820_p2 = (icmp_ln66_36_fu_1814_p2 ^ 1'd1);

assign xor_ln66_37_fu_1840_p2 = (icmp_ln66_37_fu_1834_p2 ^ 1'd1);

assign xor_ln66_38_fu_1909_p2 = (icmp_ln66_38_fu_1903_p2 ^ 1'd1);

assign xor_ln66_39_fu_1929_p2 = (icmp_ln66_39_fu_1923_p2 ^ 1'd1);

assign xor_ln66_40_fu_1949_p2 = (icmp_ln66_40_fu_1943_p2 ^ 1'd1);

assign xor_ln66_41_fu_2018_p2 = (icmp_ln66_41_fu_2012_p2 ^ 1'd1);

assign xor_ln66_42_fu_2038_p2 = (icmp_ln66_42_fu_2032_p2 ^ 1'd1);

assign xor_ln66_43_fu_2058_p2 = (icmp_ln66_43_fu_2052_p2 ^ 1'd1);

assign xor_ln66_44_fu_2127_p2 = (icmp_ln66_44_fu_2121_p2 ^ 1'd1);

assign xor_ln66_45_fu_2147_p2 = (icmp_ln66_45_fu_2141_p2 ^ 1'd1);

assign xor_ln66_46_fu_2167_p2 = (icmp_ln66_46_fu_2161_p2 ^ 1'd1);

assign xor_ln66_47_fu_2236_p2 = (icmp_ln66_47_fu_2230_p2 ^ 1'd1);

assign xor_ln66_48_fu_2256_p2 = (icmp_ln66_48_fu_2250_p2 ^ 1'd1);

assign xor_ln66_49_fu_2276_p2 = (icmp_ln66_49_fu_2270_p2 ^ 1'd1);

assign xor_ln66_50_fu_2345_p2 = (icmp_ln66_50_fu_2339_p2 ^ 1'd1);

assign xor_ln66_51_fu_2365_p2 = (icmp_ln66_51_fu_2359_p2 ^ 1'd1);

assign xor_ln66_52_fu_2385_p2 = (icmp_ln66_52_fu_2379_p2 ^ 1'd1);

assign xor_ln66_53_fu_2454_p2 = (icmp_ln66_53_fu_2448_p2 ^ 1'd1);

assign xor_ln66_54_fu_2474_p2 = (icmp_ln66_54_fu_2468_p2 ^ 1'd1);

assign xor_ln66_55_fu_2494_p2 = (icmp_ln66_55_fu_2488_p2 ^ 1'd1);

assign xor_ln66_56_fu_2563_p2 = (icmp_ln66_56_fu_2557_p2 ^ 1'd1);

assign xor_ln66_57_fu_2583_p2 = (icmp_ln66_57_fu_2577_p2 ^ 1'd1);

assign xor_ln66_58_fu_2603_p2 = (icmp_ln66_58_fu_2597_p2 ^ 1'd1);

assign xor_ln66_59_fu_2672_p2 = (icmp_ln66_59_fu_2666_p2 ^ 1'd1);

assign xor_ln66_60_fu_2692_p2 = (icmp_ln66_60_fu_2686_p2 ^ 1'd1);

assign xor_ln66_61_fu_2712_p2 = (icmp_ln66_61_fu_2706_p2 ^ 1'd1);

assign xor_ln66_62_fu_2781_p2 = (icmp_ln66_62_fu_2775_p2 ^ 1'd1);

assign xor_ln66_63_fu_2801_p2 = (icmp_ln66_63_fu_2795_p2 ^ 1'd1);

assign xor_ln66_64_fu_2821_p2 = (icmp_ln66_64_fu_2815_p2 ^ 1'd1);

assign xor_ln66_fu_1364_p2 = (icmp_ln66_fu_1358_p2 ^ 1'd1);

assign zext_ln204_10_fu_3114_p1 = tmp_10_reg_4008;

assign zext_ln204_11_fu_3122_p1 = tmp_11_reg_4018;

assign zext_ln204_12_fu_3130_p1 = tmp_12_reg_4028;

assign zext_ln204_13_fu_3138_p1 = tmp_13_reg_4038;

assign zext_ln204_14_fu_3146_p1 = tmp_14_reg_4048;

assign zext_ln204_15_fu_3154_p1 = tmp_15_reg_4058;

assign zext_ln204_16_fu_3162_p1 = tmp_16_reg_4068;

assign zext_ln204_17_fu_3170_p1 = tmp_17_reg_4078;

assign zext_ln204_18_fu_3178_p1 = tmp_18_reg_4088;

assign zext_ln204_19_fu_3186_p1 = tmp_19_reg_4098;

assign zext_ln204_20_fu_3194_p1 = tmp_20_reg_4108;

assign zext_ln204_8_fu_3098_p1 = tmp_8_reg_3988;

assign zext_ln204_9_fu_3106_p1 = tmp_9_reg_3998;

assign zext_ln204_fu_3090_p1 = tmp_reg_3978;

endmodule //cifar10_axis_wrapper_pooling2d_cl_array_array_ap_fixed_10_4_0_3_0_14u_config7_s
