[hls]
relative_roots=C:/Users/Andy/Documents/TFG/Project/3_multiplicacion_acelerada/matrix_hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=matrix_mult/VITIS_LOOP_24_2 
syn.directive.pipeline=matrix_mult/VITIS_LOOP_32_4 
syn.directive.pipeline=matrix_mult/VITIS_LOOP_53_9 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=matrix_mult/VITIS_LOOP_23_1  
syn.directive.loop_flatten=matrix_mult/VITIS_LOOP_31_3  
syn.directive.loop_flatten=matrix_mult/VITIS_LOOP_52_8  
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=matrix_mult/A dim=2 type=complete variable=A
syn.directive.array_partition=matrix_mult/B dim=1 type=complete variable=B
syn.directive.loop_flatten=matrix_mult/VITIS_LOOP_39_5  


