-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_axis_wrapper_relu_array_ap_fixed_32u_array_ap_fixed_11_5_0_3_0_32u_relu_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer8_out_dout : IN STD_LOGIC_VECTOR (351 downto 0);
    layer8_out_empty_n : IN STD_LOGIC;
    layer8_out_read : OUT STD_LOGIC;
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    layer9_out_din : OUT STD_LOGIC_VECTOR (351 downto 0);
    layer9_out_full_n : IN STD_LOGIC;
    layer9_out_write : OUT STD_LOGIC;
    layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of cifar10_axis_wrapper_relu_array_ap_fixed_32u_array_ap_fixed_11_5_0_3_0_32u_relu_config9_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001011";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_61 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100001";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000010";
    constant ap_const_lv32_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000100";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_8D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001101";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_99 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011001";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_9A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011010";
    constant ap_const_lv32_A4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100100";
    constant ap_const_lv32_A3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100011";
    constant ap_const_lv32_A5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100101";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_AE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101110";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111010";
    constant ap_const_lv32_B9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111001";
    constant ap_const_lv32_BB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111011";
    constant ap_const_lv32_C5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000101";
    constant ap_const_lv32_C4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000100";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011010";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_E5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100101";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110001";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110010";
    constant ap_const_lv32_FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111100";
    constant ap_const_lv32_FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111011";
    constant ap_const_lv32_FD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111101";
    constant ap_const_lv32_107 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000111";
    constant ap_const_lv32_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000110";
    constant ap_const_lv32_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001000";
    constant ap_const_lv32_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010010";
    constant ap_const_lv32_111 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010001";
    constant ap_const_lv32_113 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010011";
    constant ap_const_lv32_11D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011101";
    constant ap_const_lv32_11C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011100";
    constant ap_const_lv32_11E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011110";
    constant ap_const_lv32_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101000";
    constant ap_const_lv32_127 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100111";
    constant ap_const_lv32_129 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101001";
    constant ap_const_lv32_133 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110011";
    constant ap_const_lv32_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110010";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_13D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111101";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_149 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001001";
    constant ap_const_lv32_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001000";
    constant ap_const_lv32_14A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001010";
    constant ap_const_lv32_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010100";
    constant ap_const_lv32_153 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010011";
    constant ap_const_lv32_155 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010101";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_15E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011110";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_1339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer8_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal layer9_out_blk_n : STD_LOGIC;
    signal select_ln51_fu_891_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_reg_1522 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal select_ln51_8_fu_905_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_8_reg_1527 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_9_fu_919_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_9_reg_1532 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_10_fu_933_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_10_reg_1537 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_11_fu_947_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_11_reg_1542 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_12_fu_961_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_12_reg_1547 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_13_fu_975_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_13_reg_1552 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_14_fu_989_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_14_reg_1557 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_15_fu_1003_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_15_reg_1562 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_16_fu_1017_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_16_reg_1567 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_17_fu_1031_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_17_reg_1572 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_18_fu_1045_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_18_reg_1577 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_19_fu_1059_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_19_reg_1582 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_20_fu_1073_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_20_reg_1587 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_21_fu_1087_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_21_reg_1592 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_22_fu_1101_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_22_reg_1597 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_23_fu_1115_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_23_reg_1602 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_24_fu_1129_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_24_reg_1607 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_25_fu_1143_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_25_reg_1612 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_26_fu_1157_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_26_reg_1617 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_27_fu_1171_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_27_reg_1622 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_28_fu_1185_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_28_reg_1627 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_29_fu_1199_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_29_reg_1632 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_30_fu_1213_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_30_reg_1637 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_31_fu_1227_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_31_reg_1642 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_32_fu_1241_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_32_reg_1647 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_33_fu_1255_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_33_reg_1652 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_34_fu_1269_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_34_reg_1657 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_35_fu_1283_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_35_reg_1662 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_36_fu_1297_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_36_reg_1667 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_37_fu_1311_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_37_reg_1672 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_38_fu_1325_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln51_38_reg_1677 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_232 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal i_5_fu_1333_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal trunc_ln44_fu_257_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_fu_885_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_69_fu_261_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_8_fu_265_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_8_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_s_fu_275_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_9_fu_285_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_9_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_39_fu_295_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_10_fu_305_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_10_fu_927_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_40_fu_315_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_11_fu_325_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_11_fu_941_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_41_fu_335_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_12_fu_345_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_12_fu_955_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_42_fu_355_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_13_fu_365_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_13_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_43_fu_375_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_14_fu_385_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_14_fu_983_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_44_fu_395_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_15_fu_405_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_15_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_45_fu_415_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_16_fu_425_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_16_fu_1011_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_46_fu_435_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_17_fu_445_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_17_fu_1025_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_47_fu_455_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_18_fu_465_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_18_fu_1039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_48_fu_475_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_19_fu_485_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_19_fu_1053_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_49_fu_495_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_20_fu_505_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_20_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_50_fu_515_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_21_fu_525_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_21_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_51_fu_535_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_22_fu_545_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_22_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_52_fu_555_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_23_fu_565_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_23_fu_1109_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_53_fu_575_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_24_fu_585_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_24_fu_1123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_54_fu_595_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_25_fu_605_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_25_fu_1137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_55_fu_615_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_26_fu_625_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_26_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_56_fu_635_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_27_fu_645_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_27_fu_1165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_57_fu_655_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_28_fu_665_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_28_fu_1179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_58_fu_675_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_29_fu_685_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_29_fu_1193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_59_fu_695_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_30_fu_705_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_30_fu_1207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_60_fu_715_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_31_fu_725_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_31_fu_1221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_61_fu_735_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_32_fu_745_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_32_fu_1235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_62_fu_755_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_33_fu_765_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_33_fu_1249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_63_fu_775_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_34_fu_785_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_34_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_64_fu_795_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_35_fu_805_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_35_fu_1277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_65_fu_815_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_36_fu_825_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_36_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_66_fu_835_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_37_fu_845_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_37_fu_1305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln44_67_fu_855_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln44_38_fu_865_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln51_38_fu_1319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln2_fu_875_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln51_36_fu_1440_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_35_fu_1437_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_34_fu_1434_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_33_fu_1431_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_32_fu_1428_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_31_fu_1425_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_30_fu_1422_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_29_fu_1419_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_28_fu_1416_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_27_fu_1413_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_26_fu_1410_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_25_fu_1407_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_24_fu_1404_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_23_fu_1401_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_22_fu_1398_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_21_fu_1395_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_20_fu_1392_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_19_fu_1389_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_18_fu_1386_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_17_fu_1383_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_16_fu_1380_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_15_fu_1377_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_14_fu_1374_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_13_fu_1371_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_12_fu_1368_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_11_fu_1365_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_10_fu_1362_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_9_fu_1359_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_8_fu_1356_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_7_fu_1353_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln51_fu_1350_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln57_s_fu_1443_p33 : STD_LOGIC_VECTOR (350 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_177 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_axis_wrapper_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component cifar10_axis_wrapper_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    i_fu_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_177)) then
                i_fu_232 <= i_5_fu_1333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln51_10_reg_1537 <= select_ln51_10_fu_933_p3;
                select_ln51_11_reg_1542 <= select_ln51_11_fu_947_p3;
                select_ln51_12_reg_1547 <= select_ln51_12_fu_961_p3;
                select_ln51_13_reg_1552 <= select_ln51_13_fu_975_p3;
                select_ln51_14_reg_1557 <= select_ln51_14_fu_989_p3;
                select_ln51_15_reg_1562 <= select_ln51_15_fu_1003_p3;
                select_ln51_16_reg_1567 <= select_ln51_16_fu_1017_p3;
                select_ln51_17_reg_1572 <= select_ln51_17_fu_1031_p3;
                select_ln51_18_reg_1577 <= select_ln51_18_fu_1045_p3;
                select_ln51_19_reg_1582 <= select_ln51_19_fu_1059_p3;
                select_ln51_20_reg_1587 <= select_ln51_20_fu_1073_p3;
                select_ln51_21_reg_1592 <= select_ln51_21_fu_1087_p3;
                select_ln51_22_reg_1597 <= select_ln51_22_fu_1101_p3;
                select_ln51_23_reg_1602 <= select_ln51_23_fu_1115_p3;
                select_ln51_24_reg_1607 <= select_ln51_24_fu_1129_p3;
                select_ln51_25_reg_1612 <= select_ln51_25_fu_1143_p3;
                select_ln51_26_reg_1617 <= select_ln51_26_fu_1157_p3;
                select_ln51_27_reg_1622 <= select_ln51_27_fu_1171_p3;
                select_ln51_28_reg_1627 <= select_ln51_28_fu_1185_p3;
                select_ln51_29_reg_1632 <= select_ln51_29_fu_1199_p3;
                select_ln51_30_reg_1637 <= select_ln51_30_fu_1213_p3;
                select_ln51_31_reg_1642 <= select_ln51_31_fu_1227_p3;
                select_ln51_32_reg_1647 <= select_ln51_32_fu_1241_p3;
                select_ln51_33_reg_1652 <= select_ln51_33_fu_1255_p3;
                select_ln51_34_reg_1657 <= select_ln51_34_fu_1269_p3;
                select_ln51_35_reg_1662 <= select_ln51_35_fu_1283_p3;
                select_ln51_36_reg_1667 <= select_ln51_36_fu_1297_p3;
                select_ln51_37_reg_1672 <= select_ln51_37_fu_1311_p3;
                select_ln51_38_reg_1677 <= select_ln51_38_fu_1325_p3;
                select_ln51_8_reg_1527 <= select_ln51_8_fu_905_p3;
                select_ln51_9_reg_1532 <= select_ln51_9_fu_919_p3;
                select_ln51_reg_1522 <= select_ln51_fu_891_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, layer9_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer9_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, layer9_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((layer9_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, layer9_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((layer9_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, layer9_out_full_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((layer9_out_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and ((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0_grp1))));
    end process;


    ap_block_state1_pp0_stage0_iter0_grp1_assign_proc : process(layer8_out_empty_n, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0_grp1 <= ((ap_done_reg = ap_const_logic_1) or (layer8_out_empty_n = ap_const_logic_0));
    end process;


    ap_condition_177_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_177 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_1339_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_1339_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_4_assign_proc : process(ap_CS_fsm_pp0_stage0, i_fu_232, ap_loop_init, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_4 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_4 <= i_fu_232;
        end if; 
    end process;

    i_5_fu_1333_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_4) + unsigned(ap_const_lv4_1));
    icmp_ln41_fu_1339_p2 <= "1" when (ap_sig_allocacmp_i_4 = ap_const_lv4_F) else "0";
    icmp_ln51_10_fu_927_p2 <= "1" when (signed(trunc_ln44_10_fu_305_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_11_fu_941_p2 <= "1" when (signed(trunc_ln44_11_fu_325_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_12_fu_955_p2 <= "1" when (signed(trunc_ln44_12_fu_345_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_13_fu_969_p2 <= "1" when (signed(trunc_ln44_13_fu_365_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_14_fu_983_p2 <= "1" when (signed(trunc_ln44_14_fu_385_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_15_fu_997_p2 <= "1" when (signed(trunc_ln44_15_fu_405_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_16_fu_1011_p2 <= "1" when (signed(trunc_ln44_16_fu_425_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_17_fu_1025_p2 <= "1" when (signed(trunc_ln44_17_fu_445_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_18_fu_1039_p2 <= "1" when (signed(trunc_ln44_18_fu_465_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_19_fu_1053_p2 <= "1" when (signed(trunc_ln44_19_fu_485_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_20_fu_1067_p2 <= "1" when (signed(trunc_ln44_20_fu_505_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_21_fu_1081_p2 <= "1" when (signed(trunc_ln44_21_fu_525_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_22_fu_1095_p2 <= "1" when (signed(trunc_ln44_22_fu_545_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_23_fu_1109_p2 <= "1" when (signed(trunc_ln44_23_fu_565_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_24_fu_1123_p2 <= "1" when (signed(trunc_ln44_24_fu_585_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_25_fu_1137_p2 <= "1" when (signed(trunc_ln44_25_fu_605_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_26_fu_1151_p2 <= "1" when (signed(trunc_ln44_26_fu_625_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_27_fu_1165_p2 <= "1" when (signed(trunc_ln44_27_fu_645_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_28_fu_1179_p2 <= "1" when (signed(trunc_ln44_28_fu_665_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_29_fu_1193_p2 <= "1" when (signed(trunc_ln44_29_fu_685_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_30_fu_1207_p2 <= "1" when (signed(trunc_ln44_30_fu_705_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_31_fu_1221_p2 <= "1" when (signed(trunc_ln44_31_fu_725_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_32_fu_1235_p2 <= "1" when (signed(trunc_ln44_32_fu_745_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_33_fu_1249_p2 <= "1" when (signed(trunc_ln44_33_fu_765_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_34_fu_1263_p2 <= "1" when (signed(trunc_ln44_34_fu_785_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_35_fu_1277_p2 <= "1" when (signed(trunc_ln44_35_fu_805_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_36_fu_1291_p2 <= "1" when (signed(trunc_ln44_36_fu_825_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_37_fu_1305_p2 <= "1" when (signed(trunc_ln44_37_fu_845_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_38_fu_1319_p2 <= "1" when (signed(trunc_ln44_38_fu_865_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_8_fu_899_p2 <= "1" when (signed(trunc_ln44_8_fu_265_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_9_fu_913_p2 <= "1" when (signed(trunc_ln44_9_fu_285_p4) > signed(ap_const_lv11_0)) else "0";
    icmp_ln51_fu_885_p2 <= "1" when (signed(trunc_ln44_fu_257_p1) > signed(ap_const_lv11_0)) else "0";

    layer8_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, layer8_out_empty_n, ap_done_reg, ap_block_pp0_stage0_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_done_reg = ap_const_logic_0) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer8_out_blk_n <= layer8_out_empty_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer8_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_grp1, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer8_out_read <= ap_const_logic_1;
        else 
            layer8_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer9_out_full_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer9_out_blk_n <= layer9_out_full_n;
        else 
            layer9_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer9_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1443_p33),352));

    layer9_out_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer9_out_write <= ap_const_logic_1;
        else 
            layer9_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1443_p33 <= (((((((((((((((((((((((((((((((select_ln51_38_reg_1677 & zext_ln51_36_fu_1440_p1) & zext_ln51_35_fu_1437_p1) & zext_ln51_34_fu_1434_p1) & zext_ln51_33_fu_1431_p1) & zext_ln51_32_fu_1428_p1) & zext_ln51_31_fu_1425_p1) & zext_ln51_30_fu_1422_p1) & zext_ln51_29_fu_1419_p1) & zext_ln51_28_fu_1416_p1) & zext_ln51_27_fu_1413_p1) & zext_ln51_26_fu_1410_p1) & zext_ln51_25_fu_1407_p1) & zext_ln51_24_fu_1404_p1) & zext_ln51_23_fu_1401_p1) & zext_ln51_22_fu_1398_p1) & zext_ln51_21_fu_1395_p1) & zext_ln51_20_fu_1392_p1) & zext_ln51_19_fu_1389_p1) & zext_ln51_18_fu_1386_p1) & zext_ln51_17_fu_1383_p1) & zext_ln51_16_fu_1380_p1) & zext_ln51_15_fu_1377_p1) & zext_ln51_14_fu_1374_p1) & zext_ln51_13_fu_1371_p1) & zext_ln51_12_fu_1368_p1) & zext_ln51_11_fu_1365_p1) & zext_ln51_10_fu_1362_p1) & zext_ln51_9_fu_1359_p1) & zext_ln51_8_fu_1356_p1) & zext_ln51_7_fu_1353_p1) & zext_ln51_fu_1350_p1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_10_fu_933_p3 <= 
        trunc_ln44_40_fu_315_p4 when (icmp_ln51_10_fu_927_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_11_fu_947_p3 <= 
        trunc_ln44_41_fu_335_p4 when (icmp_ln51_11_fu_941_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_12_fu_961_p3 <= 
        trunc_ln44_42_fu_355_p4 when (icmp_ln51_12_fu_955_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_13_fu_975_p3 <= 
        trunc_ln44_43_fu_375_p4 when (icmp_ln51_13_fu_969_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_14_fu_989_p3 <= 
        trunc_ln44_44_fu_395_p4 when (icmp_ln51_14_fu_983_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_15_fu_1003_p3 <= 
        trunc_ln44_45_fu_415_p4 when (icmp_ln51_15_fu_997_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_16_fu_1017_p3 <= 
        trunc_ln44_46_fu_435_p4 when (icmp_ln51_16_fu_1011_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_17_fu_1031_p3 <= 
        trunc_ln44_47_fu_455_p4 when (icmp_ln51_17_fu_1025_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_18_fu_1045_p3 <= 
        trunc_ln44_48_fu_475_p4 when (icmp_ln51_18_fu_1039_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_19_fu_1059_p3 <= 
        trunc_ln44_49_fu_495_p4 when (icmp_ln51_19_fu_1053_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_20_fu_1073_p3 <= 
        trunc_ln44_50_fu_515_p4 when (icmp_ln51_20_fu_1067_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_21_fu_1087_p3 <= 
        trunc_ln44_51_fu_535_p4 when (icmp_ln51_21_fu_1081_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_22_fu_1101_p3 <= 
        trunc_ln44_52_fu_555_p4 when (icmp_ln51_22_fu_1095_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_23_fu_1115_p3 <= 
        trunc_ln44_53_fu_575_p4 when (icmp_ln51_23_fu_1109_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_24_fu_1129_p3 <= 
        trunc_ln44_54_fu_595_p4 when (icmp_ln51_24_fu_1123_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_25_fu_1143_p3 <= 
        trunc_ln44_55_fu_615_p4 when (icmp_ln51_25_fu_1137_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_26_fu_1157_p3 <= 
        trunc_ln44_56_fu_635_p4 when (icmp_ln51_26_fu_1151_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_27_fu_1171_p3 <= 
        trunc_ln44_57_fu_655_p4 when (icmp_ln51_27_fu_1165_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_28_fu_1185_p3 <= 
        trunc_ln44_58_fu_675_p4 when (icmp_ln51_28_fu_1179_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_29_fu_1199_p3 <= 
        trunc_ln44_59_fu_695_p4 when (icmp_ln51_29_fu_1193_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_30_fu_1213_p3 <= 
        trunc_ln44_60_fu_715_p4 when (icmp_ln51_30_fu_1207_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_31_fu_1227_p3 <= 
        trunc_ln44_61_fu_735_p4 when (icmp_ln51_31_fu_1221_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_32_fu_1241_p3 <= 
        trunc_ln44_62_fu_755_p4 when (icmp_ln51_32_fu_1235_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_33_fu_1255_p3 <= 
        trunc_ln44_63_fu_775_p4 when (icmp_ln51_33_fu_1249_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_34_fu_1269_p3 <= 
        trunc_ln44_64_fu_795_p4 when (icmp_ln51_34_fu_1263_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_35_fu_1283_p3 <= 
        trunc_ln44_65_fu_815_p4 when (icmp_ln51_35_fu_1277_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_36_fu_1297_p3 <= 
        trunc_ln44_66_fu_835_p4 when (icmp_ln51_36_fu_1291_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_37_fu_1311_p3 <= 
        trunc_ln44_67_fu_855_p4 when (icmp_ln51_37_fu_1305_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_38_fu_1325_p3 <= 
        trunc_ln2_fu_875_p4 when (icmp_ln51_38_fu_1319_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_8_fu_905_p3 <= 
        trunc_ln44_s_fu_275_p4 when (icmp_ln51_8_fu_899_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_9_fu_919_p3 <= 
        trunc_ln44_39_fu_295_p4 when (icmp_ln51_9_fu_913_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln51_fu_891_p3 <= 
        trunc_ln44_69_fu_261_p1 when (icmp_ln51_fu_885_p2(0) = '1') else 
        ap_const_lv10_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln2_fu_875_p4 <= layer8_out_dout(350 downto 341);
    trunc_ln44_10_fu_305_p4 <= layer8_out_dout(43 downto 33);
    trunc_ln44_11_fu_325_p4 <= layer8_out_dout(54 downto 44);
    trunc_ln44_12_fu_345_p4 <= layer8_out_dout(65 downto 55);
    trunc_ln44_13_fu_365_p4 <= layer8_out_dout(76 downto 66);
    trunc_ln44_14_fu_385_p4 <= layer8_out_dout(87 downto 77);
    trunc_ln44_15_fu_405_p4 <= layer8_out_dout(98 downto 88);
    trunc_ln44_16_fu_425_p4 <= layer8_out_dout(109 downto 99);
    trunc_ln44_17_fu_445_p4 <= layer8_out_dout(120 downto 110);
    trunc_ln44_18_fu_465_p4 <= layer8_out_dout(131 downto 121);
    trunc_ln44_19_fu_485_p4 <= layer8_out_dout(142 downto 132);
    trunc_ln44_20_fu_505_p4 <= layer8_out_dout(153 downto 143);
    trunc_ln44_21_fu_525_p4 <= layer8_out_dout(164 downto 154);
    trunc_ln44_22_fu_545_p4 <= layer8_out_dout(175 downto 165);
    trunc_ln44_23_fu_565_p4 <= layer8_out_dout(186 downto 176);
    trunc_ln44_24_fu_585_p4 <= layer8_out_dout(197 downto 187);
    trunc_ln44_25_fu_605_p4 <= layer8_out_dout(208 downto 198);
    trunc_ln44_26_fu_625_p4 <= layer8_out_dout(219 downto 209);
    trunc_ln44_27_fu_645_p4 <= layer8_out_dout(230 downto 220);
    trunc_ln44_28_fu_665_p4 <= layer8_out_dout(241 downto 231);
    trunc_ln44_29_fu_685_p4 <= layer8_out_dout(252 downto 242);
    trunc_ln44_30_fu_705_p4 <= layer8_out_dout(263 downto 253);
    trunc_ln44_31_fu_725_p4 <= layer8_out_dout(274 downto 264);
    trunc_ln44_32_fu_745_p4 <= layer8_out_dout(285 downto 275);
    trunc_ln44_33_fu_765_p4 <= layer8_out_dout(296 downto 286);
    trunc_ln44_34_fu_785_p4 <= layer8_out_dout(307 downto 297);
    trunc_ln44_35_fu_805_p4 <= layer8_out_dout(318 downto 308);
    trunc_ln44_36_fu_825_p4 <= layer8_out_dout(329 downto 319);
    trunc_ln44_37_fu_845_p4 <= layer8_out_dout(340 downto 330);
    trunc_ln44_38_fu_865_p4 <= layer8_out_dout(351 downto 341);
    trunc_ln44_39_fu_295_p4 <= layer8_out_dout(31 downto 22);
    trunc_ln44_40_fu_315_p4 <= layer8_out_dout(42 downto 33);
    trunc_ln44_41_fu_335_p4 <= layer8_out_dout(53 downto 44);
    trunc_ln44_42_fu_355_p4 <= layer8_out_dout(64 downto 55);
    trunc_ln44_43_fu_375_p4 <= layer8_out_dout(75 downto 66);
    trunc_ln44_44_fu_395_p4 <= layer8_out_dout(86 downto 77);
    trunc_ln44_45_fu_415_p4 <= layer8_out_dout(97 downto 88);
    trunc_ln44_46_fu_435_p4 <= layer8_out_dout(108 downto 99);
    trunc_ln44_47_fu_455_p4 <= layer8_out_dout(119 downto 110);
    trunc_ln44_48_fu_475_p4 <= layer8_out_dout(130 downto 121);
    trunc_ln44_49_fu_495_p4 <= layer8_out_dout(141 downto 132);
    trunc_ln44_50_fu_515_p4 <= layer8_out_dout(152 downto 143);
    trunc_ln44_51_fu_535_p4 <= layer8_out_dout(163 downto 154);
    trunc_ln44_52_fu_555_p4 <= layer8_out_dout(174 downto 165);
    trunc_ln44_53_fu_575_p4 <= layer8_out_dout(185 downto 176);
    trunc_ln44_54_fu_595_p4 <= layer8_out_dout(196 downto 187);
    trunc_ln44_55_fu_615_p4 <= layer8_out_dout(207 downto 198);
    trunc_ln44_56_fu_635_p4 <= layer8_out_dout(218 downto 209);
    trunc_ln44_57_fu_655_p4 <= layer8_out_dout(229 downto 220);
    trunc_ln44_58_fu_675_p4 <= layer8_out_dout(240 downto 231);
    trunc_ln44_59_fu_695_p4 <= layer8_out_dout(251 downto 242);
    trunc_ln44_60_fu_715_p4 <= layer8_out_dout(262 downto 253);
    trunc_ln44_61_fu_735_p4 <= layer8_out_dout(273 downto 264);
    trunc_ln44_62_fu_755_p4 <= layer8_out_dout(284 downto 275);
    trunc_ln44_63_fu_775_p4 <= layer8_out_dout(295 downto 286);
    trunc_ln44_64_fu_795_p4 <= layer8_out_dout(306 downto 297);
    trunc_ln44_65_fu_815_p4 <= layer8_out_dout(317 downto 308);
    trunc_ln44_66_fu_835_p4 <= layer8_out_dout(328 downto 319);
    trunc_ln44_67_fu_855_p4 <= layer8_out_dout(339 downto 330);
    trunc_ln44_69_fu_261_p1 <= layer8_out_dout(10 - 1 downto 0);
    trunc_ln44_8_fu_265_p4 <= layer8_out_dout(21 downto 11);
    trunc_ln44_9_fu_285_p4 <= layer8_out_dout(32 downto 22);
    trunc_ln44_fu_257_p1 <= layer8_out_dout(11 - 1 downto 0);
    trunc_ln44_s_fu_275_p4 <= layer8_out_dout(20 downto 11);
    zext_ln51_10_fu_1362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_11_reg_1542),11));
    zext_ln51_11_fu_1365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_12_reg_1547),11));
    zext_ln51_12_fu_1368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_13_reg_1552),11));
    zext_ln51_13_fu_1371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_14_reg_1557),11));
    zext_ln51_14_fu_1374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_15_reg_1562),11));
    zext_ln51_15_fu_1377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_16_reg_1567),11));
    zext_ln51_16_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_17_reg_1572),11));
    zext_ln51_17_fu_1383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_18_reg_1577),11));
    zext_ln51_18_fu_1386_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_19_reg_1582),11));
    zext_ln51_19_fu_1389_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_20_reg_1587),11));
    zext_ln51_20_fu_1392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_21_reg_1592),11));
    zext_ln51_21_fu_1395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_22_reg_1597),11));
    zext_ln51_22_fu_1398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_23_reg_1602),11));
    zext_ln51_23_fu_1401_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_24_reg_1607),11));
    zext_ln51_24_fu_1404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_25_reg_1612),11));
    zext_ln51_25_fu_1407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_26_reg_1617),11));
    zext_ln51_26_fu_1410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_27_reg_1622),11));
    zext_ln51_27_fu_1413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_28_reg_1627),11));
    zext_ln51_28_fu_1416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_29_reg_1632),11));
    zext_ln51_29_fu_1419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_30_reg_1637),11));
    zext_ln51_30_fu_1422_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_31_reg_1642),11));
    zext_ln51_31_fu_1425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_32_reg_1647),11));
    zext_ln51_32_fu_1428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_33_reg_1652),11));
    zext_ln51_33_fu_1431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_34_reg_1657),11));
    zext_ln51_34_fu_1434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_35_reg_1662),11));
    zext_ln51_35_fu_1437_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_36_reg_1667),11));
    zext_ln51_36_fu_1440_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_37_reg_1672),11));
    zext_ln51_7_fu_1353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_8_reg_1527),11));
    zext_ln51_8_fu_1356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_9_reg_1532),11));
    zext_ln51_9_fu_1359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_10_reg_1537),11));
    zext_ln51_fu_1350_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_reg_1522),11));
end behav;
