-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_axis_wrapper is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axis_TVALID : IN STD_LOGIC;
    s_axis_TREADY : OUT STD_LOGIC;
    m_axis_TVALID : OUT STD_LOGIC;
    m_axis_TREADY : IN STD_LOGIC );
end;


architecture behav of cifar10_axis_wrapper is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cifar10_axis_wrapper_cifar10_axis_wrapper,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=13.990063,HLS_SYN_LAT=232259,HLS_SYN_TPT=78850,HLS_SYN_MEM=120,HLS_SYN_DSP=0,HLS_SYN_FF=23661,HLS_SYN_LUT=36418,HLS_VERSION=2025_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_ap_start : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_ap_done : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_ap_continue : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_ap_idle : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_ap_ready : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_nn_in_din : STD_LOGIC_VECTOR (26 downto 0);
    signal axis_to_hls4ml_input_U0_nn_in_write : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_nn_in_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_to_hls4ml_input_U0_nn_in_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal axis_to_hls4ml_input_U0_start_out : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_start_write : STD_LOGIC;
    signal axis_to_hls4ml_input_U0_s_axis_TREADY : STD_LOGIC;
    signal cifar10_hls_core_U0_ap_start : STD_LOGIC;
    signal cifar10_hls_core_U0_start_out : STD_LOGIC;
    signal cifar10_hls_core_U0_start_write : STD_LOGIC;
    signal cifar10_hls_core_U0_nn_in_read : STD_LOGIC;
    signal cifar10_hls_core_U0_nn_out_din : STD_LOGIC_VECTOR (119 downto 0);
    signal cifar10_hls_core_U0_nn_out_write : STD_LOGIC;
    signal cifar10_hls_core_U0_ap_done : STD_LOGIC;
    signal cifar10_hls_core_U0_ap_ready : STD_LOGIC;
    signal cifar10_hls_core_U0_ap_idle : STD_LOGIC;
    signal cifar10_hls_core_U0_ap_continue : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_ap_start : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_ap_done : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_ap_continue : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_ap_idle : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_ap_ready : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_nn_out_read : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_m_axis_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal hls4ml_output_to_axis_U0_m_axis_TVALID : STD_LOGIC;
    signal hls4ml_output_to_axis_U0_m_axis_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal hls4ml_output_to_axis_U0_m_axis_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal hls4ml_output_to_axis_U0_m_axis_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal nn_in_full_n : STD_LOGIC;
    signal nn_in_dout : STD_LOGIC_VECTOR (26 downto 0);
    signal nn_in_empty_n : STD_LOGIC;
    signal nn_in_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal nn_in_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal nn_out_full_n : STD_LOGIC;
    signal nn_out_dout : STD_LOGIC_VECTOR (119 downto 0);
    signal nn_out_empty_n : STD_LOGIC;
    signal nn_out_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal nn_out_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal start_for_cifar10_hls_core_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_cifar10_hls_core_U0_full_n : STD_LOGIC;
    signal start_for_cifar10_hls_core_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_cifar10_hls_core_U0_empty_n : STD_LOGIC;
    signal start_for_hls4ml_output_to_axis_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_hls4ml_output_to_axis_U0_full_n : STD_LOGIC;
    signal start_for_hls4ml_output_to_axis_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_hls4ml_output_to_axis_U0_empty_n : STD_LOGIC;

    component cifar10_axis_wrapper_axis_to_hls4ml_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s_axis_TVALID : IN STD_LOGIC;
        nn_in_din : OUT STD_LOGIC_VECTOR (26 downto 0);
        nn_in_full_n : IN STD_LOGIC;
        nn_in_write : OUT STD_LOGIC;
        nn_in_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        nn_in_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        s_axis_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        s_axis_TREADY : OUT STD_LOGIC;
        s_axis_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        s_axis_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cifar10_axis_wrapper_cifar10_hls_core IS
    port (
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        nn_in_dout : IN STD_LOGIC_VECTOR (26 downto 0);
        nn_in_empty_n : IN STD_LOGIC;
        nn_in_read : OUT STD_LOGIC;
        nn_out_din : OUT STD_LOGIC_VECTOR (119 downto 0);
        nn_out_full_n : IN STD_LOGIC;
        nn_out_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component cifar10_axis_wrapper_hls4ml_output_to_axis IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        nn_out_dout : IN STD_LOGIC_VECTOR (119 downto 0);
        nn_out_empty_n : IN STD_LOGIC;
        nn_out_read : OUT STD_LOGIC;
        nn_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        nn_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axis_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axis_TVALID : OUT STD_LOGIC;
        m_axis_TREADY : IN STD_LOGIC;
        m_axis_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axis_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cifar10_axis_wrapper_fifo_w27_d16_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (26 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (26 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component cifar10_axis_wrapper_fifo_w120_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (119 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (119 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component cifar10_axis_wrapper_start_for_cifar10_hls_core_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component cifar10_axis_wrapper_start_for_hls4ml_output_to_axis_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component cifar10_axis_wrapper_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component cifar10_axis_wrapper_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    axis_to_hls4ml_input_U0 : component cifar10_axis_wrapper_axis_to_hls4ml_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => axis_to_hls4ml_input_U0_ap_start,
        start_full_n => start_for_cifar10_hls_core_U0_full_n,
        ap_done => axis_to_hls4ml_input_U0_ap_done,
        ap_continue => axis_to_hls4ml_input_U0_ap_continue,
        ap_idle => axis_to_hls4ml_input_U0_ap_idle,
        ap_ready => axis_to_hls4ml_input_U0_ap_ready,
        s_axis_TVALID => s_axis_TVALID,
        nn_in_din => axis_to_hls4ml_input_U0_nn_in_din,
        nn_in_full_n => nn_in_full_n,
        nn_in_write => axis_to_hls4ml_input_U0_nn_in_write,
        nn_in_num_data_valid => axis_to_hls4ml_input_U0_nn_in_num_data_valid,
        nn_in_fifo_cap => axis_to_hls4ml_input_U0_nn_in_fifo_cap,
        start_out => axis_to_hls4ml_input_U0_start_out,
        start_write => axis_to_hls4ml_input_U0_start_write,
        s_axis_TDATA => s_axis_TDATA,
        s_axis_TREADY => axis_to_hls4ml_input_U0_s_axis_TREADY,
        s_axis_TKEEP => s_axis_TKEEP,
        s_axis_TSTRB => s_axis_TSTRB,
        s_axis_TLAST => s_axis_TLAST);

    cifar10_hls_core_U0 : component cifar10_axis_wrapper_cifar10_hls_core
    port map (
        ap_start => cifar10_hls_core_U0_ap_start,
        start_full_n => start_for_hls4ml_output_to_axis_U0_full_n,
        start_out => cifar10_hls_core_U0_start_out,
        start_write => cifar10_hls_core_U0_start_write,
        nn_in_dout => nn_in_dout,
        nn_in_empty_n => nn_in_empty_n,
        nn_in_read => cifar10_hls_core_U0_nn_in_read,
        nn_out_din => cifar10_hls_core_U0_nn_out_din,
        nn_out_full_n => nn_out_full_n,
        nn_out_write => cifar10_hls_core_U0_nn_out_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_done => cifar10_hls_core_U0_ap_done,
        ap_ready => cifar10_hls_core_U0_ap_ready,
        ap_idle => cifar10_hls_core_U0_ap_idle,
        ap_continue => cifar10_hls_core_U0_ap_continue);

    hls4ml_output_to_axis_U0 : component cifar10_axis_wrapper_hls4ml_output_to_axis
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => hls4ml_output_to_axis_U0_ap_start,
        ap_done => hls4ml_output_to_axis_U0_ap_done,
        ap_continue => hls4ml_output_to_axis_U0_ap_continue,
        ap_idle => hls4ml_output_to_axis_U0_ap_idle,
        ap_ready => hls4ml_output_to_axis_U0_ap_ready,
        nn_out_dout => nn_out_dout,
        nn_out_empty_n => nn_out_empty_n,
        nn_out_read => hls4ml_output_to_axis_U0_nn_out_read,
        nn_out_num_data_valid => nn_out_num_data_valid,
        nn_out_fifo_cap => nn_out_fifo_cap,
        m_axis_TDATA => hls4ml_output_to_axis_U0_m_axis_TDATA,
        m_axis_TVALID => hls4ml_output_to_axis_U0_m_axis_TVALID,
        m_axis_TREADY => m_axis_TREADY,
        m_axis_TKEEP => hls4ml_output_to_axis_U0_m_axis_TKEEP,
        m_axis_TSTRB => hls4ml_output_to_axis_U0_m_axis_TSTRB,
        m_axis_TLAST => hls4ml_output_to_axis_U0_m_axis_TLAST);

    nn_in_U : component cifar10_axis_wrapper_fifo_w27_d16_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => axis_to_hls4ml_input_U0_nn_in_din,
        if_full_n => nn_in_full_n,
        if_write => axis_to_hls4ml_input_U0_nn_in_write,
        if_dout => nn_in_dout,
        if_empty_n => nn_in_empty_n,
        if_read => cifar10_hls_core_U0_nn_in_read,
        if_num_data_valid => nn_in_num_data_valid,
        if_fifo_cap => nn_in_fifo_cap);

    nn_out_U : component cifar10_axis_wrapper_fifo_w120_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => cifar10_hls_core_U0_nn_out_din,
        if_full_n => nn_out_full_n,
        if_write => cifar10_hls_core_U0_nn_out_write,
        if_dout => nn_out_dout,
        if_empty_n => nn_out_empty_n,
        if_read => hls4ml_output_to_axis_U0_nn_out_read,
        if_num_data_valid => nn_out_num_data_valid,
        if_fifo_cap => nn_out_fifo_cap);

    start_for_cifar10_hls_core_U0_U : component cifar10_axis_wrapper_start_for_cifar10_hls_core_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_cifar10_hls_core_U0_din,
        if_full_n => start_for_cifar10_hls_core_U0_full_n,
        if_write => axis_to_hls4ml_input_U0_start_write,
        if_dout => start_for_cifar10_hls_core_U0_dout,
        if_empty_n => start_for_cifar10_hls_core_U0_empty_n,
        if_read => cifar10_hls_core_U0_ap_ready);

    start_for_hls4ml_output_to_axis_U0_U : component cifar10_axis_wrapper_start_for_hls4ml_output_to_axis_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_hls4ml_output_to_axis_U0_din,
        if_full_n => start_for_hls4ml_output_to_axis_U0_full_n,
        if_write => cifar10_hls_core_U0_start_write,
        if_dout => start_for_hls4ml_output_to_axis_U0_dout,
        if_empty_n => start_for_hls4ml_output_to_axis_U0_empty_n,
        if_read => hls4ml_output_to_axis_U0_ap_ready);




    ap_done <= hls4ml_output_to_axis_U0_ap_done;
    ap_idle <= (hls4ml_output_to_axis_U0_ap_idle and cifar10_hls_core_U0_ap_idle and axis_to_hls4ml_input_U0_ap_idle);
    ap_ready <= axis_to_hls4ml_input_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    axis_to_hls4ml_input_U0_ap_continue <= ap_const_logic_1;
    axis_to_hls4ml_input_U0_ap_start <= ap_start;
    axis_to_hls4ml_input_U0_nn_in_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(nn_in_fifo_cap),5))),32));
    axis_to_hls4ml_input_U0_nn_in_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(nn_in_num_data_valid),5))),32));
    cifar10_hls_core_U0_ap_continue <= ap_const_logic_1;
    cifar10_hls_core_U0_ap_start <= start_for_cifar10_hls_core_U0_empty_n;
    hls4ml_output_to_axis_U0_ap_continue <= ap_const_logic_1;
    hls4ml_output_to_axis_U0_ap_start <= start_for_hls4ml_output_to_axis_U0_empty_n;
    m_axis_TDATA <= hls4ml_output_to_axis_U0_m_axis_TDATA;
    m_axis_TKEEP <= hls4ml_output_to_axis_U0_m_axis_TKEEP;
    m_axis_TLAST <= hls4ml_output_to_axis_U0_m_axis_TLAST;
    m_axis_TSTRB <= hls4ml_output_to_axis_U0_m_axis_TSTRB;
    m_axis_TVALID <= hls4ml_output_to_axis_U0_m_axis_TVALID;
    s_axis_TREADY <= axis_to_hls4ml_input_U0_s_axis_TREADY;
    start_for_cifar10_hls_core_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_hls4ml_output_to_axis_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
