-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult_matrix_mult_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_we0 : OUT STD_LOGIC;
    A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_we0 : OUT STD_LOGIC;
    A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_we0 : OUT STD_LOGIC;
    A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_we0 : OUT STD_LOGIC;
    A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_4_ce0 : OUT STD_LOGIC;
    A_4_we0 : OUT STD_LOGIC;
    A_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_5_ce0 : OUT STD_LOGIC;
    A_5_we0 : OUT STD_LOGIC;
    A_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_6_ce0 : OUT STD_LOGIC;
    A_6_we0 : OUT STD_LOGIC;
    A_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_7_ce0 : OUT STD_LOGIC;
    A_7_we0 : OUT STD_LOGIC;
    A_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_8_ce0 : OUT STD_LOGIC;
    A_8_we0 : OUT STD_LOGIC;
    A_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_9_ce0 : OUT STD_LOGIC;
    A_9_we0 : OUT STD_LOGIC;
    A_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_10_ce0 : OUT STD_LOGIC;
    A_10_we0 : OUT STD_LOGIC;
    A_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_11_ce0 : OUT STD_LOGIC;
    A_11_we0 : OUT STD_LOGIC;
    A_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_12_ce0 : OUT STD_LOGIC;
    A_12_we0 : OUT STD_LOGIC;
    A_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_13_ce0 : OUT STD_LOGIC;
    A_13_we0 : OUT STD_LOGIC;
    A_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_14_ce0 : OUT STD_LOGIC;
    A_14_we0 : OUT STD_LOGIC;
    A_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_15_ce0 : OUT STD_LOGIC;
    A_15_we0 : OUT STD_LOGIC;
    A_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_16_ce0 : OUT STD_LOGIC;
    A_16_we0 : OUT STD_LOGIC;
    A_16_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_17_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_17_ce0 : OUT STD_LOGIC;
    A_17_we0 : OUT STD_LOGIC;
    A_17_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_18_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_18_ce0 : OUT STD_LOGIC;
    A_18_we0 : OUT STD_LOGIC;
    A_18_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_19_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_19_ce0 : OUT STD_LOGIC;
    A_19_we0 : OUT STD_LOGIC;
    A_19_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_20_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_20_ce0 : OUT STD_LOGIC;
    A_20_we0 : OUT STD_LOGIC;
    A_20_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_21_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_21_ce0 : OUT STD_LOGIC;
    A_21_we0 : OUT STD_LOGIC;
    A_21_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_22_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_22_ce0 : OUT STD_LOGIC;
    A_22_we0 : OUT STD_LOGIC;
    A_22_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_23_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_23_ce0 : OUT STD_LOGIC;
    A_23_we0 : OUT STD_LOGIC;
    A_23_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_24_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_24_ce0 : OUT STD_LOGIC;
    A_24_we0 : OUT STD_LOGIC;
    A_24_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_25_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_25_ce0 : OUT STD_LOGIC;
    A_25_we0 : OUT STD_LOGIC;
    A_25_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_26_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_26_ce0 : OUT STD_LOGIC;
    A_26_we0 : OUT STD_LOGIC;
    A_26_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_27_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_27_ce0 : OUT STD_LOGIC;
    A_27_we0 : OUT STD_LOGIC;
    A_27_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_28_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_28_ce0 : OUT STD_LOGIC;
    A_28_we0 : OUT STD_LOGIC;
    A_28_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_29_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_29_ce0 : OUT STD_LOGIC;
    A_29_we0 : OUT STD_LOGIC;
    A_29_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_30_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_30_ce0 : OUT STD_LOGIC;
    A_30_we0 : OUT STD_LOGIC;
    A_30_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    A_31_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_31_ce0 : OUT STD_LOGIC;
    A_31_we0 : OUT STD_LOGIC;
    A_31_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matrix_mult_matrix_mult_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1D : STD_LOGIC_VECTOR (4 downto 0) := "11101";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_1B : STD_LOGIC_VECTOR (4 downto 0) := "11011";
    constant ap_const_lv5_1A : STD_LOGIC_VECTOR (4 downto 0) := "11010";
    constant ap_const_lv5_19 : STD_LOGIC_VECTOR (4 downto 0) := "11001";
    constant ap_const_lv5_18 : STD_LOGIC_VECTOR (4 downto 0) := "11000";
    constant ap_const_lv5_17 : STD_LOGIC_VECTOR (4 downto 0) := "10111";
    constant ap_const_lv5_16 : STD_LOGIC_VECTOR (4 downto 0) := "10110";
    constant ap_const_lv5_15 : STD_LOGIC_VECTOR (4 downto 0) := "10101";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_12 : STD_LOGIC_VECTOR (4 downto 0) := "10010";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_F : STD_LOGIC_VECTOR (4 downto 0) := "01111";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv5_D : STD_LOGIC_VECTOR (4 downto 0) := "01101";
    constant ap_const_lv5_C : STD_LOGIC_VECTOR (4 downto 0) := "01100";
    constant ap_const_lv5_B : STD_LOGIC_VECTOR (4 downto 0) := "01011";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv5_9 : STD_LOGIC_VECTOR (4 downto 0) := "01001";
    constant ap_const_lv5_8 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_const_lv5_7 : STD_LOGIC_VECTOR (4 downto 0) := "00111";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";
    constant ap_const_lv5_2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln23_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln24_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln24_reg_881 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal trunc_ln24_fu_682_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln24_reg_886 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln23_fu_779_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_184 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln24_fu_752_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_188 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln23_1_fu_772_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten_fu_192 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln23_1_fu_654_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal A_30_we0_local : STD_LOGIC;
    signal A_30_ce0_local : STD_LOGIC;
    signal A_29_we0_local : STD_LOGIC;
    signal A_29_ce0_local : STD_LOGIC;
    signal A_28_we0_local : STD_LOGIC;
    signal A_28_ce0_local : STD_LOGIC;
    signal A_27_we0_local : STD_LOGIC;
    signal A_27_ce0_local : STD_LOGIC;
    signal A_26_we0_local : STD_LOGIC;
    signal A_26_ce0_local : STD_LOGIC;
    signal A_25_we0_local : STD_LOGIC;
    signal A_25_ce0_local : STD_LOGIC;
    signal A_24_we0_local : STD_LOGIC;
    signal A_24_ce0_local : STD_LOGIC;
    signal A_23_we0_local : STD_LOGIC;
    signal A_23_ce0_local : STD_LOGIC;
    signal A_22_we0_local : STD_LOGIC;
    signal A_22_ce0_local : STD_LOGIC;
    signal A_21_we0_local : STD_LOGIC;
    signal A_21_ce0_local : STD_LOGIC;
    signal A_20_we0_local : STD_LOGIC;
    signal A_20_ce0_local : STD_LOGIC;
    signal A_19_we0_local : STD_LOGIC;
    signal A_19_ce0_local : STD_LOGIC;
    signal A_18_we0_local : STD_LOGIC;
    signal A_18_ce0_local : STD_LOGIC;
    signal A_17_we0_local : STD_LOGIC;
    signal A_17_ce0_local : STD_LOGIC;
    signal A_16_we0_local : STD_LOGIC;
    signal A_16_ce0_local : STD_LOGIC;
    signal A_15_we0_local : STD_LOGIC;
    signal A_15_ce0_local : STD_LOGIC;
    signal A_14_we0_local : STD_LOGIC;
    signal A_14_ce0_local : STD_LOGIC;
    signal A_13_we0_local : STD_LOGIC;
    signal A_13_ce0_local : STD_LOGIC;
    signal A_12_we0_local : STD_LOGIC;
    signal A_12_ce0_local : STD_LOGIC;
    signal A_11_we0_local : STD_LOGIC;
    signal A_11_ce0_local : STD_LOGIC;
    signal A_10_we0_local : STD_LOGIC;
    signal A_10_ce0_local : STD_LOGIC;
    signal A_9_we0_local : STD_LOGIC;
    signal A_9_ce0_local : STD_LOGIC;
    signal A_8_we0_local : STD_LOGIC;
    signal A_8_ce0_local : STD_LOGIC;
    signal A_7_we0_local : STD_LOGIC;
    signal A_7_ce0_local : STD_LOGIC;
    signal A_6_we0_local : STD_LOGIC;
    signal A_6_ce0_local : STD_LOGIC;
    signal A_5_we0_local : STD_LOGIC;
    signal A_5_ce0_local : STD_LOGIC;
    signal A_4_we0_local : STD_LOGIC;
    signal A_4_ce0_local : STD_LOGIC;
    signal A_3_we0_local : STD_LOGIC;
    signal A_3_ce0_local : STD_LOGIC;
    signal A_2_we0_local : STD_LOGIC;
    signal A_2_ce0_local : STD_LOGIC;
    signal A_1_we0_local : STD_LOGIC;
    signal A_1_ce0_local : STD_LOGIC;
    signal A_we0_local : STD_LOGIC;
    signal A_ce0_local : STD_LOGIC;
    signal A_31_we0_local : STD_LOGIC;
    signal A_31_ce0_local : STD_LOGIC;
    signal select_ln23_fu_674_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln23_fu_766_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component matrix_mult_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_188_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    i_fu_188 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    i_fu_188 <= select_ln23_1_fu_772_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln23_fu_648_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_192 <= add_ln23_1_fu_654_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_192 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_184 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_184 <= add_ln24_fu_752_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln24_reg_881 <= icmp_ln24_fu_668_p2;
                trunc_ln24_reg_886 <= trunc_ln24_fu_682_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    A_10_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_10_ce0 <= A_10_ce0_local;

    A_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_10_ce0_local <= ap_const_logic_1;
        else 
            A_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_10_d0 <= in_stream_TDATA;
    A_10_we0 <= A_10_we0_local;

    A_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_10_we0_local <= ap_const_logic_1;
        else 
            A_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_11_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_11_ce0 <= A_11_ce0_local;

    A_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_11_ce0_local <= ap_const_logic_1;
        else 
            A_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_11_d0 <= in_stream_TDATA;
    A_11_we0 <= A_11_we0_local;

    A_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_11_we0_local <= ap_const_logic_1;
        else 
            A_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_12_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_12_ce0 <= A_12_ce0_local;

    A_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_12_ce0_local <= ap_const_logic_1;
        else 
            A_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_12_d0 <= in_stream_TDATA;
    A_12_we0 <= A_12_we0_local;

    A_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_12_we0_local <= ap_const_logic_1;
        else 
            A_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_13_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_13_ce0 <= A_13_ce0_local;

    A_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_13_ce0_local <= ap_const_logic_1;
        else 
            A_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_13_d0 <= in_stream_TDATA;
    A_13_we0 <= A_13_we0_local;

    A_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_13_we0_local <= ap_const_logic_1;
        else 
            A_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_14_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_14_ce0 <= A_14_ce0_local;

    A_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_14_ce0_local <= ap_const_logic_1;
        else 
            A_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_14_d0 <= in_stream_TDATA;
    A_14_we0 <= A_14_we0_local;

    A_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_14_we0_local <= ap_const_logic_1;
        else 
            A_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_15_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_15_ce0 <= A_15_ce0_local;

    A_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_15_ce0_local <= ap_const_logic_1;
        else 
            A_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_15_d0 <= in_stream_TDATA;
    A_15_we0 <= A_15_we0_local;

    A_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_15_we0_local <= ap_const_logic_1;
        else 
            A_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_16_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_16_ce0 <= A_16_ce0_local;

    A_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_16_ce0_local <= ap_const_logic_1;
        else 
            A_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_16_d0 <= in_stream_TDATA;
    A_16_we0 <= A_16_we0_local;

    A_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_10) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_16_we0_local <= ap_const_logic_1;
        else 
            A_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_17_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_17_ce0 <= A_17_ce0_local;

    A_17_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_17_ce0_local <= ap_const_logic_1;
        else 
            A_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_17_d0 <= in_stream_TDATA;
    A_17_we0 <= A_17_we0_local;

    A_17_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_11) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_17_we0_local <= ap_const_logic_1;
        else 
            A_17_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_18_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_18_ce0 <= A_18_ce0_local;

    A_18_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_18_ce0_local <= ap_const_logic_1;
        else 
            A_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_18_d0 <= in_stream_TDATA;
    A_18_we0 <= A_18_we0_local;

    A_18_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_12) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_18_we0_local <= ap_const_logic_1;
        else 
            A_18_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_19_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_19_ce0 <= A_19_ce0_local;

    A_19_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_19_ce0_local <= ap_const_logic_1;
        else 
            A_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_19_d0 <= in_stream_TDATA;
    A_19_we0 <= A_19_we0_local;

    A_19_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_13) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_19_we0_local <= ap_const_logic_1;
        else 
            A_19_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_1_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_1_ce0 <= A_1_ce0_local;

    A_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_1_ce0_local <= ap_const_logic_1;
        else 
            A_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_1_d0 <= in_stream_TDATA;
    A_1_we0 <= A_1_we0_local;

    A_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_1_we0_local <= ap_const_logic_1;
        else 
            A_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_20_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_20_ce0 <= A_20_ce0_local;

    A_20_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_20_ce0_local <= ap_const_logic_1;
        else 
            A_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_20_d0 <= in_stream_TDATA;
    A_20_we0 <= A_20_we0_local;

    A_20_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_14) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_20_we0_local <= ap_const_logic_1;
        else 
            A_20_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_21_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_21_ce0 <= A_21_ce0_local;

    A_21_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_21_ce0_local <= ap_const_logic_1;
        else 
            A_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_21_d0 <= in_stream_TDATA;
    A_21_we0 <= A_21_we0_local;

    A_21_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_15) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_21_we0_local <= ap_const_logic_1;
        else 
            A_21_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_22_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_22_ce0 <= A_22_ce0_local;

    A_22_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_22_ce0_local <= ap_const_logic_1;
        else 
            A_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_22_d0 <= in_stream_TDATA;
    A_22_we0 <= A_22_we0_local;

    A_22_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_16) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_22_we0_local <= ap_const_logic_1;
        else 
            A_22_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_23_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_23_ce0 <= A_23_ce0_local;

    A_23_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_23_ce0_local <= ap_const_logic_1;
        else 
            A_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_23_d0 <= in_stream_TDATA;
    A_23_we0 <= A_23_we0_local;

    A_23_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_17) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_23_we0_local <= ap_const_logic_1;
        else 
            A_23_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_24_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_24_ce0 <= A_24_ce0_local;

    A_24_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_24_ce0_local <= ap_const_logic_1;
        else 
            A_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_24_d0 <= in_stream_TDATA;
    A_24_we0 <= A_24_we0_local;

    A_24_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_18) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_24_we0_local <= ap_const_logic_1;
        else 
            A_24_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_25_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_25_ce0 <= A_25_ce0_local;

    A_25_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_25_ce0_local <= ap_const_logic_1;
        else 
            A_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_25_d0 <= in_stream_TDATA;
    A_25_we0 <= A_25_we0_local;

    A_25_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_19) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_25_we0_local <= ap_const_logic_1;
        else 
            A_25_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_26_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_26_ce0 <= A_26_ce0_local;

    A_26_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_26_ce0_local <= ap_const_logic_1;
        else 
            A_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_26_d0 <= in_stream_TDATA;
    A_26_we0 <= A_26_we0_local;

    A_26_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1A) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_26_we0_local <= ap_const_logic_1;
        else 
            A_26_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_27_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_27_ce0 <= A_27_ce0_local;

    A_27_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_27_ce0_local <= ap_const_logic_1;
        else 
            A_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_27_d0 <= in_stream_TDATA;
    A_27_we0 <= A_27_we0_local;

    A_27_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1B) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_27_we0_local <= ap_const_logic_1;
        else 
            A_27_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_28_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_28_ce0 <= A_28_ce0_local;

    A_28_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_28_ce0_local <= ap_const_logic_1;
        else 
            A_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_28_d0 <= in_stream_TDATA;
    A_28_we0 <= A_28_we0_local;

    A_28_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1C) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_28_we0_local <= ap_const_logic_1;
        else 
            A_28_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_29_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_29_ce0 <= A_29_ce0_local;

    A_29_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_29_ce0_local <= ap_const_logic_1;
        else 
            A_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_29_d0 <= in_stream_TDATA;
    A_29_we0 <= A_29_we0_local;

    A_29_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1D) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_29_we0_local <= ap_const_logic_1;
        else 
            A_29_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_2_ce0 <= A_2_ce0_local;

    A_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_2_ce0_local <= ap_const_logic_1;
        else 
            A_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_2_d0 <= in_stream_TDATA;
    A_2_we0 <= A_2_we0_local;

    A_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_2) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_2_we0_local <= ap_const_logic_1;
        else 
            A_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_30_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_30_ce0 <= A_30_ce0_local;

    A_30_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_30_ce0_local <= ap_const_logic_1;
        else 
            A_30_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_30_d0 <= in_stream_TDATA;
    A_30_we0 <= A_30_we0_local;

    A_30_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1E) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_30_we0_local <= ap_const_logic_1;
        else 
            A_30_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_31_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_31_ce0 <= A_31_ce0_local;

    A_31_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_31_ce0_local <= ap_const_logic_1;
        else 
            A_31_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_31_d0 <= in_stream_TDATA;
    A_31_we0 <= A_31_we0_local;

    A_31_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_1F) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_31_we0_local <= ap_const_logic_1;
        else 
            A_31_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_3_ce0 <= A_3_ce0_local;

    A_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_3_ce0_local <= ap_const_logic_1;
        else 
            A_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_3_d0 <= in_stream_TDATA;
    A_3_we0 <= A_3_we0_local;

    A_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_3) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_3_we0_local <= ap_const_logic_1;
        else 
            A_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_4_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_4_ce0 <= A_4_ce0_local;

    A_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_4_ce0_local <= ap_const_logic_1;
        else 
            A_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_4_d0 <= in_stream_TDATA;
    A_4_we0 <= A_4_we0_local;

    A_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_4) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_4_we0_local <= ap_const_logic_1;
        else 
            A_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_5_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_5_ce0 <= A_5_ce0_local;

    A_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_5_ce0_local <= ap_const_logic_1;
        else 
            A_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_5_d0 <= in_stream_TDATA;
    A_5_we0 <= A_5_we0_local;

    A_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_5) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_5_we0_local <= ap_const_logic_1;
        else 
            A_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_6_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_6_ce0 <= A_6_ce0_local;

    A_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_6_ce0_local <= ap_const_logic_1;
        else 
            A_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_6_d0 <= in_stream_TDATA;
    A_6_we0 <= A_6_we0_local;

    A_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_6) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_6_we0_local <= ap_const_logic_1;
        else 
            A_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_7_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_7_ce0 <= A_7_ce0_local;

    A_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_7_ce0_local <= ap_const_logic_1;
        else 
            A_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_7_d0 <= in_stream_TDATA;
    A_7_we0 <= A_7_we0_local;

    A_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_7) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_7_we0_local <= ap_const_logic_1;
        else 
            A_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_8_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_8_ce0 <= A_8_ce0_local;

    A_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_8_ce0_local <= ap_const_logic_1;
        else 
            A_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_8_d0 <= in_stream_TDATA;
    A_8_we0 <= A_8_we0_local;

    A_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_8) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_8_we0_local <= ap_const_logic_1;
        else 
            A_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_9_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_9_ce0 <= A_9_ce0_local;

    A_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_9_ce0_local <= ap_const_logic_1;
        else 
            A_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_9_d0 <= in_stream_TDATA;
    A_9_we0 <= A_9_we0_local;

    A_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_9) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_9_we0_local <= ap_const_logic_1;
        else 
            A_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_address0 <= zext_ln23_fu_779_p1(5 - 1 downto 0);
    A_ce0 <= A_ce0_local;

    A_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_ce0_local <= ap_const_logic_1;
        else 
            A_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    A_d0 <= in_stream_TDATA;
    A_we0 <= A_we0_local;

    A_we0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1, trunc_ln24_reg_886)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (trunc_ln24_reg_886 = ap_const_lv5_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            A_we0_local <= ap_const_logic_1;
        else 
            A_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln23_1_fu_654_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv11_1));
    add_ln23_fu_766_p2 <= std_logic_vector(unsigned(i_fu_188) + unsigned(ap_const_lv6_1));
    add_ln24_fu_752_p2 <= std_logic_vector(unsigned(select_ln23_fu_674_p3) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_TVALID)
    begin
                ap_block_pp0_stage0_subdone <= ((in_stream_TVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln23_fu_648_p2)
    begin
        if (((icmp_ln23_fu_648_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten_fu_192, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_192;
        end if; 
    end process;

    icmp_ln23_fu_648_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv11_400) else "0";
    icmp_ln24_fu_668_p2 <= "1" when (j_fu_184 = ap_const_lv6_20) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, in_stream_TVALID, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    select_ln23_1_fu_772_p3 <= 
        add_ln23_fu_766_p2 when (icmp_ln24_reg_881(0) = '1') else 
        i_fu_188;
    select_ln23_fu_674_p3 <= 
        ap_const_lv6_0 when (icmp_ln24_fu_668_p2(0) = '1') else 
        j_fu_184;
    trunc_ln24_fu_682_p1 <= select_ln23_fu_674_p3(5 - 1 downto 0);
    zext_ln23_fu_779_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln23_1_fu_772_p3),64));
end behav;
