// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module matrix_mult_matrix_mult_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_stream_TVALID,
        A_address0,
        A_ce0,
        A_we0,
        A_d0,
        A_1_address0,
        A_1_ce0,
        A_1_we0,
        A_1_d0,
        A_2_address0,
        A_2_ce0,
        A_2_we0,
        A_2_d0,
        A_3_address0,
        A_3_ce0,
        A_3_we0,
        A_3_d0,
        A_4_address0,
        A_4_ce0,
        A_4_we0,
        A_4_d0,
        A_5_address0,
        A_5_ce0,
        A_5_we0,
        A_5_d0,
        A_6_address0,
        A_6_ce0,
        A_6_we0,
        A_6_d0,
        A_7_address0,
        A_7_ce0,
        A_7_we0,
        A_7_d0,
        A_8_address0,
        A_8_ce0,
        A_8_we0,
        A_8_d0,
        A_9_address0,
        A_9_ce0,
        A_9_we0,
        A_9_d0,
        A_10_address0,
        A_10_ce0,
        A_10_we0,
        A_10_d0,
        A_11_address0,
        A_11_ce0,
        A_11_we0,
        A_11_d0,
        A_12_address0,
        A_12_ce0,
        A_12_we0,
        A_12_d0,
        A_13_address0,
        A_13_ce0,
        A_13_we0,
        A_13_d0,
        A_14_address0,
        A_14_ce0,
        A_14_we0,
        A_14_d0,
        A_15_address0,
        A_15_ce0,
        A_15_we0,
        A_15_d0,
        A_16_address0,
        A_16_ce0,
        A_16_we0,
        A_16_d0,
        A_17_address0,
        A_17_ce0,
        A_17_we0,
        A_17_d0,
        A_18_address0,
        A_18_ce0,
        A_18_we0,
        A_18_d0,
        A_19_address0,
        A_19_ce0,
        A_19_we0,
        A_19_d0,
        A_20_address0,
        A_20_ce0,
        A_20_we0,
        A_20_d0,
        A_21_address0,
        A_21_ce0,
        A_21_we0,
        A_21_d0,
        A_22_address0,
        A_22_ce0,
        A_22_we0,
        A_22_d0,
        A_23_address0,
        A_23_ce0,
        A_23_we0,
        A_23_d0,
        A_24_address0,
        A_24_ce0,
        A_24_we0,
        A_24_d0,
        A_25_address0,
        A_25_ce0,
        A_25_we0,
        A_25_d0,
        A_26_address0,
        A_26_ce0,
        A_26_we0,
        A_26_d0,
        A_27_address0,
        A_27_ce0,
        A_27_we0,
        A_27_d0,
        A_28_address0,
        A_28_ce0,
        A_28_we0,
        A_28_d0,
        A_29_address0,
        A_29_ce0,
        A_29_we0,
        A_29_d0,
        A_30_address0,
        A_30_ce0,
        A_30_we0,
        A_30_d0,
        A_31_address0,
        A_31_ce0,
        A_31_we0,
        A_31_d0,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_stream_TVALID;
output  [4:0] A_address0;
output   A_ce0;
output   A_we0;
output  [31:0] A_d0;
output  [4:0] A_1_address0;
output   A_1_ce0;
output   A_1_we0;
output  [31:0] A_1_d0;
output  [4:0] A_2_address0;
output   A_2_ce0;
output   A_2_we0;
output  [31:0] A_2_d0;
output  [4:0] A_3_address0;
output   A_3_ce0;
output   A_3_we0;
output  [31:0] A_3_d0;
output  [4:0] A_4_address0;
output   A_4_ce0;
output   A_4_we0;
output  [31:0] A_4_d0;
output  [4:0] A_5_address0;
output   A_5_ce0;
output   A_5_we0;
output  [31:0] A_5_d0;
output  [4:0] A_6_address0;
output   A_6_ce0;
output   A_6_we0;
output  [31:0] A_6_d0;
output  [4:0] A_7_address0;
output   A_7_ce0;
output   A_7_we0;
output  [31:0] A_7_d0;
output  [4:0] A_8_address0;
output   A_8_ce0;
output   A_8_we0;
output  [31:0] A_8_d0;
output  [4:0] A_9_address0;
output   A_9_ce0;
output   A_9_we0;
output  [31:0] A_9_d0;
output  [4:0] A_10_address0;
output   A_10_ce0;
output   A_10_we0;
output  [31:0] A_10_d0;
output  [4:0] A_11_address0;
output   A_11_ce0;
output   A_11_we0;
output  [31:0] A_11_d0;
output  [4:0] A_12_address0;
output   A_12_ce0;
output   A_12_we0;
output  [31:0] A_12_d0;
output  [4:0] A_13_address0;
output   A_13_ce0;
output   A_13_we0;
output  [31:0] A_13_d0;
output  [4:0] A_14_address0;
output   A_14_ce0;
output   A_14_we0;
output  [31:0] A_14_d0;
output  [4:0] A_15_address0;
output   A_15_ce0;
output   A_15_we0;
output  [31:0] A_15_d0;
output  [4:0] A_16_address0;
output   A_16_ce0;
output   A_16_we0;
output  [31:0] A_16_d0;
output  [4:0] A_17_address0;
output   A_17_ce0;
output   A_17_we0;
output  [31:0] A_17_d0;
output  [4:0] A_18_address0;
output   A_18_ce0;
output   A_18_we0;
output  [31:0] A_18_d0;
output  [4:0] A_19_address0;
output   A_19_ce0;
output   A_19_we0;
output  [31:0] A_19_d0;
output  [4:0] A_20_address0;
output   A_20_ce0;
output   A_20_we0;
output  [31:0] A_20_d0;
output  [4:0] A_21_address0;
output   A_21_ce0;
output   A_21_we0;
output  [31:0] A_21_d0;
output  [4:0] A_22_address0;
output   A_22_ce0;
output   A_22_we0;
output  [31:0] A_22_d0;
output  [4:0] A_23_address0;
output   A_23_ce0;
output   A_23_we0;
output  [31:0] A_23_d0;
output  [4:0] A_24_address0;
output   A_24_ce0;
output   A_24_we0;
output  [31:0] A_24_d0;
output  [4:0] A_25_address0;
output   A_25_ce0;
output   A_25_we0;
output  [31:0] A_25_d0;
output  [4:0] A_26_address0;
output   A_26_ce0;
output   A_26_we0;
output  [31:0] A_26_d0;
output  [4:0] A_27_address0;
output   A_27_ce0;
output   A_27_we0;
output  [31:0] A_27_d0;
output  [4:0] A_28_address0;
output   A_28_ce0;
output   A_28_we0;
output  [31:0] A_28_d0;
output  [4:0] A_29_address0;
output   A_29_ce0;
output   A_29_we0;
output  [31:0] A_29_d0;
output  [4:0] A_30_address0;
output   A_30_ce0;
output   A_30_we0;
output  [31:0] A_30_d0;
output  [4:0] A_31_address0;
output   A_31_ce0;
output   A_31_we0;
output  [31:0] A_31_d0;
input  [31:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;

reg ap_idle;
reg in_stream_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln23_fu_648_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire    ap_block_pp0_stage0_11001_grp0;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln24_fu_668_p2;
reg   [0:0] icmp_ln24_reg_881;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [4:0] trunc_ln24_fu_682_p1;
reg   [4:0] trunc_ln24_reg_886;
wire   [63:0] zext_ln23_fu_779_p1;
reg   [5:0] j_fu_184;
wire   [5:0] add_ln24_fu_752_p2;
wire    ap_loop_init;
reg   [5:0] i_fu_188;
wire   [5:0] select_ln23_1_fu_772_p3;
reg   [10:0] indvar_flatten_fu_192;
wire   [10:0] add_ln23_1_fu_654_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg    A_30_we0_local;
reg    A_30_ce0_local;
reg    A_29_we0_local;
reg    A_29_ce0_local;
reg    A_28_we0_local;
reg    A_28_ce0_local;
reg    A_27_we0_local;
reg    A_27_ce0_local;
reg    A_26_we0_local;
reg    A_26_ce0_local;
reg    A_25_we0_local;
reg    A_25_ce0_local;
reg    A_24_we0_local;
reg    A_24_ce0_local;
reg    A_23_we0_local;
reg    A_23_ce0_local;
reg    A_22_we0_local;
reg    A_22_ce0_local;
reg    A_21_we0_local;
reg    A_21_ce0_local;
reg    A_20_we0_local;
reg    A_20_ce0_local;
reg    A_19_we0_local;
reg    A_19_ce0_local;
reg    A_18_we0_local;
reg    A_18_ce0_local;
reg    A_17_we0_local;
reg    A_17_ce0_local;
reg    A_16_we0_local;
reg    A_16_ce0_local;
reg    A_15_we0_local;
reg    A_15_ce0_local;
reg    A_14_we0_local;
reg    A_14_ce0_local;
reg    A_13_we0_local;
reg    A_13_ce0_local;
reg    A_12_we0_local;
reg    A_12_ce0_local;
reg    A_11_we0_local;
reg    A_11_ce0_local;
reg    A_10_we0_local;
reg    A_10_ce0_local;
reg    A_9_we0_local;
reg    A_9_ce0_local;
reg    A_8_we0_local;
reg    A_8_ce0_local;
reg    A_7_we0_local;
reg    A_7_ce0_local;
reg    A_6_we0_local;
reg    A_6_ce0_local;
reg    A_5_we0_local;
reg    A_5_ce0_local;
reg    A_4_we0_local;
reg    A_4_ce0_local;
reg    A_3_we0_local;
reg    A_3_ce0_local;
reg    A_2_we0_local;
reg    A_2_ce0_local;
reg    A_1_we0_local;
reg    A_1_ce0_local;
reg    A_we0_local;
reg    A_ce0_local;
reg    A_31_we0_local;
reg    A_31_ce0_local;
wire   [5:0] select_ln23_fu_674_p3;
wire   [5:0] add_ln23_fu_766_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 j_fu_184 = 6'd0;
#0 i_fu_188 = 6'd0;
#0 indvar_flatten_fu_192 = 11'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            i_fu_188 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            i_fu_188 <= select_ln23_1_fu_772_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln23_fu_648_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_192 <= add_ln23_1_fu_654_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_192 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_184 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_184 <= add_ln24_fu_752_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln24_reg_881 <= icmp_ln24_fu_668_p2;
        trunc_ln24_reg_886 <= trunc_ln24_fu_682_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_10_ce0_local = 1'b1;
    end else begin
        A_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd10) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_10_we0_local = 1'b1;
    end else begin
        A_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_11_ce0_local = 1'b1;
    end else begin
        A_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd11) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_11_we0_local = 1'b1;
    end else begin
        A_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_12_ce0_local = 1'b1;
    end else begin
        A_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd12) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_12_we0_local = 1'b1;
    end else begin
        A_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_13_ce0_local = 1'b1;
    end else begin
        A_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd13) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_13_we0_local = 1'b1;
    end else begin
        A_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_14_ce0_local = 1'b1;
    end else begin
        A_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd14) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_14_we0_local = 1'b1;
    end else begin
        A_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_15_ce0_local = 1'b1;
    end else begin
        A_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd15) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_15_we0_local = 1'b1;
    end else begin
        A_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_16_ce0_local = 1'b1;
    end else begin
        A_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd16) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_16_we0_local = 1'b1;
    end else begin
        A_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_17_ce0_local = 1'b1;
    end else begin
        A_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd17) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_17_we0_local = 1'b1;
    end else begin
        A_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_18_ce0_local = 1'b1;
    end else begin
        A_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd18) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_18_we0_local = 1'b1;
    end else begin
        A_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_19_ce0_local = 1'b1;
    end else begin
        A_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd19) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_19_we0_local = 1'b1;
    end else begin
        A_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_1_ce0_local = 1'b1;
    end else begin
        A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_1_we0_local = 1'b1;
    end else begin
        A_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_20_ce0_local = 1'b1;
    end else begin
        A_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd20) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_20_we0_local = 1'b1;
    end else begin
        A_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_21_ce0_local = 1'b1;
    end else begin
        A_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd21) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_21_we0_local = 1'b1;
    end else begin
        A_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_22_ce0_local = 1'b1;
    end else begin
        A_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd22) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_22_we0_local = 1'b1;
    end else begin
        A_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_23_ce0_local = 1'b1;
    end else begin
        A_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd23) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_23_we0_local = 1'b1;
    end else begin
        A_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_24_ce0_local = 1'b1;
    end else begin
        A_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd24) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_24_we0_local = 1'b1;
    end else begin
        A_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_25_ce0_local = 1'b1;
    end else begin
        A_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd25) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_25_we0_local = 1'b1;
    end else begin
        A_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_26_ce0_local = 1'b1;
    end else begin
        A_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd26) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_26_we0_local = 1'b1;
    end else begin
        A_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_27_ce0_local = 1'b1;
    end else begin
        A_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd27) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_27_we0_local = 1'b1;
    end else begin
        A_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_28_ce0_local = 1'b1;
    end else begin
        A_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd28) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_28_we0_local = 1'b1;
    end else begin
        A_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_29_ce0_local = 1'b1;
    end else begin
        A_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd29) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_29_we0_local = 1'b1;
    end else begin
        A_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_2_ce0_local = 1'b1;
    end else begin
        A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_2_we0_local = 1'b1;
    end else begin
        A_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_30_ce0_local = 1'b1;
    end else begin
        A_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd30) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_30_we0_local = 1'b1;
    end else begin
        A_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_31_ce0_local = 1'b1;
    end else begin
        A_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd31) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_31_we0_local = 1'b1;
    end else begin
        A_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_3_ce0_local = 1'b1;
    end else begin
        A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd3) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_3_we0_local = 1'b1;
    end else begin
        A_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_4_ce0_local = 1'b1;
    end else begin
        A_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd4) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_4_we0_local = 1'b1;
    end else begin
        A_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_5_ce0_local = 1'b1;
    end else begin
        A_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd5) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_5_we0_local = 1'b1;
    end else begin
        A_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_6_ce0_local = 1'b1;
    end else begin
        A_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd6) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_6_we0_local = 1'b1;
    end else begin
        A_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_7_ce0_local = 1'b1;
    end else begin
        A_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd7) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_7_we0_local = 1'b1;
    end else begin
        A_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_8_ce0_local = 1'b1;
    end else begin
        A_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd8) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_8_we0_local = 1'b1;
    end else begin
        A_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_9_ce0_local = 1'b1;
    end else begin
        A_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd9) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_9_we0_local = 1'b1;
    end else begin
        A_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_ce0_local = 1'b1;
    end else begin
        A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (trunc_ln24_reg_886 == 5'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        A_we0_local = 1'b1;
    end else begin
        A_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln23_fu_648_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_10_address0 = zext_ln23_fu_779_p1;

assign A_10_ce0 = A_10_ce0_local;

assign A_10_d0 = in_stream_TDATA;

assign A_10_we0 = A_10_we0_local;

assign A_11_address0 = zext_ln23_fu_779_p1;

assign A_11_ce0 = A_11_ce0_local;

assign A_11_d0 = in_stream_TDATA;

assign A_11_we0 = A_11_we0_local;

assign A_12_address0 = zext_ln23_fu_779_p1;

assign A_12_ce0 = A_12_ce0_local;

assign A_12_d0 = in_stream_TDATA;

assign A_12_we0 = A_12_we0_local;

assign A_13_address0 = zext_ln23_fu_779_p1;

assign A_13_ce0 = A_13_ce0_local;

assign A_13_d0 = in_stream_TDATA;

assign A_13_we0 = A_13_we0_local;

assign A_14_address0 = zext_ln23_fu_779_p1;

assign A_14_ce0 = A_14_ce0_local;

assign A_14_d0 = in_stream_TDATA;

assign A_14_we0 = A_14_we0_local;

assign A_15_address0 = zext_ln23_fu_779_p1;

assign A_15_ce0 = A_15_ce0_local;

assign A_15_d0 = in_stream_TDATA;

assign A_15_we0 = A_15_we0_local;

assign A_16_address0 = zext_ln23_fu_779_p1;

assign A_16_ce0 = A_16_ce0_local;

assign A_16_d0 = in_stream_TDATA;

assign A_16_we0 = A_16_we0_local;

assign A_17_address0 = zext_ln23_fu_779_p1;

assign A_17_ce0 = A_17_ce0_local;

assign A_17_d0 = in_stream_TDATA;

assign A_17_we0 = A_17_we0_local;

assign A_18_address0 = zext_ln23_fu_779_p1;

assign A_18_ce0 = A_18_ce0_local;

assign A_18_d0 = in_stream_TDATA;

assign A_18_we0 = A_18_we0_local;

assign A_19_address0 = zext_ln23_fu_779_p1;

assign A_19_ce0 = A_19_ce0_local;

assign A_19_d0 = in_stream_TDATA;

assign A_19_we0 = A_19_we0_local;

assign A_1_address0 = zext_ln23_fu_779_p1;

assign A_1_ce0 = A_1_ce0_local;

assign A_1_d0 = in_stream_TDATA;

assign A_1_we0 = A_1_we0_local;

assign A_20_address0 = zext_ln23_fu_779_p1;

assign A_20_ce0 = A_20_ce0_local;

assign A_20_d0 = in_stream_TDATA;

assign A_20_we0 = A_20_we0_local;

assign A_21_address0 = zext_ln23_fu_779_p1;

assign A_21_ce0 = A_21_ce0_local;

assign A_21_d0 = in_stream_TDATA;

assign A_21_we0 = A_21_we0_local;

assign A_22_address0 = zext_ln23_fu_779_p1;

assign A_22_ce0 = A_22_ce0_local;

assign A_22_d0 = in_stream_TDATA;

assign A_22_we0 = A_22_we0_local;

assign A_23_address0 = zext_ln23_fu_779_p1;

assign A_23_ce0 = A_23_ce0_local;

assign A_23_d0 = in_stream_TDATA;

assign A_23_we0 = A_23_we0_local;

assign A_24_address0 = zext_ln23_fu_779_p1;

assign A_24_ce0 = A_24_ce0_local;

assign A_24_d0 = in_stream_TDATA;

assign A_24_we0 = A_24_we0_local;

assign A_25_address0 = zext_ln23_fu_779_p1;

assign A_25_ce0 = A_25_ce0_local;

assign A_25_d0 = in_stream_TDATA;

assign A_25_we0 = A_25_we0_local;

assign A_26_address0 = zext_ln23_fu_779_p1;

assign A_26_ce0 = A_26_ce0_local;

assign A_26_d0 = in_stream_TDATA;

assign A_26_we0 = A_26_we0_local;

assign A_27_address0 = zext_ln23_fu_779_p1;

assign A_27_ce0 = A_27_ce0_local;

assign A_27_d0 = in_stream_TDATA;

assign A_27_we0 = A_27_we0_local;

assign A_28_address0 = zext_ln23_fu_779_p1;

assign A_28_ce0 = A_28_ce0_local;

assign A_28_d0 = in_stream_TDATA;

assign A_28_we0 = A_28_we0_local;

assign A_29_address0 = zext_ln23_fu_779_p1;

assign A_29_ce0 = A_29_ce0_local;

assign A_29_d0 = in_stream_TDATA;

assign A_29_we0 = A_29_we0_local;

assign A_2_address0 = zext_ln23_fu_779_p1;

assign A_2_ce0 = A_2_ce0_local;

assign A_2_d0 = in_stream_TDATA;

assign A_2_we0 = A_2_we0_local;

assign A_30_address0 = zext_ln23_fu_779_p1;

assign A_30_ce0 = A_30_ce0_local;

assign A_30_d0 = in_stream_TDATA;

assign A_30_we0 = A_30_we0_local;

assign A_31_address0 = zext_ln23_fu_779_p1;

assign A_31_ce0 = A_31_ce0_local;

assign A_31_d0 = in_stream_TDATA;

assign A_31_we0 = A_31_we0_local;

assign A_3_address0 = zext_ln23_fu_779_p1;

assign A_3_ce0 = A_3_ce0_local;

assign A_3_d0 = in_stream_TDATA;

assign A_3_we0 = A_3_we0_local;

assign A_4_address0 = zext_ln23_fu_779_p1;

assign A_4_ce0 = A_4_ce0_local;

assign A_4_d0 = in_stream_TDATA;

assign A_4_we0 = A_4_we0_local;

assign A_5_address0 = zext_ln23_fu_779_p1;

assign A_5_ce0 = A_5_ce0_local;

assign A_5_d0 = in_stream_TDATA;

assign A_5_we0 = A_5_we0_local;

assign A_6_address0 = zext_ln23_fu_779_p1;

assign A_6_ce0 = A_6_ce0_local;

assign A_6_d0 = in_stream_TDATA;

assign A_6_we0 = A_6_we0_local;

assign A_7_address0 = zext_ln23_fu_779_p1;

assign A_7_ce0 = A_7_ce0_local;

assign A_7_d0 = in_stream_TDATA;

assign A_7_we0 = A_7_we0_local;

assign A_8_address0 = zext_ln23_fu_779_p1;

assign A_8_ce0 = A_8_ce0_local;

assign A_8_d0 = in_stream_TDATA;

assign A_8_we0 = A_8_we0_local;

assign A_9_address0 = zext_ln23_fu_779_p1;

assign A_9_ce0 = A_9_ce0_local;

assign A_9_d0 = in_stream_TDATA;

assign A_9_we0 = A_9_we0_local;

assign A_address0 = zext_ln23_fu_779_p1;

assign A_ce0 = A_ce0_local;

assign A_d0 = in_stream_TDATA;

assign A_we0 = A_we0_local;

assign add_ln23_1_fu_654_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln23_fu_766_p2 = (i_fu_188 + 6'd1);

assign add_ln24_fu_752_p2 = (select_ln23_fu_674_p3 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((in_stream_TVALID == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln23_fu_648_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_668_p2 = ((j_fu_184 == 6'd32) ? 1'b1 : 1'b0);

assign select_ln23_1_fu_772_p3 = ((icmp_ln24_reg_881[0:0] == 1'b1) ? add_ln23_fu_766_p2 : i_fu_188);

assign select_ln23_fu_674_p3 = ((icmp_ln24_fu_668_p2[0:0] == 1'b1) ? 6'd0 : j_fu_184);

assign trunc_ln24_fu_682_p1 = select_ln23_fu_674_p3[4:0];

assign zext_ln23_fu_779_p1 = select_ln23_1_fu_772_p3;

endmodule //matrix_mult_matrix_mult_Pipeline_VITIS_LOOP_23_1_VITIS_LOOP_24_2
