-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cifar10_axis_wrapper_pointwise_conv_2d_cl_array_array_ap_fixed_11_5_0_3_0_24u_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer9_out_dout : IN STD_LOGIC_VECTOR (351 downto 0);
    layer9_out_empty_n : IN STD_LOGIC;
    layer9_out_read : OUT STD_LOGIC;
    layer9_out_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    layer9_out_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    layer10_out_din : OUT STD_LOGIC_VECTOR (263 downto 0);
    layer10_out_full_n : IN STD_LOGIC;
    layer10_out_write : OUT STD_LOGIC;
    layer10_out_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    layer10_out_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of cifar10_axis_wrapper_pointwise_conv_2d_cl_array_array_ap_fixed_11_5_0_3_0_24u_config14_s is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100001";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_4C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001100";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_6D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101101";
    constant ap_const_lv32_6E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101110";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_79 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111001";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000100";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_99 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011001";
    constant ap_const_lv32_9A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011010";
    constant ap_const_lv32_A4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100100";
    constant ap_const_lv32_A5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100101";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111010";
    constant ap_const_lv32_BB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111011";
    constant ap_const_lv32_C5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000101";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_D1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010001";
    constant ap_const_lv32_DB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011011";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100110";
    constant ap_const_lv32_E7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100111";
    constant ap_const_lv32_F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110001";
    constant ap_const_lv32_F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110010";
    constant ap_const_lv32_FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111100";
    constant ap_const_lv32_FD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111101";
    constant ap_const_lv32_107 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000111";
    constant ap_const_lv32_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001000";
    constant ap_const_lv32_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010010";
    constant ap_const_lv32_113 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010011";
    constant ap_const_lv32_11D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011101";
    constant ap_const_lv32_11E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011110";
    constant ap_const_lv32_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101000";
    constant ap_const_lv32_129 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101001";
    constant ap_const_lv32_133 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110011";
    constant ap_const_lv32_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110100";
    constant ap_const_lv32_13E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111110";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_149 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001001";
    constant ap_const_lv32_14A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001010";
    constant ap_const_lv32_154 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010100";
    constant ap_const_lv32_155 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010101";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer9_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln112_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal layer10_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_ih_4_fu_248_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_ih_4_reg_751 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_iw_4_fu_260_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_iw_4_reg_759 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal data_fu_266_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_reg_764 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_1_reg_769 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_2_reg_774 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_3_reg_779 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_4_reg_784 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_5_reg_789 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_6_reg_794 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_7_reg_799 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_8_reg_804 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_9_reg_809 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_10_reg_814 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_11_reg_819 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_12_reg_824 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_13_reg_829 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_14_reg_834 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_15_reg_839 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_16_reg_844 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_17_reg_849 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_18_reg_854 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_19_reg_859 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_20_reg_864 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_21_reg_869 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_22_reg_874 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_31_reg_879 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_23_reg_884 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_24_reg_889 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_25_reg_894 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_26_reg_899 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_27_reg_904 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_28_reg_909 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_29_reg_914 : STD_LOGIC_VECTOR (10 downto 0);
    signal data_30_reg_919 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_reg_924 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done : STD_LOGIC;
    signal res_1_reg_929 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_2_reg_934 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_3_reg_939 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_4_reg_944 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_5_reg_949 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_6_reg_954 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_7_reg_959 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_8_reg_964 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_9_reg_969 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_10_reg_974 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_11_reg_979 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_12_reg_984 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_13_reg_989 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_14_reg_994 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_15_reg_999 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_16_reg_1004 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_17_reg_1009 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_18_reg_1014 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_19_reg_1019 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_20_reg_1024 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_21_reg_1029 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_22_reg_1034 : STD_LOGIC_VECTOR (10 downto 0);
    signal res_23_reg_1039 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_idle : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_ready : STD_LOGIC;
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_3 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_4 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_5 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_6 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_7 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_8 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_9 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_10 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_11 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_12 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_13 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_14 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_15 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_16 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_17 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_18 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_19 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_20 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_21 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_22 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_23 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_iw_reg_185 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln110_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state3_ignore_call35 : BOOLEAN;
    signal i_ih_fu_168 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cifar10_axis_wrapper_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_1_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_2_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_3_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_4_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_5_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_6_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_7_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_8_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_9_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_10_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_11_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_12_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_13_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_14_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_15_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_16_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_17_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_18_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_19_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_20_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_21_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_22_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_23_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_24_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_25_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_26_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_27_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_28_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_29_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_30_val : IN STD_LOGIC_VECTOR (10 downto 0);
        data_31_val : IN STD_LOGIC_VECTOR (10 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_16 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_17 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_18 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_19 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_20 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_21 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_22 : OUT STD_LOGIC_VECTOR (10 downto 0);
        ap_return_23 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196 : component cifar10_axis_wrapper_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start,
        ap_done => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done,
        ap_idle => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_idle,
        ap_ready => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_ready,
        data_0_val => data_reg_764,
        data_1_val => data_1_reg_769,
        data_2_val => data_2_reg_774,
        data_3_val => data_3_reg_779,
        data_4_val => data_4_reg_784,
        data_5_val => data_5_reg_789,
        data_6_val => data_6_reg_794,
        data_7_val => data_7_reg_799,
        data_8_val => data_8_reg_804,
        data_9_val => data_9_reg_809,
        data_10_val => data_10_reg_814,
        data_11_val => data_11_reg_819,
        data_12_val => data_12_reg_824,
        data_13_val => data_13_reg_829,
        data_14_val => data_14_reg_834,
        data_15_val => data_15_reg_839,
        data_16_val => data_16_reg_844,
        data_17_val => data_17_reg_849,
        data_18_val => data_18_reg_854,
        data_19_val => data_19_reg_859,
        data_20_val => data_20_reg_864,
        data_21_val => data_21_reg_869,
        data_22_val => data_22_reg_874,
        data_23_val => data_31_reg_879,
        data_24_val => data_23_reg_884,
        data_25_val => data_24_reg_889,
        data_26_val => data_25_reg_894,
        data_27_val => data_26_reg_899,
        data_28_val => data_27_reg_904,
        data_29_val => data_28_reg_909,
        data_30_val => data_29_reg_914,
        data_31_val => data_30_reg_919,
        ap_return_0 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_0,
        ap_return_1 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_1,
        ap_return_2 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_2,
        ap_return_3 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_3,
        ap_return_4 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_4,
        ap_return_5 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_5,
        ap_return_6 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_6,
        ap_return_7 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_7,
        ap_return_8 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_8,
        ap_return_9 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_9,
        ap_return_10 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_10,
        ap_return_11 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_11,
        ap_return_12 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_12,
        ap_return_13 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_13,
        ap_return_14 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_14,
        ap_return_15 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_15,
        ap_return_16 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_16,
        ap_return_17 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_17,
        ap_return_18 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_18,
        ap_return_19 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_19,
        ap_return_20 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_20,
        ap_return_21 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_21,
        ap_return_22 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_22,
        ap_return_23 => grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_23);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln110_fu_242_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state3_ignore_call35) and (icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_ready = ap_const_logic_1)) then 
                    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_ih_fu_168_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_ih_fu_168 <= ap_const_lv3_0;
            elsif (((ap_const_boolean_0 = ap_block_state3) and (icmp_ln112_fu_254_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_ih_fu_168 <= i_ih_4_reg_751;
            end if; 
        end if;
    end process;

    i_iw_reg_185_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((layer10_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i_iw_reg_185 <= i_iw_4_reg_759;
            elsif (((icmp_ln110_fu_242_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_iw_reg_185 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                data_10_reg_814 <= layer9_out_dout(120 downto 110);
                data_11_reg_819 <= layer9_out_dout(131 downto 121);
                data_12_reg_824 <= layer9_out_dout(142 downto 132);
                data_13_reg_829 <= layer9_out_dout(153 downto 143);
                data_14_reg_834 <= layer9_out_dout(164 downto 154);
                data_15_reg_839 <= layer9_out_dout(175 downto 165);
                data_16_reg_844 <= layer9_out_dout(186 downto 176);
                data_17_reg_849 <= layer9_out_dout(197 downto 187);
                data_18_reg_854 <= layer9_out_dout(208 downto 198);
                data_19_reg_859 <= layer9_out_dout(219 downto 209);
                data_1_reg_769 <= layer9_out_dout(21 downto 11);
                data_20_reg_864 <= layer9_out_dout(230 downto 220);
                data_21_reg_869 <= layer9_out_dout(241 downto 231);
                data_22_reg_874 <= layer9_out_dout(252 downto 242);
                data_23_reg_884 <= layer9_out_dout(274 downto 264);
                data_24_reg_889 <= layer9_out_dout(285 downto 275);
                data_25_reg_894 <= layer9_out_dout(296 downto 286);
                data_26_reg_899 <= layer9_out_dout(307 downto 297);
                data_27_reg_904 <= layer9_out_dout(318 downto 308);
                data_28_reg_909 <= layer9_out_dout(329 downto 319);
                data_29_reg_914 <= layer9_out_dout(340 downto 330);
                data_2_reg_774 <= layer9_out_dout(32 downto 22);
                data_30_reg_919 <= layer9_out_dout(351 downto 341);
                data_31_reg_879 <= layer9_out_dout(263 downto 253);
                data_3_reg_779 <= layer9_out_dout(43 downto 33);
                data_4_reg_784 <= layer9_out_dout(54 downto 44);
                data_5_reg_789 <= layer9_out_dout(65 downto 55);
                data_6_reg_794 <= layer9_out_dout(76 downto 66);
                data_7_reg_799 <= layer9_out_dout(87 downto 77);
                data_8_reg_804 <= layer9_out_dout(98 downto 88);
                data_9_reg_809 <= layer9_out_dout(109 downto 99);
                data_reg_764 <= data_fu_266_p1;
                i_iw_4_reg_759 <= i_iw_4_fu_260_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_ih_4_reg_751 <= i_ih_4_fu_248_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done = ap_const_logic_1))) then
                res_10_reg_974 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_10;
                res_11_reg_979 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_11;
                res_12_reg_984 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_12;
                res_13_reg_989 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_13;
                res_14_reg_994 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_14;
                res_15_reg_999 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_15;
                res_16_reg_1004 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_16;
                res_17_reg_1009 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_17;
                res_18_reg_1014 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_18;
                res_19_reg_1019 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_19;
                res_1_reg_929 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_1;
                res_20_reg_1024 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_20;
                res_21_reg_1029 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_21;
                res_22_reg_1034 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_22;
                res_23_reg_1039 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_23;
                res_2_reg_934 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_2;
                res_3_reg_939 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_3;
                res_4_reg_944 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_4;
                res_5_reg_949 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_5;
                res_6_reg_954 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_6;
                res_7_reg_959 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_7;
                res_8_reg_964 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_8;
                res_9_reg_969 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_9;
                res_reg_924 <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer10_out_full_n, ap_CS_fsm_state3, icmp_ln112_fu_254_p2, ap_CS_fsm_state5, ap_CS_fsm_state2, ap_block_state3, ap_CS_fsm_state4, grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done, icmp_ln110_fu_242_p2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln110_fu_242_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (icmp_ln112_fu_254_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_const_boolean_0 = ap_block_state3) and (icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((layer10_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done)
    begin
        if ((grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(layer10_out_full_n)
    begin
        if ((layer10_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state3_assign_proc : process(layer9_out_empty_n, icmp_ln112_fu_254_p2)
    begin
                ap_block_state3 <= ((icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (layer9_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_ignore_call35_assign_proc : process(layer9_out_empty_n, icmp_ln112_fu_254_p2)
    begin
                ap_block_state3_ignore_call35 <= ((icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (layer9_out_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln110_fu_242_p2)
    begin
        if (((icmp_ln110_fu_242_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_266_p1 <= layer9_out_dout(11 - 1 downto 0);
    grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start <= grp_dense_resource_rf_gt_nin_rem0_ap_fixed_ap_fixed_11_5_0_3_0_config14_mult_s_fu_196_ap_start_reg;
    i_ih_4_fu_248_p2 <= std_logic_vector(unsigned(i_ih_fu_168) + unsigned(ap_const_lv3_1));
    i_iw_4_fu_260_p2 <= std_logic_vector(unsigned(i_iw_reg_185) + unsigned(ap_const_lv3_1));
    icmp_ln110_fu_242_p2 <= "1" when (i_ih_fu_168 = ap_const_lv3_4) else "0";
    icmp_ln112_fu_254_p2 <= "1" when (i_iw_reg_185 = ap_const_lv3_4) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln110_fu_242_p2)
    begin
        if (((icmp_ln110_fu_242_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer10_out_blk_n_assign_proc : process(layer10_out_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            layer10_out_blk_n <= layer10_out_full_n;
        else 
            layer10_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer10_out_din <= (((((((((((((((((((((((res_23_reg_1039 & res_22_reg_1034) & res_21_reg_1029) & res_20_reg_1024) & res_19_reg_1019) & res_18_reg_1014) & res_17_reg_1009) & res_16_reg_1004) & res_15_reg_999) & res_14_reg_994) & res_13_reg_989) & res_12_reg_984) & res_11_reg_979) & res_10_reg_974) & res_9_reg_969) & res_8_reg_964) & res_7_reg_959) & res_6_reg_954) & res_5_reg_949) & res_4_reg_944) & res_3_reg_939) & res_2_reg_934) & res_1_reg_929) & res_reg_924);

    layer10_out_write_assign_proc : process(layer10_out_full_n, ap_CS_fsm_state5)
    begin
        if (((layer10_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            layer10_out_write <= ap_const_logic_1;
        else 
            layer10_out_write <= ap_const_logic_0;
        end if; 
    end process;


    layer9_out_blk_n_assign_proc : process(layer9_out_empty_n, ap_CS_fsm_state3, icmp_ln112_fu_254_p2)
    begin
        if (((icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer9_out_blk_n <= layer9_out_empty_n;
        else 
            layer9_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer9_out_read_assign_proc : process(ap_CS_fsm_state3, icmp_ln112_fu_254_p2, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (icmp_ln112_fu_254_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            layer9_out_read <= ap_const_logic_1;
        else 
            layer9_out_read <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
