[hls]
relative_roots=E:/Andy/COLEGIO/Ingenieria_de_Software/TFG/Project/h/v4_8_14_32_24_final
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=nnet::global_pooling2d_cl<nnet::array<ap_fixed<12, 6, (ap_q_mode)0, (ap_o_mode)3, 0>, 10u>, nnet::array<ap_fixed<12, 5, (ap_q_mode)0, (ap_o_mode)3, 0>, 10u>, config13>/ReadInputWidth 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=nnet::global_pooling2d_cl<nnet::array<ap_fixed<12, 6, (ap_q_mode)0, (ap_o_mode)3, 0>, 10u>, nnet::array<ap_fixed<12, 5, (ap_q_mode)0, (ap_o_mode)3, 0>, 10u>, config13>/ReadInputHeight  
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=axis_to_hls4ml_input/v dim=1 type=complete variable=v
syn.directive.loop_flatten=axis_to_hls4ml_input/VITIS_LOOP_43_1  
syn.directive.loop_flatten=nnet::pooling2d_cl<nnet::array<ap_fixed<9, 3, (ap_q_mode)0, (ap_o_mode)3, 0>, 8u>, nnet::array<ap_fixed<9, 3, (ap_q_mode)0, (ap_o_mode)3, 0>, 8u>, config4>/ReadInputHeight  


